### ISSUE TITLE
Secure note attachments

### ISSUE THREAD

**Issue by astoltz** [lastpass/lastpass-cli#1]
How do I access attachments for secure notes? This is usually where I store private keys.

**Comment by bcopeland** [comment]
As noted in #77 I just push a change to enable parsing of the secure note templates, please try it out.

**Comment by bcopeland** [comment]
Just pushed a new branch which allows viewing attachments using "lpass show":

https://github.com/lastpass/lastpass-cli/tree/topic-attachments

**Comment by kyleburton** [comment]
Thanks for coding this up - I'm trying it out off of your branch and after adding a few `fprintf's`, I think I'm getting back an empty string (JSON) from `cmd-show.c` when it's calling `lastpass_load_attachment`  when it is making the post via `lastpass_load_attachment`.  Is the endpoint `show_website.php` correct?  Or is there a different reason why I might be getting back an empty string? `""`

**Comment by akolesen** [comment]
Double-checked, looks like 
```c
        reply = http_post_lastpass("show_website.php", session, NULL,
                                   "token", session->token,
                                   "getattach", attach->storagekey, NULL);
```
returns `""`

**Comment by spencerwhyte** [comment]
@kyleburton @akolesen "show_website.php" doesn't seem like the correct endpoint. I switched it to "getattach.php". Additionally, the reason that you are be getting back ("") from the call is that the "sharedfolderid" was not being provided to the server in that call. In other words if the attachment was part of a note in a shared folder, it would fail and return nothing ("").
