### ISSUE TITLE
Forward slash is displayed as a new line

### ISSUE THREAD

**Issue by aygee** [lastpass/lastpass-cli#10]
Hi, first I'd like to thank you for the great tool. I love it!

One small problem is that forward slash is displayed as a new line (interpreted as a folder name) when doing 'lpass ls'

For example, I have an entry 'spaceship cpanel / ftp'.
'lpass ls' would show

    spaceship cpanel
        ftp [id: xxxxxxx]

**Comment by bcopeland** [comment]
I think what we should do here is convert _backslash_ to newlines but not forward slashes... since internally a folder like "abc/def/ghi/xyz" is represented as a group called "abc\def\ghi" +  site "xyz"

**Comment by bcopeland** [comment]
ed892c0 should fix this.
