### ISSUE TITLE
smarter match capabilities, case insensitivity

### ISSUE THREAD

**Issue by k0377** [lastpass/lastpass-cli#100]
It is annoying to use the exact name of the password entry. I never remember the exact spelling. Computers should be smart enough to find out for me whether it is `face`, `facebook` or `Facebook`.
```
lpass show face
Error: Could not find specified account 'face'.
```
```
lpass show facebook
Error: Could not find specified account 'face'.
```

**Comment by bcopeland** [comment]
Just use -G and a suitable regex...

lpass show -G face
