### ISSUE TITLE
Suggested patch to make output colorization optional

### ISSUE THREAD

**Issue by HippoMan** [lastpass/lastpass-cli#102]
This is not technically an "issue", but I haven't found another way to suggest a patch that I came up with to add a desired feature to lastpass-cli.  If I missed something, please forgive my bandwidth here ... but I would be grateful if you'd at least consider my patch, as follows:

I'd like to control lastpass-cli via "expect", but the terminal color sequences make it hard to match output strings. Therefore, I have patched the latest lastpass-cli (August 1, 2015, version) so that output colorization is optional.

In my patched version, if the environment variable LPASS_DISABLE_COLOR=1 is set, then no output colorization is performed. If this environment variable is not set or set to any other value, then output is colorized as normal.

Here's my patch. What do you folks think?

PS: check the routine "disable_color()" which I added to util.c.

Thank you very much for at least considering my suggestion.

    *** lastpass-cli-master.orig/cmd-login.c	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/cmd-login.c	Sat Aug  8 18:32:39 2015
    ***************
    *** 71,77 ****
    --- 71,87 ----
      
      	do {
      		free(password);
    + #ifdef ORIGINAL
      		password = password_prompt("Master Password", error, "Please enter the LastPass master password for <%s>.", username);
    + #else /* !ORIGINAL */
    + 		if (disable_color()) {
    + 			password = password_prompt("\nMaster Password", error, "Please enter the LastPass master password for <%s>.", username);
    + 			terminal_fprintf(stderr, "\r\n");
    + 		}
    + 		else {
    + 			password = password_prompt("Master Password", error, "Please enter the LastPass master password for <%s>.", username);
    + 		}
    + #endif /* !ORIGINAL */
      		if (!password)
      			die("Failed to enter correct password.");
      
    ***************
    *** 93,98 ****
    --- 103,114 ----
      	session_free(session);
      	session = NULL;
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_printf("Success: Logged in as %s.\n", username);
    + 	}
    + 	else
    + #endif /* !ORIGINAL */
      	terminal_printf(TERMINAL_FG_GREEN TERMINAL_BOLD "Success" TERMINAL_RESET ": Logged in as " TERMINAL_UNDERLINE "%s" TERMINAL_RESET ".\n", username);
      
      	return 0;
    *** lastpass-cli-master.orig/cmd-logout.c	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/cmd-logout.c	Sat Aug  8 18:08:52 2015
    ***************
    *** 49,54 ****
    --- 49,60 ----
      		die("Not currently logged in.");
      
      	if (!force && !ask_yes_no(true, "Are you sure you would like to log out?")) {
    + #ifndef ORIGINAL
    + 		if (disable_color()) {
    + 			terminal_printf("Log out: aborted.\n");
    + 		}
    + 		else
    + #endif /* !ORIGINAL */
      		terminal_printf(TERMINAL_FG_YELLOW TERMINAL_BOLD "Log out" TERMINAL_RESET ": aborted.\n");
      		return 1;
      	}
    ***************
    *** 65,70 ****
    --- 71,82 ----
      	agent_kill();
      	upload_queue_kill();
      	lastpass_logout(session);
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_printf("Log out: complete.\n");
    + 	}
    + 	else
    + #endif /* !ORIGINAL */
      	terminal_printf(TERMINAL_FG_YELLOW TERMINAL_BOLD "Log out" TERMINAL_RESET ": complete.\n");
      	return 0;
      }
    *** lastpass-cli-master.orig/cmd-ls.c	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/cmd-ls.c	Sat Aug  8 18:07:18 2015
    ***************
    *** 73,84 ****
    --- 73,103 ----
      		if (node->name) {
      			for (int i = 0; i < level; ++i)
      				printf("    ");
    + #ifdef ORIGINAL
      			if (node->account)
      				terminal_printf(TERMINAL_FG_GREEN TERMINAL_BOLD "%s" TERMINAL_NO_BOLD " [id: %s]" TERMINAL_RESET "\n", node->name, node->account->id);
      			else if (node->shared)
      				terminal_printf(TERMINAL_FG_CYAN TERMINAL_BOLD "%s" TERMINAL_RESET "\n", node->name);
      			else
      				terminal_printf(TERMINAL_FG_BLUE TERMINAL_BOLD "%s" TERMINAL_RESET "\n", node->name);
    + #else  /* !ORIGINAL */
    + 			if (disable_color()) {
    + 				if (node->account)
    + 					terminal_printf("%s [id: %s]\n", node->name, node->account->id);
    + 				else if (node->shared)
    + 					terminal_printf("%s\n", node->name);
    + 				else
    + 					terminal_printf("%s\n", node->name);
    + 			}
    + 			else {
    + 				if (node->account)
    + 					terminal_printf(TERMINAL_FG_GREEN TERMINAL_BOLD "%s" TERMINAL_NO_BOLD " [id: %s]" TERMINAL_RESET "\n", node->name, node->account->id);
    + 				else if (node->shared)
    + 					terminal_printf(TERMINAL_FG_CYAN TERMINAL_BOLD "%s" TERMINAL_RESET "\n", node->name);
    + 				else
    + 					terminal_printf(TERMINAL_FG_BLUE TERMINAL_BOLD "%s" TERMINAL_RESET "\n", node->name);
    + 			}
    + #endif /* !ORIGINAL */
      		}
      		print_node(node->first_child, level + 1);
      	}
    ***************
    *** 115,120 ****
    --- 134,144 ----
      	char *fullname;
      	enum blobsync sync = BLOB_SYNC_AUTO;
      	enum color_mode cmode = COLOR_MODE_AUTO;
    + #ifndef ORIGINAL
    + 	if (disable_color()) {	
    +         	cmode = COLOR_MODE_NEVER;
    + 	}
    + #endif /* ! ORIGINAL */
      	bool print_tree;
      	struct account *account;
      
    *** lastpass-cli-master.orig/cmd-share.c	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/cmd-share.c	Sat Aug  8 18:05:22 2015
    ***************
    *** 62,67 ****
    --- 62,74 ----
      		die("Unable to access user list for share %s\n",
      		    args->sharename);
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_printf("%-40s %6s %6s %6s %6s %6s\n",
    + 		       "User", "RO", "Admin", "Hide", "OutEnt", "Accept");
    + 	}
    + 	else
    + #endif /* !ORIGINAL */
      	terminal_printf(TERMINAL_FG_YELLOW TERMINAL_BOLD "%-40s %6s %6s %6s %6s %6s" TERMINAL_RESET "\n",
      	       "User", "RO", "Admin", "Hide", "OutEnt", "Accept");
      
    ***************
    *** 92,97 ****
    --- 99,111 ----
      		return 0;
      
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_printf("%-40s %6s %6s %6s %6s %6s\n",
    + 				"Group", "RO", "Admin", "Hide", "OutEnt", "Accept");
    + 	}
    + 	else
    + #endif /* !ORIGINAL */
      	terminal_printf(TERMINAL_FG_YELLOW TERMINAL_BOLD "%-40s %6s %6s %6s %6s %6s"
      			TERMINAL_RESET "\n",
      			"Group", "RO", "Admin", "Hide", "OutEnt", "Accept");
    *** lastpass-cli-master.orig/cmd-show.c	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/cmd-show.c	Sat Aug  8 18:03:50 2015
    ***************
    *** 28,39 ****
    --- 28,58 ----
      
      static void print_header(struct account *found)
      {
    + #ifdef ORIGINAL
      	if (found->share)
      		terminal_printf(TERMINAL_FG_CYAN "%s/" TERMINAL_RESET, found->share->name);
      	if (strlen(found->group))
      		terminal_printf(TERMINAL_FG_BLUE "%s/" TERMINAL_BOLD "%s" TERMINAL_RESET TERMINAL_FG_GREEN " [id: %s]" TERMINAL_RESET "\n", found->group, found->name, found->id);
      	else
      		terminal_printf(TERMINAL_FG_BLUE TERMINAL_BOLD "%s" TERMINAL_RESET TERMINAL_FG_GREEN " [id: %s]" TERMINAL_RESET "\n", found->name, found->id);
    + #else  /* !ORIGINAL */
    + 	if (disable_color()) {
    + 		if (found->share)
    + 			terminal_printf("%s/", found->share->name);
    + 		if (strlen(found->group))
    + 			terminal_printf("%s/%s [id: %s]\n", found->group, found->name, found->id);
    + 		else
    + 			terminal_printf("%s [id: %s]\n", found->name, found->id);
    + 	}
    + 	else {
    + 		if (found->share)
    + 			terminal_printf(TERMINAL_FG_CYAN "%s/" TERMINAL_RESET, found->share->name);
    + 		if (strlen(found->group))
    + 			terminal_printf(TERMINAL_FG_BLUE "%s/" TERMINAL_BOLD "%s" TERMINAL_RESET TERMINAL_FG_GREEN " [id: %s]" TERMINAL_RESET "\n", found->group, found->name, found->id);
    + 		else
    + 			terminal_printf(TERMINAL_FG_BLUE TERMINAL_BOLD "%s" TERMINAL_RESET TERMINAL_FG_GREEN " [id: %s]" TERMINAL_RESET "\n", found->name, found->id);
    + 	}
    + #endif /* !ORIGINAL */
      }
      
      int cmd_show(int argc, char **argv)
    ***************
    *** 148,153 ****
    --- 167,178 ----
      	last_found = list_last_entry(&matches, struct account, match_list);
      	if (found != last_found) {
      		/* Multiple matches; dump the ids and exit */
    + #ifndef ORIGINAL
    + 		if (disable_color()) {
    + 			terminal_printf("Multiple matches found.\n");
    + 		}
    + 		else
    + #endif /* !ORIGINAL */
      		terminal_printf(TERMINAL_FG_YELLOW TERMINAL_BOLD "Multiple matches found.\n");
      		list_for_each_entry(found, &matches, match_list)
      			print_header(found);
    ***************
    *** 196,201 ****
    --- 221,227 ----
      	if (choice == ALL) {
      		print_header(found);
      
    + #ifdef ORIGINAL
      		if (strlen(found->username))
      			terminal_printf(TERMINAL_FG_YELLOW "%s" TERMINAL_RESET ": %s\n", "Username", found->username);
      		if (strlen(found->password))
    ***************
    *** 210,215 ****
    --- 236,275 ----
      		}
      		if (strlen(found->note))
      			terminal_printf(TERMINAL_FG_YELLOW "%s" TERMINAL_RESET ":\n%s\n", "Notes", found->note);
    + #else  /* !ORIGINAL */
    + 		if (disable_color()) {
    + 			if (strlen(found->username))
    + 				terminal_printf("%s: %s\n", "Username", found->username);
    + 			if (strlen(found->password))
    + 				terminal_printf("%s: %s\n", "Password", found->password);
    + 			if (strlen(found->url) && strcmp(found->url, "http://"))
    + 				terminal_printf("%s: %s\n", "URL", found->url);
    + 
    + 			list_for_each_entry(found_field, &found->field_head, list) {
    + 				pretty_field = pretty_field_value(found_field);
    + 				terminal_printf("%s: %s\n", found_field->name, pretty_field);
    + 				free(pretty_field);
    + 			}
    + 			if (strlen(found->note))
    + 				terminal_printf("%s:\n%s\n", "Notes", found->note);
    + 		}
    + 		else {
    + 			if (strlen(found->username))
    + 				terminal_printf(TERMINAL_FG_YELLOW "%s" TERMINAL_RESET ": %s\n", "Username", found->username);
    + 			if (strlen(found->password))
    + 				terminal_printf(TERMINAL_FG_YELLOW "%s" TERMINAL_RESET ": %s\n", "Password", found->password);
    + 			if (strlen(found->url) && strcmp(found->url, "http://"))
    + 				terminal_printf(TERMINAL_FG_YELLOW "%s" TERMINAL_RESET ": %s\n", "URL", found->url);
    + 
    + 			list_for_each_entry(found_field, &found->field_head, list) {
    + 				pretty_field = pretty_field_value(found_field);
    + 				terminal_printf(TERMINAL_FG_YELLOW "%s" TERMINAL_RESET ": %s\n", found_field->name, pretty_field);
    + 				free(pretty_field);
    + 			}
    + 			if (strlen(found->note))
    + 				terminal_printf(TERMINAL_FG_YELLOW "%s" TERMINAL_RESET ":\n%s\n", "Notes", found->note);
    + 		}
    + #endif /* !ORIGINAL */
      	} else {
      		if (!value)
      			die("Programming error.");
    *** lastpass-cli-master.orig/endpoints-login.c	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/endpoints-login.c	Sat Aug  8 18:23:57 2015
    ***************
    *** 171,176 ****
    --- 171,182 ----
      		return error_other(message, session, "Could not determine out-of-band type.");
      	can_do_passcode = has_capabilities(oob_capabilities, "passcode");
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_fprintf(stderr, "Waiting for approval of out-of-band %s login%s...", *oob_name, can_do_passcode ? ", or press Ctrl+C to enter a passcode" : "");
    + 	}
    + 	else
    + #endif /* !ORIGINAL */
      	terminal_fprintf(stderr, TERMINAL_FG_YELLOW TERMINAL_BOLD "Waiting for approval of out-of-band %s login%s" TERMINAL_NO_BOLD "...", *oob_name, can_do_passcode ? ", or press Ctrl+C to enter a passcode" : "");
      	append_post(args, "outofbandrequest", "1");
      	for (;;) {
    ***************
    *** 213,218 ****
    --- 219,230 ----
      	ret = false;
      	goto out;
      out:
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_fprintf(stderr, "                                                            \r");
    + 	}
    + 	else
    + #endif /* !ORIGINAL */
      	terminal_fprintf(stderr, TERMINAL_RESET "\n" TERMINAL_UP_CURSOR(1) TERMINAL_CLEAR_DOWN);
      	return ret;
      }
    *** lastpass-cli-master.orig/password.c	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/password.c	Sat Aug  8 18:31:06 2015
    ***************
    *** 24,29 ****
    --- 24,30 ----
      	char *password = NULL, *lastlf;
      	size_t len = 0;
      
    + #ifdef ORIGINAL
      	terminal_fprintf(stderr, TERMINAL_FG_YELLOW TERMINAL_BOLD);
      	vfprintf(stderr, descfmt, params);
      	terminal_fprintf(stderr, TERMINAL_RESET "\n\n");
    ***************
    *** 32,37 ****
    --- 33,60 ----
      		terminal_fprintf(stderr, TERMINAL_FG_RED TERMINAL_BOLD "%s" TERMINAL_RESET "\n", error);
      
      	terminal_fprintf(stderr, TERMINAL_BOLD "%s" TERMINAL_RESET ": ", prompt);
    + #else  /* !ORIGINAL */
    + 	if (disable_color()) {
    + 		vfprintf(stderr, descfmt, params);
    + 
    + 		if (error) {
    + 			terminal_fprintf(stderr, "\n%s\n", error);
    + 			error = NULL;
    + 		}
    + 
    + 		terminal_fprintf(stderr, "%s: ", prompt);
    + 	}
    + 	else {
    + 		terminal_fprintf(stderr, TERMINAL_FG_YELLOW TERMINAL_BOLD);
    + 		vfprintf(stderr, descfmt, params);
    + 		terminal_fprintf(stderr, TERMINAL_RESET "\n\n");
    + 
    + 		if (error)
    + 			terminal_fprintf(stderr, TERMINAL_FG_RED TERMINAL_BOLD "%s" TERMINAL_RESET "\n", error);
    + 
    + 		terminal_fprintf(stderr, TERMINAL_BOLD "%s" TERMINAL_RESET ": ", prompt);
    + 	}
    + #endif /* !ORIGINAL */
      
      	if (isatty(STDIN_FILENO)) {
      		if (tcgetattr(STDIN_FILENO, &old_termios) < 0)
    ***************
    *** 58,63 ****
    --- 81,93 ----
      			die_errno("tcsetattr");
      	}
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		if (error != NULL)
    + 			terminal_fprintf(stderr, "\n%s\n", error);
    + 	}
    + 	else
    + #endif /* !ORIGINAL */
      	terminal_fprintf(stderr, "%s" TERMINAL_CLEAR_DOWN, error ? TERMINAL_UP_CURSOR(4) : TERMINAL_UP_CURSOR(3));
      	return password;
      }
    *** lastpass-cli-master.orig/util.c	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/util.c	Sat Aug  8 17:52:07 2015
    ***************
    *** 39,44 ****
    --- 39,50 ----
      	vsnprintf(message, sizeof(message), err, params);
      	va_end(params);
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_fprintf(stderr, "Warning: %s\n", message);
    + 	}
    + 	else 
    + #endif /* ! ORIGINAL */
      	terminal_fprintf(stderr, TERMINAL_FG_YELLOW TERMINAL_BOLD "Warning" TERMINAL_RESET ": %s\n", message);
      }
      
    ***************
    *** 53,58 ****
    --- 59,70 ----
      	vsnprintf(message, sizeof(message), err, params);
      	va_end(params);
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_fprintf(stderr, "WARNING: %s: %s\n", error_message, message);
    + 	}
    + 	else 
    + #endif /* ! ORIGINAL */
      	terminal_fprintf(stderr, TERMINAL_FG_YELLOW TERMINAL_BOLD "WARNING" TERMINAL_RESET ": " TERMINAL_FG_YELLOW "%s" TERMINAL_RESET ": %s\n", error_message, message);
      }
      
    ***************
    *** 65,70 ****
    --- 77,88 ----
      	vsnprintf(message, sizeof(message), err, params);
      	va_end(params);
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_fprintf(stderr, "Error: %s\n", message);
    + 	}
    + 	else 
    + #endif /* ! ORIGINAL */
      	terminal_fprintf(stderr, TERMINAL_FG_RED TERMINAL_BOLD "Error" TERMINAL_RESET ": %s\n", message);
      	exit(1);
      }
    ***************
    *** 79,84 ****
    --- 97,108 ----
      	vsnprintf(message, sizeof(message), err, params);
      	va_end(params);
      
    + #ifndef ORIGINAL
    + 	if (disable_color()) {
    + 		terminal_fprintf(stderr, "Error: %s: %s\n", error_message, message);
    + 	}
    + 	else 
    + #endif /* ! ORIGINAL */
      	terminal_fprintf(stderr, TERMINAL_FG_RED TERMINAL_BOLD "Error" TERMINAL_RESET ": " TERMINAL_FG_RED "%s" TERMINAL_RESET ": %s\n", error_message, message);
      	exit(1);
      }
    ***************
    *** 97,110 ****
    --- 121,155 ----
      
      	for (;;) {
      		va_start(params, prompt);
    + #ifndef ORIGINAL
    + 		if (!disable_color())
    + #endif /* ! ORIGINAL */
      		terminal_fprintf(stderr, TERMINAL_FG_YELLOW);
      		vfprintf(stderr, prompt, params);
    + #ifndef ORIGINAL
    + 		if (!disable_color())
    + #endif /* ! ORIGINAL */
      		terminal_fprintf(stderr, TERMINAL_RESET);
      		va_end(params);
    + #ifdef ORIGNAL
      		if (default_yes)
      			terminal_fprintf(stderr, " [" TERMINAL_BOLD "Y" TERMINAL_RESET "/n] ");
      		else
      			terminal_fprintf(stderr, " [y/" TERMINAL_BOLD "N" TERMINAL_RESET "] ");
    + #else  /* !ORIGINAL */
    + 		if (disable_color()) {
    + 			if (default_yes)
    + 				terminal_fprintf(stderr, " [Y/n] ");
    + 			else
    + 				terminal_fprintf(stderr, " [y/N] ");
    + 		}
    + 		else {
    + 			if (default_yes)
    + 				terminal_fprintf(stderr, " [" TERMINAL_BOLD "Y" TERMINAL_RESET "/n] ");
    + 			else
    + 				terminal_fprintf(stderr, " [y/" TERMINAL_BOLD "N" TERMINAL_RESET "] ");
    + 		}
    + #endif /* !ORIGINAL */
      		if (getline(&response, &len, stdin) < 0)
      			die("aborted response.");
      		strlower(response);
    ***************
    *** 115,120 ****
    --- 160,171 ----
      		else if (!strcmp("\n", response))
      			return default_yes;
      		else {
    + #ifndef ORIGINAL
    + 			if (disable_color()) {
    + 				terminal_fprintf(stderr, "Error: Response not understood.\n");
    + 			}
    + 			else 
    + #endif /* ! ORIGINAL */
      			terminal_fprintf(stderr, TERMINAL_FG_RED TERMINAL_BOLD "Error" TERMINAL_RESET ": Response not understood.\n");
      			free(response);
      			response = NULL;
    ***************
    *** 458,460 ****
    --- 509,526 ----
      {
      	return val ? "1" : "0";
      }
    + 
    + #ifndef ORIGINAL
    + bool disable_color() {
    + 	static bool _init_         = true;
    + 	static bool _disablecolor_ = false;
    + 	if (_init_) {
    + 		_init_ = false;
    + 		char* disablecolor = getenv("LPASS_DISABLE_COLOR");
    + 		if (disablecolor && !strcmp(disablecolor, "1")) {
    + 			_disablecolor_ = true;
    + 		}
    + 	}
    + 	return (_disablecolor_);
    + }
    + #endif /* ! ORIGINAL */
    *** lastpass-cli-master.orig/util.h	Sat Aug  1 18:24:06 2015
    --- lastpass-cli-master/util.h	Sat Aug  8 17:40:16 2015
    ***************
    *** 106,109 ****
    --- 106,114 ----
      void get_random_bytes(unsigned char *buf, size_t len);
      
      const char *bool_str(bool val);
    + 
    + #ifndef ORIGINAL
    + bool disable_color();
    + #endif /* ! ORIGINAL */
    + 
      #endif

**Comment by bcopeland** [comment]
Thanks, but couldn't you just change your expect script to pass ```--color=never```?

**Comment by HippoMan** [comment]
Oh, thank you.

I missed "--color=never". That option is not described in the man pages, and when I just type "lpass", the "Usage" summary doesn't list that option, either. Therefore, I didn't know it exists.

It indeed works most of the lpass commands.

However, "--color=never" doesn't seem to work with the following commands:
  lpass ls       (dir listing and error messages)
  lpass sync  (error messages)

But anyway, at least "--color=never" works in most of my cases. I'll make a small patch to get it to work with "lpass ls" and "lpass sync", also. I'll submit it within a day or so.

**Comment by bcopeland** [comment]
Thanks - I will add it to the manpage.  If you find any commands you need where it doesn't work, please feel free to fix and send a PR.

**Comment by bcopeland** [comment]
Added to man page, closing this.
