### ISSUE TITLE
Patch submitted: Feature Request: Create new Secure Note with "lpass edit"?

### ISSUE THREAD

**Issue by HippoMan** [lastpass/lastpass-cli#105]
If I have already created a Secure Note called, say, *__aa\bb/cc__*, I can do the following, and I will be able to properly edit that Secure Note:

__lpass edit --sync=now --notes 'aa\bb/cc'__

However, if an item called, say, *__xx\yy/zz__* has never been created before, the following command creates it and lets me edit it, but it is not categorized as a Secure Note:

__lpass edit --sync=now --notes 'xx\yy/zz'__

What are the chances of adding some sort of option to "lpass edit" to cause a new note to be created as a Secure Note? ... perhaps a *__--secure=yes__* option, or something like that?

Or alternatively, could there be a new "lpass create" command which takes all the usual options (*i.e.*, *__--name|--username|--password|--url|--notes|--field=FIELD__*) but also, an additional option such as *__--secure-notes__*?

Or maybe is there some other way that a new Secure Note could be created via lpass?

Thank you very much.

**Comment by HippoMan** [comment]
I figured out what is wrong in this case, and I have a fix. When "--notes" is specified, the url field must be set to "http://sn". This currently isn't being done when a new Secure Note is being created. The following patch will set the url explicitly to "http://sn", only in the case where "--notes" is specified in "lpass edit" and only when a Secure Note doesn't already exist.

    --- cmd-edit.c.orig	2015-08-16 11:30:46.307648778 -0400
    +++ cmd-edit.c	2015-08-16 11:37:20.226456486 -0400
    @@ -199,11 +199,16 @@
     		editable->id = xstrdup("0");
     		account_set_password(editable, xstrdup(""), key);
     		account_set_fullname(editable, xstrdup(name), key);
     		account_set_username(editable, xstrdup(""), key);
     		account_set_note(editable, xstrdup(""), key);
    -		editable->url = xstrdup("");
    +		if (choice == NOTES) {
    +			editable->url = xstrdup("http://sn");
    +		}
    +		else {
    +			editable->url = xstrdup("");
    +		}
     		list_add(&editable->list, &blob->account_head);
     	}
     	notes_expansion = notes_expand(editable);
     	if (notes_expansion) {
     		notes_collapsed = editable;

**Comment by bcopeland** [comment]
Thanks for the patch!

I'm as yet undecided whether I want to merge this as-is -- although it would be odd to start editing a regular site by specifying a note, someone may do so, and regular sites can have also notes.  On the other hand, http://sn is not at all discoverable.  Curious what others may think.

In any case I'll need a Signed-off-by to apply any patch.

**Comment by HippoMan** [comment]
Well, without this patch, there is no way for anyone to create a new Secure Note using lastpass-cli. The Secure Note would have to be created some other way, first. All that's currently possibly via "lpass" is to edit, remove, or rename an existing Secure Note.

Also, I don't what you mean by a "Signed-off-by" ... ???

**Comment by bcopeland** [comment]
Yes, I understand, I think your patch may make the most sense but I want to think about it a bit.

Please see: https://github.com/lastpass/lastpass-cli/blob/master/CONTRIBUTING

**Comment by HippoMan** [comment]
Concerning the patch, perhaps a new flag could be added to "lpass edit" called "--site" or something like that. With "--site", a person could start editing a regular site by specifying a note, which is the current behavior of "--notes".  Then, "--notes" could work the way it does with my patch, which is consistent with the usage of "--notes".

Regarding "Signed-off-by", are you suggesting I do a pull and then submit the patch to cmd-edit.c, with my signoff as specified in the "CONTRIBUTING" doc? I'd be glad to do that.

**Comment by bcopeland** [comment]
Yes -  I think the original approach is simplest so I just took that (with some minor edits).  Thanks again!

**Comment by HippoMan** [comment]
Sure ...

Thank you for everything!

- Lloyd

-- 
 Lloyd Zusman
 hippoman@potamuses.net

    .---------, 0__0
   /           (  oo'---,
  /                    oo\
 ,\                      |
 | \                ,=__/
    \              /
    /  /------|  /|
    |__|-'    |__|'
