### ISSUE TITLE
Path separator consistency

### ISSUE THREAD

**Issue by przemyslaw-pokrywka-smt** [lastpass/lastpass-cli#107]
Platform: Ubuntu. I've noticed, that when you have nested shared folders, you must use backslash between path components with one exception: the last item needs to be separated by forward slash.

```
lpass show --notes "Shared-TopFolder\\SubFolder/entry"
```
If you try to use forward slash everywhere you get an error:
```
Error: Could not find specified account 'Shared-TopFolder/SubFolder/entry'
```
In my opinion you should be allowed to use forward slashes everywhere for consistent user experience and for Rule of Least Surprise's sake.

Thanks for great product by the way!

**Comment by przemyslaw-pokrywka-smt** [comment]
Nevermind, it turned out, that the shared folder was created with backslash in its name. Problem solved.

**Comment by bcopeland** [comment]
Thansk for the update -- there was a bug somewhere in there in lpass where path wasn't terminated properly and so there could be extra chars on the end, maybe you got hit by that.  In any case glad you found it.
