### ISSUE TITLE
[Feature Request] UniqueName case sensitive

### ISSUE THREAD

**Issue by HazCod** [lastpass/lastpass-cli#111]
Currently, the lpass show accepts the uniquename, but only case sensitive.
This should be case insensitive.

**Comment by bcopeland** [comment]
It makes sense to allocate a new command-line switch for this - feel free to send me a pull request if you have time!

I don't want to make it the default though (nor substring matching) -- at least until we have a way to configure an alternate default: some peoples' scripts may rely on matching being done the way it is today.

In the meantime you can accomplish this with an unwieldy regex:
```
lpass show -G [Ff][Oo][Oo]
```

**Comment by bcopeland** [comment]
I think the alias features in the latest HEAD should now mostly satisfy this request.  Substring and regex matching are case insensitive.  Using it by default can be done like this (for regex):
{{{
echo "show -G" > ~/.lpass/alias.show 
}}}
