### ISSUE TITLE
[Feature Request] Do not require whole UNIQUENAME

### ISSUE THREAD

**Issue by HazCod** [lastpass/lastpass-cli#112]
Would be a nice addition if we would not need to specify the whole UNIQUENAME, just enough so it's unique.

Btw) Great work!

**Comment by bcopeland** [comment]
Just pass in `-F` to lpass show.

**Comment by HazCod** [comment]
May I ask why -F isn't enabled by default?
Is  there a way to set this by default?

**Comment by bcopeland** [comment]
Because originally we did full matching, and changing it now would break existing scripts.  Today there isn't a way to change the default, but it would be nice to have such an option.

You can, of course, use a shell alias to avoid having to type -F.

**Comment by HazCod** [comment]
`alias lps='lpass show -F -c --password'`

This did the job, thank you.

**Comment by bcopeland** [comment]
Because it's a frequent request -- I went ahead and took a stab at building in aliases to lpass -- please try topic-alias branch (1986e342db35021493d49df29b5e75fcab60accf) and let me know if it works for you (see commit log for details).

**Comment by HazCod** [comment]
@bcopeland This works wonders! Great work!
Do note tab completion does not work on new alias commands nor UNIQUENAME.
(Makes sense for the commands, since it is hard-coded.)
