### ISSUE TITLE
Provide changelog

### ISSUE THREAD

**Issue by whysthatso** [lastpass/lastpass-cli#117]
Not sure if i just haven't found it, but it would be nice if it could be available in the git repo.

**Comment by bcopeland** [comment]
Ok, there are of course the git commit logs though I understand there is a difference.

**Comment by bcopeland** [comment]
Also I should point to this:
https://github.com/lastpass/lastpass-cli/releases

**Comment by whysthatso** [comment]
ah, yes. That's a lot already, thank you. Maybe a straight forward link in the readme would help make it even more obvious :)

**Comment by bcopeland** [comment]
Now in the tree.
