### ISSUE TITLE
Feature request: support multiple IDs

### ISSUE THREAD

**Issue by mindfulmonk** [lastpass/lastpass-cli#118]
Hello,

I have written a wrapper that searches for multiple entries and then does an lpass show on each id.
This is quite slow even with --sync=no. From what I see the issue is that the blob is opened and closed on each call to lpass show. 

Can you please implement lpass show to take multiple IDs?
Is there a temporary workaround?

**Comment by bcopeland** [comment]
How many entries do you have in your vault, and/or how big is ~/.lpass/blob?  Even though there's decryption involved, I would think you'd hit the cache on subsequent tries and it would be faster.  While it might make sense to add this (and certainly it wouldn't be hard), I'd like to understand the performance issue a bit better first.

**Comment by mindfulmonk** [comment]
4k entries and the blob is 1.6M. It is quite responsive up to 10 results, but from there its getting much slower.

For example:

7 passwords - 0.92s
30 passwords - 3.74s
100 passwords - 11.76s

**Comment by dnichk** [comment]
I can second this. Or if even the cli client would be aware when you have the accounts linked through the web interface.

**Comment by bcopeland** [comment]
Thanks to @AngusG this is now implemented.  Also you can now use ```lpass show --expand-multi [...]``` if you have a search string that would normally show the 'Multiple Matches Found' id list and you would rather see the site contents.
