### ISSUE TITLE
lpass ls doesn't work with shared folders

### ISSUE THREAD

**Issue by mindfulmonk** [lastpass/lastpass-cli#119]
Hi,

The following functionality:
```
lpass ls "folder-name"
```

Only works for local folders, if a folder is shared then the following won't work:

```
lpass ls "Shared-folder-name"
```

**Comment by bcopeland** [comment]
Thanks for the report, I can confirm and will patch this shortly.

**Comment by bcopeland** [comment]
Latest HEAD should work now.
