### ISSUE TITLE
Allow configuring the clipboard program to use.

### ISSUE THREAD

**Issue by tomprince** [lastpass/lastpass-cli#121]
I'd like to use `xclip -l ` instead of the default configuration.

**Comment by bcopeland** [comment]
I could take a patch for this, but perhaps it makes sense to pass -l in any case?

Also if you want to clear the clipboard, I think it would be better to just fork a process inside clipboard.c that clears it after a set amount of time (#59).

**Comment by tomprince** [comment]
While changing the default might make sense to change the defaults, different people will want different behavior. For example, I want the 'PRIMARY' selection while others, based on the current setting, want the `CLIPBOARD` selection.
