### ISSUE TITLE
"Please upgrade your client." on login page

### ISSUE THREAD

**Issue by max-allan-surevine** [lastpass/lastpass-cli#124]
When I try to login I get a message "Please upgrade your client.", after typing a password, regardless of which password I use. (the correct one or a bad one)
If I use a random email address I correctly get a "Unknown email address."
I have tried downloading/building both master and v0.6.0.
I have checked the admin log and it does not show any of the attempts to login with a valid email address, whether I used the correct password or not.

**Comment by bcopeland** [comment]
Hmm... I'm not reproducing this.  What platform are you on?  Can you send me your account name in a private email to copeland@lastpass.com?

One thing you might try is setting up mitmproxy to see the details of the login messages, that might give a clue.  You can rebuild lpass to use the proxy like so:
```
$ touch *.c && CFLAGS=-DDO_NOT_ENABLE_ME_MITM_PROXY_FOR_DEBUGGING_ONLY
```
Then just run mitmproxy and hit enter on the login request, tab to see the responses.

**Comment by max-allan-surevine** [comment]
Hi, I'm using an Amazon EC2 instance. It's their Linux flavour, quite an old base build but recently updated. It was running the LastPass client fine about 3 months ago when I last used it. I'll send my account over in a mail. Thanks very much!

**Comment by max-allan-surevine** [comment]
So, the place it was going wrong is our live VPN server, didn't really want to mess with it, so I tried again on a "fresh" instance.
Some messing about to get mitmproxy to work making symbolic links for libxml and other odd bits and bobs... Anyway, eventually after importing the SSL certificates, Request and response headers below.  (hash and cookie value are not real!)

In summary, it looks like the server is really making that response. 

```
2015-10-26 15:44:59 POST https://lastpass.com/login.php
Detail
User-Agent:      LastPass-CLI/0.6.0                                                                                                                                    
Host:            lastpass.com                                                                                                                                          
Accept:          */*                                                                                                                                                   
Content-Length:  180                                                                                                                                                   
Content-Type:    application/x-www-form-urlencoded                                                                                                                     
URLEncoded form                                                                                                                                                  [m:Auto]
xml:                   2                                                                                                                                               
username:              max@company.com                                                                                                                          
hash:                  ffedcba98765432100fffffffffffffffff98coffee123875feghi61a3000007                                                                                
iterations:            5000                                                                                                                                            
includeprivatekeyenc:  1                                                                                                                                               
method:                cli                                                                                                                                             
outofbandsupported:    1      


RESPONSE
Detail
Date:                       Mon, 26 Oct 2015 15:45:12 GMT                                                                                                              
Content-Type:               text/xml; charset=UTF-8                                                                                                                    
Transfer-Encoding:          chunked                                                                                                                                    
Connection:                 keep-alive                                                                                                                                 
Vary:                       Accept-Encoding                                                                                                                            
X-Frame-Options:            SAMEORIGIN                                                                                                                                 
Content-Security-Policy:    default-src 'self' ; img-src 'self' https://lastpass.com data: https://ssl.google-analytics.com https://www.google-analytics.com           
                            https://img.youtube.com https://googleads.g.doubleclick.net https://www.google.com  ; object-src 'self' http://*.googlevideo.com;          
                            connect-src 'self' https://lastpass.com wss://*.lastpass.com  https://pollserver.lastpass.com https://loglogin.lastpass.com ; style-src    
                            'self' 'unsafe-inline' 'unsafe-eval'  https://lastpass.com ; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://lastpass.com          
                            https://www.youtube.com https://*.ytimg.com ; font-src 'self' 'unsafe-inline' 'unsafe-eval'  https://lastpass.com ; frame-src 'self'       
                            https://ssl.gstatic.com https://www.google.com https://www.youtube.com                                                                     
Cache-Control:              no-cache, private, no-store, max-age=0, s-maxage=0, must-revalidate, proxy-revalidate                                                      
Cache-Control:              no-store, no-cache, must-revalidate, post-check=0, pre-check=0                                                                             
X-Content-Security-Policy:  allow 'self'  'self' https://lastpass.com wss://*.lastpass.com  https://pollserver.lastpass.com https://loglogin.lastpass.com ; img-src    
                            'self' https://lastpass.com data: https://ssl.google-analytics.com https://www.google-analytics.com https://img.youtube.com                
                            https://googleads.g.doubleclick.net https://www.google.com  ; object-src 'self' http://*.googlevideo.com; frame-src 'self'                 
                            https://ssl.gstatic.com https://www.google.com https://www.youtube.com ; options inline-script eval-script                                 
Set-Cookie:                 PHPSESSID=QQQi8bZ6xxx9SUeFIHHHH123H; expires=Sun, 08-Nov-2015 15:45:12 GMT; Max-Age=1123200; path=/; secure; httponly                    
P3P:                        CP="NON DSP COR CUR OUR LEG PHY COM"                                                                                                       
Expires:                    Thu, 19 Nov 1981 08:52:00 GMT                                                                                                              
Pragma:                     no-cache                                                                                                                                   
Server:                     LastPass                                                                                                                                   
Strict-Transport-Security:  max-age=86400000                                                                                                                           
X-XSS-Protection:           1; mode=block                                                                                                                              
X-Content-Type-Options:     nosniff                                                                                                                                    
XML-like data                                                                                                                                                    [m:Auto]
<?xml version='1.0' encoding='UTF-8'?>
<response>
  <error server="lastpass.eu" message="Please upgrade your client."/>
</response>
```

**Comment by bcopeland** [comment]
Ok, yes, lastpass-cli doesn't support lastpass.eu at the moment, but it should not be hard to add.

**Comment by bcopeland** [comment]
It will take me a bit of time to figure out how to do this properly in the current code - at the least we'll need to pass more state into http_post_lastpass functions.

As a workaround, for now you could use the attached patch.  It simply changes lastpass.com to lastpass.eu, and then removes the certificate pinning since lastpass.eu is signed with a different CA (lpass should still validate your certs based on the platform certificate store, though).

[0001-minimal-modifications-to-support-lastpass.eu.patch.txt](https://github.com/lastpass/lastpass-cli/files/21093/0001-minimal-modifications-to-support-lastpass.eu.patch.txt)

**Comment by max-allan-surevine** [comment]
I also commented out the pin_certificate function to avoid the warnings :
```
/* static CURLcode pin_certificate(CURL *curl, void *sslctx, void *parm)
 *{
 *      UNUSED(curl);
 *      UNUSED(parm);
 *      X509_STORE *store;
........
 *      BIO_free(bio);
 *      return ret;
 *}
 */
```
But the patch does definitely fix the problem for me.
Thanks.

**Comment by Yggdrasil** [comment]
Thanks, I can confirm that the patch works for my lastpass.eu account as well. I applied it via Homebrew on OS X on an install of lastpass-cli v0.8.0.

Would be great to have this done properly though, please.

**Comment by johnybradshaw** [comment]
Any news when this will be integrated?

**Comment by bcopeland** [comment]
Soon.

**Comment by bcopeland** [comment]
All, pease try out the [topic-lastpass-eu](/lastpass/lastpass-cli/tree/topic-lastpass-eu) branch, and see if it works for you.  It's quite a bit more complex than the patch linked upthread due to having to also support lastpass.com, and some cert differences.

If no big problems I'll merge it by the end of the week.

**Comment by bcopeland** [comment]
I'll take no replies as success across the board :)  I merged this now.

**Comment by Yggdrasil** [comment]
Sorry, spent a few unsuccessful hours this week trying to build the branch on OS X, but apparently I still have lots to learn. :cry: In other words, I don't know if it works. Thanks a lot for your work though!

**Comment by johnybradshaw** [comment]
@bcopeland I installed via brew, is there a simple way to use this branch?

**Comment by bcopeland** [comment]
@johnybradshaw try ```brew install --HEAD lastpass-cli```

**Comment by max-allan-surevine** [comment]
Sorry @bcopeland, I missed your update. I have installed the EU branch and can now login but cannot list any sites.

`[root@ip-10-0-1-1 openvpn]# lpass login max@domain.com
Success: Logged in as max@domain.com.
[root@ip-10-0-1-1 openvpn]# lpass show "Max"
Error: HTTP response code said error.
[root@ip-10-0-1-1 openvpn]# lpass ls
Error: HTTP response code said error.
[root@ip-10-0-1-1 openvpn]# lpass logout
Are you sure you would like to log out? [Y/n] y
Log out: complete.
`

**Comment by bcopeland** [comment]
On Mon, Feb 01, 2016 at 07:00:00AM -0800, max-allan-surevine wrote:
> Sorry @bcopeland, I missed your update. I have installed the EU branch and can now login but cannot list any sites.
> 
> `[root@ip-10-0-1-1 openvpn]# lpass login max@domain.com
> Success: Logged in as max@domain.com.
> [root@ip-10-0-1-1 openvpn]# lpass show "Max"
> Error: HTTP response code said error.
> [root@ip-10-0-1-1 openvpn]# lpass ls
> Error: HTTP response code said error.
> [root@ip-10-0-1-1 openvpn]# lpass logout
> Are you sure you would like to log out? [Y/n] y
> Log out: complete.

Hmm, I just tested master with an .eu account and it worked for me.

Check ~/.lpass/ -- there should be a "session_server" file which says
"lastpass.eu" after you login, and this should be used for subsequent
connects for that session.

If not too much trouble, you could rebuild in debug mode and run
mitmproxy to see what response the server is giving you:

$ CFLAGS=-DDO_NOT_ENABLE_ME_MITM_PROXY_FOR_DEBUGGING_ONLY make clean all

(in another window):
$ mitmproxy

(in original window):
$ lpass show blahblah

Then go back to mitmproxy and look at the traffic.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by Yggdrasil** [comment]
I can confirm the homebrew HEAD build works well for my .eu account.

`brew install lastpass-cli --with-doc --with-pinentry --HEAD`
