### ISSUE TITLE
Clarify Licensing

### ISSUE THREAD

**Issue by tomprince** [lastpass/lastpass-cli#127]
There are a few ways the licensing is unclear.
- None of the source files have a copyright or license statement. (This isn't strictly necessary, but would make things clearer.)
- There is a file that describes an exception for linking with OpenSSL; but that file says only certain files fall under that exception and suggests that those files point at this one. Since none of the files have any license statement, the reasonable conclusion is that none of the files have that exception. (I assume this wasn't the intent).
- `CONTRIBUTING` says the license is GPLv2 (without exception), so that all contributions have not been made with the SSL exception.

**Comment by bcopeland** [comment]
Point taken; the intent of course was to allow linking with OpenSSL (I will be so happy when they adopt a standard license.).  So I suppose in addition to clarifying, we must ask contributors to confirm their acceptance.

**Comment by bcopeland** [comment]
I pushed a change for all the files that have only been modified by LastPass; will add the others pending approval by contributors.

**Comment by tomprince** [comment]
The licensing block should probably explicitly refer to `LICENSE.OpenSSL`.

**Comment by bcopeland** [comment]
Good idea, will tack on a:
```
 * See LICENSE.OpenSSL for details.
```
or so.

**Comment by bcopeland** [comment]
I think this is addressed now.
