### ISSUE TITLE
Respect XDG Base Directory Specification

### ISSUE THREAD

**Issue by bcremer** [lastpass/lastpass-cli#13]
First, realy nice project, :+1: 

It would be really nice if lpass would not clutter my home directory.

I suggest respecting the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

For example:
Most files should be located at `$XDG_RUNTIME_DIR/lpass`instead of `$HOME/.lpass`.

**Comment by bcopeland** [comment]
I believe I'll do this in a future release.  For the simple case of throwing everything into XDG_RUNTIME_DIR, you could add this two-liner.

I suppose what really needs to happen though is things like aliases and config settings that persist need to go in XDG_CONFIG_HOME, but right now config_XXX() functions don't differentiate at all the type of data that they are saving.

[0001-config-put-everything-in-XDG_RUNTIME_DIR.patch.txt](https://github.com/lastpass/lastpass-cli/files/101132/0001-config-put-everything-in-XDG_RUNTIME_DIR.patch.txt)

**Comment by bcopeland** [comment]
Ok, I implemented this but haven't yet merged it pending some testing.  Please let me know what you think, commit here: 302b673ea19d7972b6d9643b0dedeb3ddf997494
