### ISSUE TITLE
Allows shared passwords to be viewed

### ISSUE THREAD

**Issue by tonycapone** [lastpass/lastpass-cli#130]
I noticed after having site credentials shared with me using the sharing feature, I was able to view the password to the shared site with the the lpass show command. Should that be possible?

 The [lastpass docs](https://helpdesk.lastpass.com/sharing/) claim that it would only be possible to get a shared password using "advanced techniques", but the CLI makes it trivial. 

I would think there should be some validation around allowing people to display shared passwords in the CLI.

**Comment by bcopeland** [comment]
Well, this is unfortunate, but I'm not really sure what we should do here.  The client has the data.  We could limit it server-side, but then you wouldn't be able to actually use those sites.  We could disable show unless ```-c``` was passed, but then "advanced techniques" boils down to pasting somewhere (or at worst, recompiling the app).

**Comment by tonycapone** [comment]
In that case, it sounds like the issue is more with the documentation. "Advanced techniques" is relative to the expertise of the user, but it seems pretty trivial to me. The wording that suggests you generate a random password before sharing a site should be a little stronger in my opinoin.

Anyway, I will close this issue since there seems to be nothing you can do as far as this repo is concerned. Thanks!

**Comment by bcopeland** [comment]
We did ultimately decide to implement stripping of such accounts on the server side after several other people reported this issue with varying levels of concern.  Now, unless a share is marked 'give' then it will not be returned from the server.  Unfortunately, of course, it also means such accounts are unavailable to the CLI.

**Comment by tonycapone** [comment]
Thanks for the update!
