### ISSUE TITLE
LastPass Secure Notes (SSH Key type) does not store private key in the right format

### ISSUE THREAD

**Issue by rehmanz** [lastpass/lastpass-cli#135]
LastPass Secure Notes (SSH Key type) does not place new lines when I paste my private key via the web.

Problem
========
1) Copied my private key from vi editor in Mac and pasted it to the Secure Notes SSH Key's Private Key field as "ssh-key-creds"
2) Use the 'lpass show --field "Private Key" ssh-key-creds" to retrive. The key does not show new line characters and hence needs to be manually fixed

- What am I doing wrong?
- Is there a way to store my ssh keys via lpass cli?

**Comment by bcopeland** [comment]
You were not doing anything wrong, this was a known shortcoming.  However, I just made a fix for it in the repo, so please try it now.

**Comment by rehmanz** [comment]
Thanks.
