### ISSUE TITLE
Unable to fetch blob. Either your session is invalid and you need to login with `lpass login`, you need to synchronize, your blob is empty, or there is something wrong with your internet connection.

### ISSUE THREAD

**Issue by juabara** [lastpass/lastpass-cli#140]
OS: CentOS release 6.7 (Final)
LasPass CLI v0.7.1

Hi guys, I'm facing exactly the same problem reported on issue #47 

lpass login, sync and logout works well, but lpass ls doesn't work at all, it always show the message:

Error: Unable to fetch blob. Either your session is invalid and you need to login with `lpass login`, you need to synchronize, your blob is empty, or there is something wrong with your internet connection.

I've already tried to update the system and lpass-cli to the last versions without success.

**Comment by bcopeland** [comment]
Can you tell me your lastpass username?

**Comment by mickeyh** [comment]
I am having the same issue but only when using a particular LastPass account (my other account works fine with LastPass CLI).

This has occurred for me in multiple versions. Most recently I tried LastPass CLI v0.8.0 on Ubuntu 14.04.3.

I tried poking around a bit in `gdb` and the issue appeared to be that an `ACCT` chunk was never found in the LastPass CLI "blob", which caused an error in `blob.c::blob_parse`.

**Comment by bcopeland** [comment]
On Wed, Jan 06, 2016 at 05:00:36PM -0800, mickeyh wrote:
> I tried poking around a bit in `gdb` and the issue appeared to be that an `ACCT` chunk was never found in the LastPass CLI "blob", which caused an error in `blob.c::blob_parse`.

That sounds rather like the "your blob is empty" part of the error message:
is it the case?

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by juabara** [comment]
Hi, LastPass username is lastpass.robooperacoes@mdsinsure.com, I´ve checked lastpass files at ~/.lpass and none of them is zero sized.

**Comment by mickeyh** [comment]
@bcopeland No the blob appears to have many other sections in it (the first couple are LPAV, PREM, ENTU).

It seems more like the blob is deterministically corrupted/malformed (even across machines, I have also had the same issue with this account on two other machines running OSX 10.10.5 LastPass CLI v0.6.0, and Ubuntu 15.10 LastPass CLI v0.7.0 respectively).

**Comment by mickeyh** [comment]
On the same Ubuntu 14.04.3 box as described above the `~/.lpass` directory looks like:
```
~/.lpass# ls -al
total 60
drwx------ 2 root root  4096 Jan  7 03:23 .
drwx------ 3 root root  4096 Jan  7 03:24 ..
srwx------ 1 root root     0 Jan  7 03:23 agent.sock
-rw------- 1 root root 21696 Jan  7 03:23 blob
-rw------- 1 root root     4 Jan  7 03:22 iterations
-rw------- 1 root root  1280 Jan  7 03:22 session_privatekey
-rw------- 1 root root    80 Jan  7 03:22 session_sessionid
-rw------- 1 root root   128 Jan  7 03:22 session_token
-rw------- 1 root root    64 Jan  7 03:22 session_uid
-rw------- 1 root root    22 Jan  7 03:22 username
-rw------- 1 root root    96 Jan  7 03:22 verify
```

I can `lpass login <my_account>` fine (it creates above directory). I can `lpass sync` successfully (or at least the sync has exit code 0). However both `lpass ls` and `lpass ls --sync=no` give the error

    Error: Unable to fetch blob. Either your session is invalid and you need to login with `lpass login`, you need to synchronize, your blob is empty, or there is something wrong with your internet connection.

**Comment by mickeyh** [comment]
Would it be helpful for me to email you my account name?

**Comment by juabara** [comment]
I've tried all --sync options in lpass ls and still get the same error.

**Comment by juabara** [comment]
Just to give you guys an update, I've upgraded to v0.8.0 and still get the same error. I've deleted .lpass folder, logged in and sync'ed again, and here is the new lpass content:

```bash
[some_username@server_name .lpass]$ ls -lash
total 60K
4.0K drwx------ 2 some_username some_group 4.0K Jan  7 22:40 .
4.0K drwx------ 9 some_username some_group 4.0K Jan  7 22:38 ..
   0 srwx------ 1 some_username some_group    0 Jan  7 22:38 agent.sock
 20K -rw------- 1 some_username some_group  19K Jan  7 22:40 blob
4.0K -rw------- 1 some_username some_group    4 Jan  7 22:38 iterations
4.0K -rw------- 1 some_username some_group 1.3K Jan  7 22:38 session_privatekey
4.0K -rw------- 1 some_username some_group   80 Jan  7 22:38 session_sessionid
4.0K -rw------- 1 some_username some_group  128 Jan  7 22:38 session_token
4.0K -rw------- 1 some_username some_group   64 Jan  7 22:38 session_uid
4.0K -rw------- 1 some_username some_group   32 Jan  7 22:38 trusted_id
4.0K -rw------- 1 some_username some_group   36 Jan  7 22:38 username
4.0K -rw------- 1 some_username some_group   96 Jan  7 22:38 verify
```

**Comment by mickeyh** [comment]
For posterity: This was resolved this offline (thanks @bcopeland for the help!).

The problem was that shared credentials marked with "Hide Passwords" are not supplied to LastPass CLI at all. Allowing the account in question to view the shared credentials solved my problem.

I think that https://github.com/lastpass/lastpass-cli/issues/130 gives a bit more context.

**Comment by bcopeland** [comment]
@juabara I checked out your account and it is the same issue as mickeyh's: the server is stripping out any accounts with 'hide passwords' so your blob, as far as lpcli is concerned, is empty.

In the next release I'll improve things a little bit here: I believe we should just allow an empty account (and perhaps show empty shared folders as suggested in #148) -- and detect errors some other way.

**Comment by juabara** [comment]
Hi guys! Thank you so much! I've changed the 'hide password' setting and eveything is working now! Cheers!
