### ISSUE TITLE
Improper escaping of site names

### ISSUE THREAD

**Issue by castrapel** [lastpass/lastpass-cli#141]
The output for `lpass ls` doesn’t properly escape some characters. Sites with forward slashes are not being parsed and printed out correctly. 

For example:
lpass ls shows:
"rosetta r
    o user" 

("rosetta r" above is printed with the blue directory font)

This should be printed as:
"rosetta r\o user"

**Comment by castrapel** [comment]
Looks like this one has already been reported on issue # 10

**Comment by bcopeland** [comment]
Thanks, closing as duplicate.  I'll take a look at #10 today.
