### ISSUE TITLE
lpass share limit --whitelist sometimes segfaults

### ISSUE THREAD

**Issue by castrapel** [lastpass/lastpass-cli#142]
I'm seeing segmentation faults about 50% of the time with the new lpass share limit --whitelist feature. 

The first time it usually fails with seg fault, but running the exact command a second time works fine.

./lpass share limit --whitelist "<shared-folder-name>" <user_email> <credential ID>
Segmentation fault (core dumped)
./lpass share limit --whitelist "<shared-folder-name>" <user_email> <credential ID>
<Works fine>

**Comment by bcopeland** [comment]
Er, oops:
```
	 * Although we look up the share based on the supplied sharename,
	 * it may not exist, in the case of commands such as 'add'.  Subcmds
	 * should check args.share before using it.
```
... and yet almost no command does.

**Comment by bcopeland** [comment]
I rebased the topic-share-limit branch with fixes (just a few minutes ago) for some obvious segfaults here.  I'm not sure you were hitting those, as it worked for you later -- please retest with the latest version of this branch.

**Comment by bcopeland** [comment]
I've merged this branch now to main trunk; please reopen if this continues to have issues.
