### ISSUE TITLE
lpass share useradd --read_only doesn't work

### ISSUE THREAD

**Issue by castrapel** [lastpass/lastpass-cli#143]
./lpass share useradd --read_only=true --hidden=false --admin=true "Shared-folder" user@x.com

Shows:

share: unrecognized option '--read_only=true'
Usage: ./lpass share [--color=auto|never|always] subcommand sharename...

**Comment by bcopeland** [comment]
It should be ``--read-only=true```, I made this mistake in several parts.  I've pushed a couple of patches which fixes the documentation, and also displays better usage:
```
$ ./lpass share useradd --read_only=true --hidden=false --admin=true "Shared-folder" user@x.com
share: unrecognized option '--read_only=true'
Usage: ./lpass share useradd [--read-only=[true|false] --hidden=[true|false] --admin=[true|false] SHARE USERNAME
```
