### ISSUE TITLE
lpass sync hangs

### ISSUE THREAD

**Issue by cbeilman** [lastpass/lastpass-cli#146]
When running lpass sync (0.8.0), command hangs.

If I logout and back in, the sync works, but after a period of time starts hanging again.

This only occurs on my CentOS 6.5 system and not with Cygwin.

**Comment by bcopeland** [comment]
It's probably not hanging but actually backing off - see 285833a5091e6f5b88e1bbad3e5a6dfa92ce6f30 and 0b938d996cc6ee64eaec54c3b9e7f8226e78ee4d -- maybe it makes sense to tweak some timeouts there.  What does your ~/.lpass/upload-queue look like (as in # of files) when hung?

**Comment by cbeilman** [comment]
When the command is hung, there are 60 files in ~/.lpass/upload-queue/

**Comment by bcopeland** [comment]
Does this number stay the same for over 10 minutes if you just let ```lpass sync``` continue running?

**Comment by cbeilman** [comment]
Yes, the number stays the same.

**Comment by bcopeland** [comment]
OK, I guess I'll need to make a debug logging patch then...

**Comment by cbeilman** [comment]
Okay, let me know what you want me to do.

Thanks,
Clint

**Comment by bcopeland** [comment]
Please try the attached patch and then /tmp/lpass-upload.log should shed some light.

[0001-debug-upload-queue-patch.txt](https://github.com/lastpass/lastpass-cli/files/87671/0001-debug-upload-queue-patch.txt)

**Comment by cbeilman** [comment]
I left the sync running for about an hour.
[lpass-upload.txt](https://github.com/lastpass/lastpass-cli/files/87817/lpass-upload.txt)

**Comment by bcopeland** [comment]
Thanks, this shows an unexpected condition that leaves a stuck job item.

**Comment by bcopeland** [comment]
(There was a bug in the previous patch, here's an updated version -- but no need to run it right now.)

[0001-debug-upload-queue-patch.txt](https://github.com/lastpass/lastpass-cli/files/87876/0001-debug-upload-queue-patch.txt)

**Comment by bcopeland** [comment]
Does this patch (on top of your debug patch) solve it for you?

[0001-always-drop-failed-requests.patch.txt](https://github.com/lastpass/lastpass-cli/files/87878/0001-always-drop-failed-requests.patch.txt)

**Comment by cbeilman** [comment]
Yes, it corrects the issue.

**Comment by bcopeland** [comment]
Please try the master branch, where I addressed it slightly differently, and reopen if you still have problems.

**Comment by tech-vsilva** [comment]
Hi guys, I'm facing the same issue. The `sync` operation is hanging a lot.
