### ISSUE TITLE
lpass generate does not add 'password' field to generated secure note

### ISSUE THREAD

**Issue by kbroughton** [lastpass/lastpass-cli#151]
I'm trying to generate a password and push it to LP using the commandline.

lpass --version
LastPass CLI v0.5.1

lpass generate --no-symbols --sync=now --url=10.x.y.z --username=testuser "Shared-devops/user@10.x.y.z" 20
E4********************b5

This creates an entry in my lastpass called Shared-devops/user@10.x.y.z
with username user but there is no entry in the password field.

Looking at the code for cmd-generate.c, it appears that the password should be getting set.  But no.

I tried to work around this using edit after generate, but edit requires a vim interaction and i haven't figured out how to pipe into it yet.

**Comment by bcopeland** [comment]
Look at 392372448e9b94f4e370f1e64a346ad4754f6847 for an example of piping to edit, but you need to be on 0.8.0 for that.

I cannot recreate this on v0.8.0.

**Comment by kbroughton** [comment]
Thanks.  Confirmed this works in v0.8.0.

brew upgrade lastpass-cli
did the trick for me.
