### ISSUE TITLE
HTTP response code said error (probably .eu/.com confusion again)

### ISSUE THREAD

**Issue by max-allan-surevine** [lastpass/lastpass-cli#154]
When using the CLI with a .eu account the application still seems to be querying the lastpass.com servers for actual content (rather than just login, which goes to .eu).
```
    [root@ip-10-66-2-107 lastpass-cli-master]# lpass login max@domain.com
    Success: Logged in as max@domain.com.
    [root@ip-10-66-2-107 lastpass-cli-master]# lpass ls
```
Error: HTTP response code said error.

Result from mitmproxy : 
```
    >> POST https://lastpass.com/iterations.php
            ← 200 text/html 4B 135ms
       POST https://lastpass.com/login.php
            ← 200 text/xml 127B 635ms
       POST https://lastpass.eu/login.php
            ← 200 text/xml 121B 2.79s
       POST https://lastpass.com/login.php
            ← 200 text/xml 127B 24.2s
       POST https://lastpass.eu/login.php
            ← 200 text/xml 302B 2.53s
       POST https://lastpass.eu/login.php
            ← 200 text/xml 6.46kB 3.78s
       POST https://lastpass.com/getaccts.php
            ← 403 text/html 478B 1.12s
```
(I did get my password wrong during the login so one step more than required there!) 
But then the last hit in the list is on the .com domain when I do the "lpass ls".
Consistently : 
```
      POST https://lastpass.com/getaccts.php
            ← 403 text/html 478B 1.12s
    >> POST https://lastpass.com/getaccts.php
            ← 403 text/html 478B 1.12s
       POST https://lastpass.com/getaccts.php
            ← 403 text/html 478B 1.14s
```

I am using  "master" :
LastPass CLI v0.8.0

**Comment by bcopeland** [comment]
On Thu, Feb 04, 2016 at 08:02:46AM -0800, max-allan-surevine wrote:
> When using the CLI with a .eu account the application still seems to be querying the lastpass.com servers for actual content (rather than just login, which goes to .eu).
>     [root@ip-10-66-2-107 lastpass-cli-master]# lpass login max@domain.com
>     Success: Logged in as max@domain.com.
>     [root@ip-10-66-2-107 lastpass-cli-master]# lpass ls
> Error: HTTP response code said error.

It sounds like it's not persisting the login server choice.  Can you check
whether the session_server file is getting created in ~/.lpass and it
looks sane?

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by max-allan-surevine** [comment]
Nope, no session_server file : 
`
[root@ip-10-66-2-107 .lpass]# lpass login max@domain.com
Success: Logged in as max@domain.com.
[root@ip-10-66-2-107 .lpass]# ls -l
total 28
srwx------ 1 root root    0 Feb  5 14:41 agent.sock
-rw------- 1 root root    4 Feb  5 14:41 iterations
-rw------- 1 root root 1280 Feb  5 14:41 session_privatekey
-rw------- 1 root root   80 Feb  5 14:41 session_sessionid
-rw------- 1 root root  128 Feb  5 14:41 session_token
-rw------- 1 root root   64 Feb  5 14:41 session_uid
-rw------- 1 root root   22 Feb  5 14:41 username
-rw------- 1 root root   96 Feb  5 14:41 verify
[root@ip-10-66-2-107 .lpass]# lpass ls
Error: HTTP response code said error.
`
I am "root" and in my home directory and SELinux is not enabled. So I don't see why it would be unable to create the session_server file. 

I just noticed it also hit lastpass.com for the logout : 
`   POST https://lastpass.com/logout.php
        ← 302 text/html [no content] 156ms
`
Although restoring the .lpass directory doesn't seem to restore my session, so it does seem to cause a logout with the .com server.

**Comment by bcopeland** [comment]
Ok, well, that's a clue.  Can you try this debug patch so we can see which part might be going wrong?

[0001-debug-eu-login-patch.txt](https://github.com/lastpass/lastpass-cli/files/119318/0001-debug-eu-login-patch.txt)

**Comment by max-allan-surevine** [comment]
```[root@ip-10-66-2-107 lastpass-cli-master]# lpass login max@domain.com
Using server: (null), passed-in server: (null), session: (nil)
Ordinary login called with login_server: lastpass.com
Using server: lastpass.com, passed-in server: lastpass.com, session: (nil)
Ordinary login called with login_server: lastpass.eu
Using server: lastpass.eu, passed-in server: lastpass.eu, session: (nil)
OTP login using server lastpass.eu
Using server: lastpass.eu, passed-in server: lastpass.eu, session: (nil)
Saving the session, session->server is: null!
Success: Logged in as max@domain.com.
[root@ip-10-66-2-107 lastpass-cli-master]# lpass ls
Loaded the session, session->server is: null!
Using server: (null), passed-in server: (null), session: 0x25e8110
Error: HTTP response code said error.
```

(We do use Google Auth, so maybe other people not using G-auth are fine)

**Comment by bcopeland** [comment]
Indeed, does the attached patch fix?
[0001-login-set-the-login-server-for-EU-if-2fa-succeeds.txt](https://github.com/lastpass/lastpass-cli/files/121716/0001-login-set-the-login-server-for-EU-if-2fa-succeeds.txt)

**Comment by max-allan-surevine** [comment]
Yes, thanks! That does the job.

**Comment by bcopeland** [comment]
Thanks for testing, pushed out to master branch.
