### ISSUE TITLE
'lpass show' is unable to download from 3rd level folder depth

### ISSUE THREAD

**Issue by dolphy17** [lastpass/lastpass-cli#156]
Neither 'lpass ls' work for:

lpass ls "First/Second/Third"

However 'lpass ls' at root level shows the complete structure.

**Comment by jfield** [comment]
I'm also seeing this problem - anything 3 deep it just returns the location, but none of the data. This was working, and I hadn't actually updated lastpass-cli when it broke. I've since upgraded and it still doesn't work - something on the API side maybe?

**Comment by bcopeland** [comment]
The API could only be involved if this were a shared folder: lastpass doesn't actually see the group hierarchy of normal sites on the server side; it is simply stored as an encrypted string attribute.

It should be pointed out, that, for compatibility with everything else, _backslashes_ need to be used to separate individual group components, and slashes to separate group names from account names.  I know this makes for pretty rough UX, but, well, that's how it works today.

Anyway, I tried the following with current head with no obvious problems:
```
$ ./lpass generate "some/slash/folder/a name" 10
[password]
$ ./lpass generate "some\backslash\folder/a name" 10
[password]
$ ./lpass ls
[...]
some/slash/folder
    a name [id: 3991309521641590183]
some
    backslash
        folder
            a name [id: 3604779141773469739]
[...]
$ ./lpass show "some/slash/folder/a name"
some/slash/folder/a name [id: 3991309521641590183]
Password: [xxx]
$ ./lpass show "some\backslash\folder/a name"
some\backslash\folder/a name [id: 3604779141773469739]
Password: [xxx]
```
Can you give a similar example that shows the broken behavior?

**Comment by bcopeland** [comment]
Just to add, because of the slash/backslash confusion, the OP example should use:
```
$ ./lpass ls First\Second\Third
```
Originally, we parsed forward slash as the separator for individual path components, but this turned out to be incorrect compared to what LP does everywhere else (if you did that, you'd wind up with an entry with the folder name "foo/bar/baz" instead of a 3-level hierarchy).  It might make sense to have an option to transparently convert them, or maybe that's too confusing -- I'm not really sure.

**Comment by jfield** [comment]
I'm not actually using the path in the show command, I'm using the numeric ID. It just seems to fail only fail on deeper nested items (and these are things that work through the plugin & web vaults). It just returns a single line with the path and the name.

I'll give examples when I'm back at my desk.

**Comment by bcopeland** [comment]
Any update here?  Things are working for me.

**Comment by danjjeff** [comment]
I just set up lpass on Fedore 23 (v 0.8.0-1) and seem to be encountering the same behavior. I am dealing with shared folders and accounts. 

## Shared Account ##
lpass ls myemail@provider.com\base #returns nothing
lpass ls myemail@provider.com/base #returns nothing
lpass ls myemail@provider.com #returns all items from the shared account

## Shared Folder ##
lpass ls Shared-folder\DC #returns nothing
lpass ls Shared-folder/DC #returns all entries in folder DC
lpass ls Shared-folder/DC/Systems #returns nothing

Using the uniqueid or even just the exact name of the account itself does seem to work fine.

**Comment by bcopeland** [comment]
The latter (unfortunately) needs to be ```lpass ls Shared-folder/DC\Systems``` ... I know, that makes no sense at all.

As for the others -- I'm not able to duplicate here.  But there have been some changes in 0.9.0 for ```lpass ls```.

**Comment by bcopeland** [comment]
Not to make excuses for the bad UX, but if it helps understanding, the way the folder separator stuff works is:

[shared folder or linked account] '/' [groupname] '/' [account name]

In particular, the groupname is not any kind of hierarchy in the blob, it's just an encrypted string.  The "lpass ls" command, and all lastpass plugins, for that matter, construct folders from groupname.

For historical reasons that weren't apparent at the time when lastpass-cli was written, "\" is used to separate "subfolders" inside the groupname.  We used to split on forward slashes too, but that actually caused some confusion when people had embedded forward slashes in their groupnames and then bogus subfolders got created.   

So perhaps it would make more sense to use backslash everywhere, or else somehow escape forward slashes inside groupnames, but for now this is how things work.

**Comment by danjjeff** [comment]
I tried both ```lpass ls Shared-folder/DC\Systems``` and ```lpass ls Shared-folder\DC/Systems``` and still got nothing back. Read your explanation and tried again, quoting the shared folder and groupname and it worked:
```lpass ls "Shared-folder/DC\Systems"```

The ```myemail@provider.com``` option I explored a little more and it works with the 'suggested' folders (i.e. Travel, Entertainment, etc), but the 'base' folder (originally imported from a CSV) and several layers of folders beneath it, ```lspass ls``` cannot seem to identify.

I can try compiling 0.9.0 a little later and see if that sorts it out.

**Comment by bcopeland** [comment]
Ah, yes, thanks -- shell will interpret \X as just X so it does need quoting or double backslashes.

**Comment by danjjeff** [comment]
Leaving a comment for anyone who finds this:
I did not end up upgrading at this point. Instead I just switched to using -G and regex searching instead of using the pseudo folder hierarchy.

**Comment by bcopeland** [comment]
@danjjeff FYI if you want to always use '-G' you can do that with an alias: ```echo "show -G" > ~/.lpass/alias.show```

**Comment by bcopeland** [comment]
Closing this as it looks like there's not actually a bug here, just confusing UX.

**Comment by raymondKelly** [comment]
> Closing this as it looks like there's not actually a bug here, just confusing UX.

@bcopeland is that really a good reason to close it? At the least, the documentation should be updated to inform people.
