### ISSUE TITLE
Honor the https_proxy environment variable

### ISSUE THREAD

**Issue by chmduquesne** [lastpass/lastpass-cli#160]
Hello,

When using the lpass command line tool this morning, I stumbled on the following error:

    Error: Peer certificate cannot be authenticated with given CA certificates.

My company runs a [Blue Coat Proxy](https://en.wikipedia.org/wiki/Blue_Coat_Systems), which essentially performs a MITM attack in order [to snoop on employees traffic](http://security.stackexchange.com/questions/33976/man-in-the-middle-blue-coat-proxy-ssl-or-what). Because it triggers all sorts of problems with certificates, there is also an https proxy for developers, and we all simply do:

    export https_proxy="https://proxy.company.local:3128"

This does the trick for most command line tools, provided they honor this https_proxy variable.

I have the feeling lpass does not honor the https_proxy variable. Would it be possible to add support for it? Otherwise lpass is unusable for me :(

Thank you!

**Comment by bcopeland** [comment]
I believe we already do (or rather libcurl does).  Your issue is most likely an instance of #88 -- all you need to do is update lastpass-cli to a newer version.

**Comment by chmduquesne** [comment]
Indeed. I compiled the program rather than using the one provided by debian and it now works with no issue.

**Comment by bcopeland** [comment]
I send this via email but github apparently ate it:
```
Okay -- the binary package in jessie is pretty old at this point but testing and unstable have updated versions which should work as far as I know.
```
