### ISSUE TITLE
make usage of --non-interactive flag obvious

### ISSUE THREAD

**Issue by whysthatso** [lastpass/lastpass-cli#163]
the usage is not clearly explained in teh man page, i.e. when issuing:
`lpass add --non-interactive --note "Shared-directory/testentry"
nothing happens 
neither
`echo "testentry" | lpass add --non-interactive --note "Shared-directory/testentry"`
nor 
`lpass add --non-interactive --note "Shared-directory/testentry" < echo "testentry"`
worked.

coudl anybody provide a working esxample how to add a note/entry in a non interactive fashion, i.e. for scripting purposes?

thanks

**Comment by whysthatso** [comment]
actually, it seems to have worked, there was an unexpected delay in syncing from server to other clients. however, the point for an example still remains, or some more clarification might still help the unexpecting user

**Comment by whysthatso** [comment]
this worked for me:
echo "piped testentry" | lpass add --non-interactive --note "Shared-directory/testentry"

**Comment by bcopeland** [comment]
A PR to add something to the man page would be great (see CONTRIBUTING file).

There's also an example of doing multiple fields at once, from the commitlog that added that:
```
(echo "Username:foo"; echo "Password: bar") | \
    ./lpass add somesite --non-interactive
```
