### ISSUE TITLE
No good way to create secure note

### ISSUE THREAD

**Issue by tod-uma** [lastpass/lastpass-cli#165]
There doesn't seem to be a way to create a new secure note. The generate subcommand always creates a site. You can create a secure note template and duplicate it, but that leads to problems.

**Comment by bcopeland** [comment]
Did you try ```lpass add --notes Foo```

**Comment by tod-uma** [comment]
That will add text to the note field, not make the entry a secure note, or one of the note types like Server, Database, etc. If you try to use lpass add and force the NoteType field you get an error:

$ lpass add --field=NoteType test/Test6
Error: Editing fields of entries that are not secure notes is currently not supported.

Also, the add command is not documented in the man page at all, although I do see it in lpass help.

**Comment by bcopeland** [comment]
The add (and edit) commands will set the type to a secure note if the only thing being edited is a note field, and all other fields are otherwise empty.  You can also set the url to "http://sn" which is a special marker for SNs.  

Yes, now that add and edit support editing templates, we should just add support for all of the existing note types.  That would be in ```edit.c``` -- patches adding that kind of functionality would be most welcome.

**Comment by dnorthup-ums** [comment]
I went ahead and had a look at the code. After looking at cmd-add.c it is incredibly clear that as-written it is impossible to use the add command as intended as it can only add *one* "field" (username, password, url, etc) at a time—which also makes it impossible to create secure notes "all in one go" as a user would expect. Some refactoring will be necessary to make it work properly from a user perspective, as "add thingy" followed by several rounds of "edit thingy" it not the normally expected way of doing things (if it works at all...I'm going to try it).

**Comment by bcopeland** [comment]
Are you sure you are looking at the master branch?

If you pass no arguments, it will pop up a text file for you to edit with multiple fields...

**Comment by dnorthup-ums** [comment]
@bcopeland I am actually running a modestly updated version of efb90bf98e1 which allows getopt_long to parse all of the possible options covered by the switch block at line 77 of cmd-add.c, as in the upstream only *u* and *p* were specified. Alas, that minor fixup doesn't actually make it behave any better due to the execution flow of the code.

The expected behavior of the below two lines of bash would have been:
1. Create an empty Secure Note of default type
2. Pop up the text file editor

In both cases it just prints the help dialog.

```bash
[dnorthup@drew-northup ~]$ /home/dnorthup/local_git_repos/lastpass-cli/lpass add --url "http://sn" "Secure Notes/Test Note 2"                                                                             
Usage: /home/dnorthup/local_git_repos/lastpass-cli/lpass add [--sync=auto|now|no] [--non-interactive] [--color=auto|never|always] {--username|--password|--url|--notes|--field=FIELD} NAME
[dnorthup@drew-northup ~]$ /home/dnorthup/local_git_repos/lastpass-cli/lpass add
Usage: /home/dnorthup/local_git_repos/lastpass-cli/lpass add [--sync=auto|now|no] [--non-interactive] [--color=auto|never|always] {--username|--password|--url|--notes|--field=FIELD} NAME
```


```diff
diff --git a/cmd-add.c b/cmd-add.c
index 57b2031..ffc7a4a 100644
--- a/cmd-add.c
+++ b/cmd-add.c
@@ -73,7 +73,7 @@ int cmd_add(int argc, char **argv)
        bool is_app = false;
 
        #define ensure_choice() if (choice != EDIT_ANY) goto choice_die;
-       while ((option = getopt_long(argc, argv, "up", long_options, &option_index)) != -1) {
+       while ((option = getopt_long(argc, argv, "SupLFOXaC?", long_options, &option_index)) != -1) {
                switch (option) {
                        case 'S':
                                sync = parse_sync_string(optarg);
```

**Comment by bcopeland** [comment]
The changed string only affects which "short" options can be passed.  I intentionally do not expose all of them so as to minimize chances of short options meaning conflicting things between different commands.

If you pass something like --url it has to come from stdin, like
```
echo "http://sn" | lpass add --url bar
``` 
If you just pass --notes, then it sets URL to http://sn automatically.

I think the interface you are looking for is:
```
printf "NoteType:Database\nUsername: admin\nPassword: admin\nType: Postgres\nHostname: db01\nPort: 5432\nDatabase: users\nNotes:\nThis is the production DB\n" | ./lpass add --notes --non-interactive MyPgDB
```
And then it would probably be a short amount of work to refine that to:
```
./lpass add --note-type=Database MyDB
```
Where --note-type would, in edit.c, generate the proper template.  This is what I meant by teaching edit.c about the various templates.

**Comment by bcopeland** [comment]
I went ahead and implemented my last suggestion on the HEAD:
```
./lpass add --note-type=drivers-license my-license
```
To see a list of types:
```
./lpass add --note-type=x
```

**Comment by dnorthup-ums** [comment]
@bcopeland I'm afraid I can't verify your fix because the sync process is hanging...
