### ISSUE TITLE
CA cert issue with 0.9.0

### ISSUE THREAD

**Issue by mtoothman** [lastpass/lastpass-cli#169]
`$:/# lpass --version
LastPass CLI v0.9.0`

After upgrading to 0.9.0 to address 
`Error: Peer certificate cannot be authenticated with given CA certificates.`
this issue persists.

Do I need to take additional action to use the correct certificate? We use `lpass-cli` as part of a CircleCI build process, so this is happening inside a Docker container that CircleCI creates at buildtime.

**Comment by bcopeland** [comment]
On Sun, May 01, 2016 at 06:10:15AM -0700, Matt wrote:
> ```$:/# lpass --version
> LastPass CLI v0.9.0```
> 
> After upgrading to 0.9.0 to address 
> `Error: Peer certificate cannot be authenticated with given CA certificates.`
> this issue persists.
> 
> Do I need to take additional action to use the correct certificate? We use `lpass-cli` as part of a CircleCI build process, so this is happening inside a Docker container that CircleCI creates at buildtime.

What OS is the Docker container running?

The additional requirement is that libcurl should be built having a
reasonable platform certificate store.  Usually, it uses the platform
certificate store, but if that were missing or it were compiled without
such a setting then it would be unable to verify the cert.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by mtoothman** [comment]
OK, good info. The container runs Ubuntu 14.04.3 LTS. I'm not aware of any changes to libcurl at all. Do you advise attempting to rebuild it? curl provides a [handy page](https://curl.haxx.se/docs/caextract.html) to get a recent Mozilla cert bundle.

`/etc/ssl/certs` on the container has all the stuff in it you'd expect, including a few Thawte certs.

**Comment by bcopeland** [comment]
Hmm, so I built lastpass-cli on a recent vagrant ubuntu 14.04.3 LTS image, using libcurl4-openssl-dev and libxml2-dev and everything is working here.

Forgot to ask, are you using lastpass.com or lastpass.eu?

Some details from my vagrant VM:
```
$ dpkg -l ca-certificates
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version           Architecture      Description
+++-========================-=================-=================-======================================================
ii  ca-certificates          20141019ubuntu0.1 all               Common CA certificates

$ md5sum /usr/share/ca-certificates/mozilla/GeoTrust*
a8682761b5055d468bdc7c7c86240b08  /usr/share/ca-certificates/mozilla/GeoTrust_Global_CA_2.crt
a59fa24705ed0be7ff6b00d5f3aefd5c  /usr/share/ca-certificates/mozilla/GeoTrust_Global_CA.crt
d68c1f01ac27820f8619aece39e04ab0  /usr/share/ca-certificates/mozilla/GeoTrust_Primary_Certification_Authority.crt
a515ce63f77afbca2e19af8aa64019c3  /usr/share/ca-certificates/mozilla/GeoTrust_Primary_Certification_Authority_-_G2.crt
f4be9f921f176c357f1ebb2e9d8a33cb  /usr/share/ca-certificates/mozilla/GeoTrust_Primary_Certification_Authority_-_G3.crt
ce531e74cd0ba6a2456e1a3c4b710a57  /usr/share/ca-certificates/mozilla/GeoTrust_Universal_CA_2.crt
034c17251a18993f996f3020b0f97384  /usr/share/ca-certificates/mozilla/GeoTrust_Universal_CA.crt
```

**Comment by mtoothman** [comment]
ibcurl4-openssl-dev and libxml2-dev here as well. I'm using lastpass.com.

**Comment by bcopeland** [comment]
Can you try this version and set LPASS_LOG_LEVEL=7?  https://github.com/bcopeland/lastpass-cli/

That enables curl logging so will dump a lot more stuff to the log and to stderr.

**Comment by mtoothman** [comment]
When building this fork:
```/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libxml2.so: undefined reference to `gzopen64@ZLIB_1.2.3.3'
collect2: error: ld returned 1 exit status
make: *** [lpass] Error 1```

**Comment by bcopeland** [comment]
On Fri, Jun 17, 2016 at 06:43:34PM -0700, Matt wrote:
> When building this fork:
> ```/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libxml2.so: undefined reference to `gzopen64@ZLIB_1.2.3.3'
> collect2: error: ld returned 1 exit status
> make: *** [lpass] Error 1```

This fork builds for me, and also doesn't change the Makefile at all
compared to lastpas-cli master, so I'm confused as to how building
lastpass-cli master works in your environment?

It sounds like libxml2 picked up a dependency on zlib, so you can
either edit the Makefile to manually add '-lz' to LDLIBS or check
that ```pkg-config --libs libxml-2.0``` is working properly (the
Makefile will fallback to just -lxml2 if not).

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by bcopeland** [comment]
FYI I have merged a much evolved version of that patch into master just now, so you can also test with master if that is easier to build in your environment.

**Comment by bcopeland** [comment]
By the way on master you will need to use LPASS_LOG_LEVEL=8 to see the curl messages.

**Comment by mtoothman** [comment]
Thanks! No longer an issue.
