### ISSUE TITLE
lpass is not properly pushing queued changes

### ISSUE THREAD

**Issue by xPopTartsx** [lastpass/lastpass-cli#176]
I have been trying sync changes I have created with lpass edit to properly sync with my last pass vault.  I have used the program via the terminal and through a php script I have been working on however changes rarely sync properly.  I am wondering if there is perhaps a network issue that could be causing this?

I have also tried the work around of having the --sync=no and then running lpass sync this does not appear to help me.

**Comment by bcopeland** [comment]
1) Make sure you have b78ae2ef2ed185e32147c3d51db219d8d003594e
2) If that doesn't work, set LPASS_LOG_LEVEL=7 and get a log file.

**Comment by xPopTartsx** [comment]
1) I added this code and this did not work
2) I set the  LPASS_LOG_LEVEL=7  and the log file did not generate in .lpass/  

I am a bit lost at the moment.

**Comment by bcopeland** [comment]
Most likely the uploader has already started: the log only gets created if LPASS_LOG_LEVEL=7 when the uploader process is forked the first time.  I think perhaps setting CURLOPT_VERBOSE and redirecting stderr to the log would be one route to getting more information, another way is to set up a proxy with mitmproxy to see which requests are failing.

**Comment by bcopeland** [comment]
Please update to master and try with LPASS_LOG_LEVEL=8, I've added CURLOPT_VERBOSE when using that loglevel.

**Comment by xPopTartsx** [comment]
My apologies.  for not updating this sooner.  I found that lastpass is functioning correctly it was that my server was killing the process.
