### ISSUE TITLE
config.c:194]: (error) Resource leak: file

### ISSUE THREAD

**Issue by dcb314** [lastpass/lastpass-cli#185]
Suggest add missing call to fclose.

**Comment by bcopeland** [comment]
On Fri, Jul 15, 2016 at 07:53:16AM -0700, dcb314 wrote:
> Suggest add missing call to fclose.

This is already done via _cleanup_fclose attribute.  Is
this a static checker?

**Comment by dcb314** [comment]
Hello there,
________________________________
> On Fri, Jul 15, 2016 at 07:53:16AM -0700, dcb314 wrote: 
> > Suggest add missing call to fclose. 
>  
> This is already done via _cleanup_fclose attribute. 

Indeed it is. Sorry my mistake.

> Is this a static checker? 

Yes, cppcheck.


Regards

David Binderman

**Comment by bcopeland** [comment]
Thanks, closing.
