### ISSUE TITLE
Certificate error on login

### ISSUE THREAD

**Issue by JacobDB** [lastpass/lastpass-cli#188]
Just discovered this tool, super excited to give it a try. Sadly, I keep getting an error when trying to run `lpass login` on Ubuntu 16.04.

    Error: Peer certificate cannot be authenticated with given CA certificates.

This occurs when I run

    lpass login john@doe.com

Obviously replacing john@doe.com with my real LastPass login email. I've also trued using the `--trust` and `--force` flags, to no avail. Would really appreciate some guidance, I'm pretty sure I'm missing something obvious.

**Comment by JacobDB** [comment]
Nevermind, I should read instructions more clearly :) I installed using apt-get instead of building it from the repository. It's working properly now.

**Comment by bcopeland** [comment]
I'll go see if I can dig up an ubuntu maintainer to update to a newer version or backport patches for them.
