### ISSUE TITLE
Toopher auth asked every time I login ... feature or bug?

### ISSUE THREAD

**Issue by jhirbour** [lastpass/lastpass-cli#19]
We have toopher authentication required on our corporate last pass accounts.

Every time I do `lpass login MYUSERNAME`  I have to goto my phone and click "Approve" in toopher.

Is the command line utility supposed to remember my device/computer like the chrome plugin does? Or is this expected behavior?   If it's expected it'd make scripting password changes (like https://github.com/lastpass/lastpass-cli/blob/master/contrib/examples/change-ssh-password.sh) nearly impossible.

**Comment by bruce-ricard** [comment]
I have the opposite problem. I would like to configure the chrome extension to ask for MFA **every** time I want to log in. Is there a way to do that?
