### ISSUE TITLE
Error: Peer certificate cannot be authenticated with given CA certificates.

### ISSUE THREAD

**Issue by catroll** [lastpass/lastpass-cli#191]
```sh
$ lpass login <email>
Error: Peer certificate cannot be authenticated with given CA certificates.
```

**Comment by catroll** [comment]
- Ubuntu GNOME 16.04
- LastPass CLI v0.7.0

**Comment by bcopeland** [comment]
On Sun, Aug 07, 2016 at 10:53:25PM -0700, 胡昂 wrote:
> - Ubuntu GNOME 16.04
> - LastPass CLI v0.7.0

You need at least v0.7.2 which has a backport explicitly for this.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by componhead** [comment]
One year after, in the ubuntu repositories, it's still at v0.7.0-1
Same problem (Gnome 16.04)
