### ISSUE TITLE
Add formats for show

### ISSUE THREAD

**Issue by moserke** [lastpass/lastpass-cli#192]
Is there an easy way to add different formats for the show command?  For example, yaml or json as the output format.  This would make scripting against the cli much easier as the output would be a in a format that would be better suited for parsing.

**Comment by bcopeland** [comment]
Not currently, but I would take a patch to use printf-style format strings, similar to ```git log --pretty=tformat:X```.

You can also look at the export command if you just want to see all the features in CSV format, and you can display a single field of an account by specifying the fieldname in show (e.g. ```lpass show --password foo```).  Perhaps if I knew more about what kind of scripting you have in mind (no, I wouldn't parse the output of show either!) then I could suggest something.

**Comment by bcopeland** [comment]
This is merged now.
