### ISSUE TITLE
lpass add : be able to push all credentials though non-interactive command

### ISSUE THREAD

**Issue by xPopTartsx** [lastpass/lastpass-cli#193]
I have been encountering a performance issue with the lpass add command in my script.  To add a site and add the credentials I have been doing an add and then edits via non-interactive mode.  Is there a better way to do this?  Or perhaps make it so that we can pass all the parameters for the site at once?

**Comment by bcopeland** [comment]
On Mon, Aug 22, 2016 at 08:37:55AM -0700, Robert Kaldenbach wrote:
> I have been encountering a performance issue with the lpass add command in my script.  To add a site and add the credentials I have been doing an add and then edits via non-interactive mode.  Is there a better way to do this?  Or perhaps make it so that we can pass all the parameters for the site at once?

You can pass all the parameters for the site at once (in stdin); see the
commit log here for an example:

https://github.com/lastpass/lastpass-cli/commit/392372448e9b94f4e370f1e64a346ad4754f6847

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by xPopTartsx** [comment]
Thank you so much.  This is exactly what I need.
