### ISSUE TITLE
lpass Error: Could not find decryption key.

### ISSUE THREAD

**Issue by pnikolaev31** [lastpass/lastpass-cli#194]
Hello,
I have a very strange issue which I cannot solve already 3rd day. I am using the latest lastpass-cli (LastPass CLI v1.0.0) under Centos (7.2.1511 Core). I am logged in into my user account successfully:

**root**@xxx [/home/scorpion]# lpass status
Logged in as ...

I have a script which I execute as **root** and this script is supposed to do some automation suff for me, but instead it troughs me an error: 
Error: Could not find decryption key. Perhaps you need to login with `lpass login`.
Kindly let me know what can I do to fix that.
Sorry if this is not the right place to ask.
Thank you!
P.S. Strange fact is that the script sometimes manages to add a record in my lastpass directory, sometimes not. Very weird behavior.

**Comment by xPopTartsx** [comment]
Are you logging into the lpass using your script?  I ask because I have seen a similar issue which was caused when I had the askpass variable setup incorrectly and had manually logged into lpass via the terminal before running my script.  Once the lpass session timed out the script would stop working because my script was never properly logging in.  This also caused the script to add records into my lastpass directory and sometimes not.

**Comment by pnikolaev31** [comment]
I am logging via the terminal and immediately after that I run the script?

**Comment by bcopeland** [comment]
This could happen if, for example, your environment is different in the shell versus in your script (so that ```agent_socket_path()``` returns something different), or if there are permissions issues when opening the unix domain socket, etc.

Running lpass with strace is a good way to debug this kind of thing.

**Comment by pnikolaev31** [comment]
Thank you for the advice (I think the strace is telling me a lot). But wat is the proper way to sort of equalize the environment in the shell and in the script :
`munmap(0x7fe1d76c4000, 38791)           = 0
set_tid_address(0x7fe1d76b2b10)         = 348
set_robust_list(0x7fe1d76b2b20, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7fe1d4e4f780, [], SA_RESTORER|SA_SIGINFO, 0x7fe1d4e58100}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7fe1d4e4f810, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fe1d4e58100}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
statfs("/sys/fs/selinux", {f_type=0xf97cff8c, f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096}) = 0
statfs("/sys/fs/selinux", {f_type=0xf97cff8c, f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096}) = 0
stat("/sys/fs/selinux", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
brk(0)                                  = 0x1c35000
brk(0x1c56000)                          = 0x1c56000
access("/etc/system-fips", F_OK)        = -1 ENOENT (No such file or directory)
umask(077)                              = 022
futex(0x7fe1d4e480d0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
gettid()                                = 348
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER, 0x7fe1d64fa670}, NULL, 8) = 0
stat("/root/.lpass", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
open("/root/.lpass/env", O_RDONLY)      = -1 ENOENT (No such file or directory)
stat("/root/.lpass", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
open("/root/.lpass/alias.add", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/root/.lpass", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
stat("/root/.lpass/plaintext_key", 0x7fff8ed25af0) = -1 ENOENT (No such file or directory)
stat("/root/.lpass", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/root/.lpass/agent.sock"}, 25) = -1 ENOENT (No such file or directory)
close(3)                                = 0
stat("/root/.lpass", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
open("/root/.lpass/iterations", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/root/.lpass", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
open("/root/.lpass/username", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(2, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7fff8ed24920) = -1 ENOTTY (Inappropriate ioctl for device)
write(2, "Error", 5Error)                    = 5
write(2, ": Could not find decryption key."..., 88: Could not find decryption key. Perhaps you need to login with `/usr/bin/lpass login`.
) = 88
exit_group(1)                           = ?
+++ exited with 1 +++
`
Thank you!

**Comment by bcopeland** [comment]
If I had to guess, I'd say you are missing some variables like ```$XDG_RUNTIME_DIR``` in the shell script; these are usually set by the desktop environment.  Best way to confirm is to just run ```env > shell_env.txt``` inside your shell script, and then ```diff shell_env.txt <(env)``` from your interactive shell.

You have a couple of options:
 * make interactive shell use the same thing as in your script environment, e.g. by setting ```export LPASS_HOME=$HOME/.lpass``` in your ```.bashrc```
 * make script match interactive shell by copying missing ```$XDG``` variables.  You can look at https://github.com/lastpass/lastpass-cli/blob/668ea0011c6a644be0093981c78a5e5bf151495c/config.c#L112-L129 to see where lpass looks for things.
