### ISSUE TITLE
lpass login question

### ISSUE THREAD

**Issue by xPopTartsx** [lastpass/lastpass-cli#196]
Thanks for answering this question in advance.  I have been asked to look into if it would be possible to login to lpass using something other than an accounts username and password.  Perhaps something more like how the API works.  I looked through the login code and commits and I believe this is a firm no however asking to just to make sure.
Thanks!

**Comment by bcopeland** [comment]
No.

Well, perhaps it is more correct to say you can also log in with the session token (once you have authenticated normally, and as long as the session is still active) but you will also need the key (derived from your password) to do anything useful.

In the case of the API, for the most part things there are not dealing with the vault per se but user management etc., and therefore do not need the key, so it makes more sense there to allow additional authentication.

If you don't want to use your own password, one option is to dedicate an account for the kinds of things you want to automate, and put sites in a shared folder that both your account and the other one have access to.

**Comment by xPopTartsx** [comment]
This is exactly what I was thinking.  Thank you for all of your help.
