### ISSUE TITLE
curl vs libcurl host CAs differenent

### ISSUE THREAD

**Issue by moserke** [lastpass/lastpass-cli#197]
alpine 3.4

Due to the netskope appliance the lastpass cert gets replaced with a custom cert that is signed by netskope.  Therefore need to add the new certs into the CA trust.  I add the certs with update-ca-certificates and curl works fine at that point, however lpass still throws Error: Peer certificate cannot be authenticated with given CA certificates.

I went as far as building libcurl from source on the host so that curl and lpass were definitely built from the same deps, but still get the same issue.

Why is the CA being trusted in curl but not in lpass when they are both using the same libcurl and built agains the same libcurl.

**Comment by bcopeland** [comment]
On Wed, Aug 24, 2016 at 03:43:43PM -0700, Kevin Moser wrote:
> alpine 3.4
> 
> Due to the netskope appliance the lastpass cert gets replaced with a custom cert that is signed by netskope.  Therefore need to add the new certs into the CA trust.  I add the certs with update-ca-certificates and curl works fine at that point, however lpass still throws Error: Peer certificate cannot be authenticated with given CA certificates.
> 
> I went as far as building libcurl from source on the host so that curl and lpass were definitely built from the same deps, but still get the same issue.
> 
> Why is the CA being trusted in curl but not in lpass when they are both using the same libcurl and built agains the same libcurl.  

lpass also pins the LastPass certificates (see pins.h) precisely to avoid
unknowingly accepting a certificate with a different root.  You'll need
to pin the netskope root cert in your build.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by moserke** [comment]
Is there a command to generate the pins?  I am assuming this is some openssl command against the certificate?

**Comment by bcopeland** [comment]
See commit log for 375b77fc58bcc45c7b9770b04017a4466750ccca.

**Comment by moserke** [comment]
Great, worked like a charm.  Thanks.
