### ISSUE TITLE
Confusing names

### ISSUE THREAD

**Issue by djui** [lastpass/lastpass-cli#201]
I'm confused by the names `GROUP`, `SHARE`, `UNIQUEID`, Folders. 

I try to get the values for these keys, but simply can't figure it out. We have shared folders, but I don't see how this would map to `GROUP`s, `SHARE`s or `UNIQUEID`s.

- I try to `lpass ls` but I can't figure out how to get the `GROUP` name.
- I try to `lpass show` but I can't figure out how to get the `UNIQUEID ` name.

I can run `lpass share userls` there only see users.

**Comment by djui** [comment]
Also even though I can see that I am logged in, `lpass export` is empty.

**Comment by gunslingerfry** [comment]
These values are shown when you do an ls or a show although they are not identified as such. Folders = group if I'm understanding it correctly.
e.g. my _lpass ls_ has this output:

Entertainment
  plex.tv [id: 8...7]
Travel
    starwoodhotels.com [id: 4...3]

format:
**GROUP**
**UNIQUENAME [id: UNIQUEID]**
**...**

my _lpass show plex.tv_ has this output:
Entertainment/plex.tv [id: 8...7] 
...

format:
**GROUP/UNIQUENAME [id: UNIQUEID]**

If I do an lpass ls Entertainment it will only give me the Entertainment list. If I do an lpass show 8...7 it will give me the details on the plex.tv item.

**Comment by bcopeland** [comment]
Yes, group is approximately folder name, and is generally treated as such.  For the special case of shared folder commands, it is ```SHARE/GROUP/UNIQUENAME```.

So Shared-Folder-Abc/Foo\Bar\Baz/Quux breaks down into:
```
Share: Shared-Folder-Abc
Group: Foo\Bar\Baz
Name: Quux
```
though most commands like `lpass ls` will just pretend like Share and Group are both part of Group.
