### ISSUE TITLE
Adding exaples and brief description of functions

### ISSUE THREAD

**Issue by piotrKantor** [lastpass/lastpass-cli#202]
It would be nice if it was some examples packed into man so it would be clear how to use it.

Some brief description of existing function would be great as well, because right now it's not clear what this function do.

**Comment by bcopeland** [comment]
There is an examples section at the end of the man page -- please feel free to send a PR if there are more examples you would like to have included.

**Comment by gunslingerfry** [comment]
Rather than pulling all the ridiculous dependencies for asciidoc I've just bookmarked the generated man page here: https://lastpass.github.io/lastpass-cli/lpass.1.html

**Comment by gunslingerfry** [comment]
Personally, I'd like to see an add example. I still haven't figured out how that works. I'd also like to see a better description of the environment variables as I, again, can't seem to get lpass to read them.

**Comment by bcopeland** [comment]
On Fri, Sep 09, 2016 at 12:05:19PM -0700, gunslingerfry wrote:
> Personally, I'd like to see an add example. I still haven't figured out how
> that works. I'd also like to see a better description of the environment
> variables as I, again, can't seem to get lpass to read them.

Ok, I'll add some examples for add/edit and see if I can reword the
environment section.

**Comment by bcopeland** [comment]
Done.
