### ISSUE TITLE
add password entry to vault in specific folder

### ISSUE THREAD

**Issue by kevinlong206** [lastpass/lastpass-cli#206]
Hello,

Sorry if I am being daft, but I've now read the man page, perused the github and googled,  and I still cannot figure out how to actually add a new password entry to my Lastpass vault.

I can login and list entries, but my hope is to add the capability to some of my bash scripts to generate passwords and automatically name them and place them into an existing Lastpass shared folder.  Is this functionality available?

If so you can please provide the CLI syntax? 

I am on OSX LastPass CLI v0.9.0 installed via homebrew , but also often work on Debian.

**Comment by derekjbernard** [comment]
Look at the bash scripts in contributed/examples

**Comment by kevinlong206** [comment]
@derekjbernard  I've looked at them and still don't see an obvious example of adding a new entry to Lastpass vault

**Comment by bcopeland** [comment]
See:
https://lastpass.github.io/lastpass-cli/lpass.1.html#_examples

(just updated to match latest master manpage).
