### ISSUE TITLE
Missing `lpass import` command from brew installation

### ISSUE THREAD

**Issue by e03213ac** [lastpass/lastpass-cli#207]
I installed the command-line interface using Homebrew on OS X El Capitan:

```
brew install lastpass-cli --with-pinentry --with-doc
```

I noticed that the `lpass import` command is missing (but `lpass export` is available).

If I build `lastpass-cli` from source the `import` command is present.

**Comment by bcopeland** [comment]
If you install the HEAD version, it should have it.  This is just because I haven't done a release yet with import.

**Comment by bcopeland** [comment]
Now released.
