### ISSUE TITLE
Write Password from .net web application into LastPass application

### ISSUE THREAD

**Issue by KAVPT** [lastpass/lastpass-cli#209]
Hi,
I have a requirement to write password from the .Net web application to LastPass application when user would like to reset their password. This web application will be SSL Configured later stage.
I have looked command line at this location https://github.com/lastpass/lastpass-cli.
Not sure how to use this tool through the .net code.
Or is there any other solution available?
Can you advise on above requirement please.
Thank You

**Comment by bcopeland** [comment]
You can operate lastpass-cli over a pipeline (or named pipe) from another application.

That said, this probably won't be a very satisfying solution for your use case.  Is this for a user's master password or an account password?

**Comment by KAVPT** [comment]
Hi
Thank you for your response.
This is for account password.
Could you give some more details to operate lastpass-cli over a pipeline. How to use in .Net code.

**Comment by bcopeland** [comment]
I'm sorry, I don't really know much about .net, so I can't really help here.  For what it's worth, there is a third-party C# library for LastPass that I've seen on github before.  It is not an official LastPass library and I haven't looked at any of its code let alone verified its security properties, but it might help you -- unfortunately I don't recall the name, so you'll have to search.
