### ISSUE TITLE
Sync is super slow

### ISSUE THREAD

**Issue by noplanman** [lastpass/lastpass-cli#211]
When I run `lpass sync`, it takes quite some time to complete.

Checking the `~/.lpass/upload-queue` folder, there are about 8K files totalling to around 5MB. I see that around 9 files get removed each second, making the duration around 15 minutes (going by the maths).

Why is it so slow? Is that normal?

I'm on OSX Mavericks, lpass v1.0.0 from brew.

**Comment by bcopeland** [comment]
There is a rate limit built in the application to avoid overloading lastpass servers and tripping server-side abuse limits.  I have some experimental code to convert lots of updates into a single batch update, but I haven't had a chance to get that production ready yet.

May I ask what kind of usage pattern you are using which generates 8k updates?  (Not saying that is unusual, just want to make sure my changes can accommodate this workflow).

**Comment by noplanman** [comment]
I've written a short script that synchronises, exports, PGP encrypts, and saves.

Do I ever need to call `lpass sync`? Or does `lpass export` already do that if necessary?

Regarding the 8K, it seems that the the sync sometimes just takes a few seconds (which makes sense to me, as hardly anything every changes), but then from time to time it seems as if it does a full refresh of some sort.

Hope this helps!

Btw., this is the script I'm using at the moment. Please do suggest any improvements:
```bash
#!/usr/bin/env bash

# Make sure we have LastPass CLI installed
type "lpass" &>/dev/null || exit 1

# Set signing key ID.
key_id="<my-id>"

# Change into directory the script was called from.
cd "$(dirname "${0}")" || exit 1

# Export (plaintext)
lpass export --sync=auto > lastpass.csv

# Export (encrypted)
cat lastpass.csv | gpg -e -q -r "${key_id}" --yes > lastpass.csv.gpg
```

**Comment by bcopeland** [comment]
Sorry, I missed this question before.

There are two reasons to sync: 1) to upload pending account changes to lastpass; 2) to download the latest encrypted blob from lastpass.  The `lpass sync` command is really all about the first.  If you are just looking to get a snapshot of the vault at the current time, you can pass `--sync=yes` to always download the latest.  Alternatively, you can delete the `blob` file which will force it to be refetched.

**Comment by bcopeland** [comment]
One other note, it is better to directly pipe lpass export into gpg:

`lpass export --sync=yes | gpg -e -q -r $key --yes > lastpass.csv.gpg`

That way, unencrypted data never hits the disk.

**Comment by noplanman** [comment]
Perfect, thanks so much for the reply!

Will be using the pipe directly from now on 👌
