### ISSUE TITLE
Can't see all shared folders

### ISSUE THREAD

**Issue by trs80** [lastpass/lastpass-cli#212]
I have access to two shared folders, with similar names, the second one being called the same as the first but with " Credentials" appended to it. I can't see the second one any more, or reference it by name, using lastpass-cli 1.0.0 and 0.8.1 (both via Debian packages). I used to be able to see it with lastpass-cli 0.3.0 but I can't use that version due to the certificate issue. 0.7.0 segfaults, and 0.5.0 has the certificate issue too.

**Comment by bcopeland** [comment]
Does it have any accounts inside?  We may not show empty ones.  If that's not it, could you send me your account username in an email?  

Also there are builds with the certificate fix back-ported (0.5.1, 0.7.2, etc).

**Comment by trs80** [comment]
It's not empty, it has 33 passwords in it, email sent. I've just built 0.5.2, 0.4.0, 0.3.0 (copying thawte.pem from 0.5.2 to the latter two) and they all have the same behaviour, so maybe it's a server change?

**Comment by bcopeland** [comment]
Yes, there was a server-side change at some point.  The gist is that if a folder is shared with "hide passwords" then they are not delivered to the client (see e.g. #130).  It looks like that is the case with the folder name you sent to me in private.  If the admin can set it to give you the passwords from the sharing center in the webvault, it should show up for you.

**Comment by bcopeland** [comment]
Closing on the basis of previous comment; if it doesn't sound like what is going on, please reopen.
