### ISSUE TITLE
LastPass unexpectedly stopped auto filling apps on Galaxy S7 edge

### ISSUE THREAD

**Issue by ppolando76** [lastpass/lastpass-cli#213]
LastPass just all of a sudden quit autofilling for apps, specifically the Facebook app on my Galaxy S7 Edge. Auto fill for websites still works, but not for apps. I've been through all the troubleshooting with LastPass support and they were able to reproduce the issue. Any help would be greatly appreciated.

**Comment by bcopeland** [comment]
I'm sorry, this really isn't the right place to report it -- I can only address lastpass-cli issues and cannot do anything about the Android app.  I suggest opening a new ticket with support and ask them to tell you how to extract the proper debug logs for the Android developers which should help them solve it in the absence of being able to reproduce.
