### ISSUE TITLE
Suggestions for Usability Enhancement  

### ISSUE THREAD

**Issue by jsarcone** [lastpass/lastpass-cli#216]
I would like to make a few suggestions. I'm a former Roboform users. Overall I do like LastPass. However, I do find a couple of things that are annoying. 
1. Unable to set a default login card for a domain,
2. Bookmarklet is very poor and not very usable. 
3. The application detection doesn't exactly detect that application you have start the detection and then it will log in.
4. When a site doesn't match have the ability to select another login card would be helpful as well. This doesn't require you to open another program to select the login info. 
These areas are where roboform does well with. I just wanted to provide you this feedback to better your product.

**Comment by bcopeland** [comment]
Ok, thanks for the feedback.  It would be better to report this kind of thing with a support ticket, as this github is only for the open source command line client, and none of these suggestions are specific to that.

**Comment by jsarcone** [comment]
Thanks for getting back to me. But they pointed me to this site. I do have a support ticket open already. If you need the number let me know.
