### ISSUE TITLE
Touch ID not working properly

### ISSUE THREAD

**Issue by crocktherock** [lastpass/lastpass-cli#217]
I opened a ticket with Lastpass support - #4549992 and was instructed to report an issue here.  I updated to the current version of Lastpass on my iphone last week and touch ID stopped working.  When I logged into Lastpass app it immediately opens my vault.  

Based upon the support ticket I updated my iphone this morning to 10.1.1, reinstalled Lastpass app and I'm still having the same issue.  My lastpass settings are currently:

Remember password
Use Touch ID
My Lock options are immediately
Auto Logout 5 minutes

I log out, and when I log in, the vault opens immediately without using my touch ID.

**Comment by bcopeland** [comment]
I've redirected this internally so that it should land at the right people shortly.
