### ISSUE TITLE
GitHub issue/PR creation doesn't work while lastpass is enabled on Chrome

### ISSUE THREAD

**Issue by bhuga** [lastpass/lastpass-cli#218]
I'm not sure if this is the right place, but lastpass support (Boski) asked me to post here.

On Friday, the lastpass extension for Chrome for Mac was updated. On that day, we started to see problems on GitHub. If the lastpass extension is enabled, users cannot create new pull requests or issues. Every character typed in the new PR/issue form has a 15 second delay or so before it appears, so the form is basically unusable.

One of our engineers did a CPU trace on this. We see 15 seconds spent in this function:

![](https://cloud.githubusercontent.com/assets/671378/20072242/69cad74e-a4dc-11e6-8e12-b60695b45a54.png)

![](https://cloud.githubusercontent.com/assets/671378/20072239/6813348c-a4dc-11e6-9fb7-4f2970d9d86b.png)

We've been seeing this quite a bit so a number of our mutual customers are probably running in to it. We'd appreciate if you could take a look. If this is the wrong place to report this, can you please help me get to the right place to report bugs with the chrome extension?

**Comment by bcopeland** [comment]
Thanks, I've redirected this internally so it should land at the right people shortly.
