### ISSUE TITLE
Secure note field in Mac client does not scroll

### ISSUE THREAD

**Issue by mrthaman** [lastpass/lastpass-cli#219]
Version 3.17.0 (234) of the Mac client has a bug in the secure notes section.  The notes field does not scroll, so any note that is longer than the visible field is cut off and the the rest of the note is inaccessable.  I have tried scrolling down via mouse, keyboards, and trackpad gestures.  If you resize the LastPass window more of the note becomes visible, but you still cannot scroll to the bottom.

![screen_shot_2016-11-10_at_8_06_51_am](https://cloud.githubusercontent.com/assets/23214208/20179425/171e8d70-a724-11e6-876e-6a086f5d87e1.jpg)

**Comment by bcopeland** [comment]
This landed in the wrong place, I can't do much about it.  Redirected internally.
