### ISSUE TITLE
LASTPASS Customer support told me to pass the bug...apologies ;-)

### ISSUE THREAD

**Issue by madsecdev** [lastpass/lastpass-cli#221]
SUPPORT REQUEST #4624222 :  Problem : Chrome
WE ARE INVESTIGATING THIS SUPPORT REQUEST
2016-11-23 05:22
You	OK will do. FYI, tested a new user account with a new install of chrome and lastpass extension for chrome and reproduced the same results, so this rules out user specific or preferences set in the browser like disabling 3rd party cookies and limiting local store to a session etc. Also, no other extensions or background processes to interfere with your extension. I guess I'll just cut and paste our exchange if that's OK; will save me time :)

Thanks for your rapid response!
2016-11-23 04:53
Naveed	Apologies for the inconvenience. I can reproduce the issue and can confirm 'Restore General default' is not functioning correctly. Since this is a bug you will need to submit the issue directly to our developer's channel here https://github.com/LastPass/lastpass-cli/issues which allows them to work closely with the issue.
2016-11-22 23:08
You	Oh, forgot to add that I don't log in with google to sync chrome settings...
2016-11-22 23:07
You
LibrarayFi... (286.8 KB)
restore bu... (683 KB)	Great advise, but I went even further... Uninstalled chrome, removed ~/Library/Application Support/Google/Chrome and ~Library/Preferences/com.google.chrome.plist. Rebooted system in rescue, did a disk check (in case...), logged in to clean install of chrome with no extensions, added JUST lastpass w/o chaging default chrome preferences and had same issue. Again, got lastpass extension from chrome store as it's the first opion from the lastpass site when navigating with chrome and is the latest build. Can you replicate?
2016-11-22 22:17
Keno	Hello there, 

Thank you for contacting LastPass Support, we're happy to assist. 

We're sorry that you are experiencing this. To have this issue addressed, please do the following:
1. Remove the LastPass extension (https://support.google.com/chrome_webstore/answer/2664769?hl=en)
2. Remove your browser profile (https://support.google.com/chrome/answer/2390059?hl=en)
3. Restart Chrome then re-add the extension to Chrome using the Chrome Web Store (https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd).

After reinstalling the LastPass extension you can go ahead and re-add your browser profile afterwards: https://support.google.com/chrome/answer/142059?hl=en.

Let us know if you need further assistance. 

Best, 
Keno
2016-11-22 19:47
You
poach-phon... (118.2 KB)	Just some feedback: lastpass 4.1.33 on Chrome for OS X Sierra 10.12.1 is really buggy relative to earlier releases. Some minor bugs are spurious changes in icon color from RED to YELLOW (solved by clicking on the icon to restore to RED. Last accessed time/date stamps are off on some entries that are never used; this does not change with a new non-revertible MASTER PASSWORD and with Google 2-factor auth, nor with reiterating the PBKDF2 function and restricting mobile devices and reseting approved devices and re-registering them.

ONE QUESTION for you: I set PBKDF2 reinterations at 5,000 which does not slow down my mobile app. How high can I go before crashing a mobile phone such as the iPhone 7 or Galaxy 7? I was thinking 10,000 should be good with enough headroom without dissembling your app to infer the limits. Keep up the great work, support rules!

2016-11-22 09:11
You	When I access the last pass extension menu item>Preferences, Restore Defaults button does not work, either before or after saving a change. I installed the lastpass extension in Apple Safari and the Restore Defaults button works normally. Is this an issue with chrome? 

FYI, Am using latest version of OS X, Chrome, Safari and Lastpass chrome extension 4.1.33 and with Safari version 4.1.25. These whewre added via the add extension option within each browser.

Thanks!

**Comment by bcopeland** [comment]
Where the first line support got the idea that this project is the "developer's channel," I have no idea.  At some point I requested that lastpass-cli issues be reported on the public github rather than internally, but that seems to have been widely misunderstood.

I've forwarded this along to second line support in hopes it will get you better results and get it added to the internal bug tracker.
