### ISSUE TITLE
Build process no longer respects local directories for completions?

### ISSUE THREAD

**Issue by fortes** [lastpass/lastpass-cli#224]
Hi there, I've been using the following to install `lpass` into my home directory:

```bash
LOCAL_DIR="$HOME/.local"
make
# Install everything locally so we don't need sudo
COMPDIR="$LOCAL_DIR/completions.d" PREFIX="$LOCAL_DIR" BINDIR="$LOCAL_DIR/bin" \
  make install
```

It looks like the latest `cmake` based build breaks some of this. I see there is a `CMAKE_INSTALL_PREFIX` -- but the completion file seems to be hardcoded to `/usr/share/bash-completion/completions/lpass`. Is there something I'm missing here? (I actually didn't seem to get the `CMAKE_INSTALL_PREFIX` variable to work either, still tries to copy into `/usr/local/bin` -- I'm almost certainly missing something there)

Thanks again for the great tool!

**Comment by bcopeland** [comment]
The completion directory comes from pkg-config initially, but you can override it with a subsequent invocation of cmake:
```
cmake .
cmake -DCMAKE_INSTALL_PREFIX=~/my-lastpass -DBASH_COMPLETION_COMPLETIONSDIR=~/my-lastpass .
make && make install
```
You can also use ```ccmake .``` to reconfigure any cached settings with a little text-based gui.

**Comment by fortes** [comment]
Perfect, thanks!
