### ISSUE TITLE
New CMake build system doesn't work properly

### ISSUE THREAD

**Issue by eli-schwartz** [lastpass/lastpass-cli#227]
When running `make install install-doc`:

- DESTDIR is not respected for your custom targets (i.e. install-doc). Everything else is installed via the CMake install() macro which respects DESTDIR...
- In the doc and doc-man targets, `lpass.1.txt` is specified using `CMAKE_SOURCE_DIR` but in install-doc `lpass.1` isn't... which means this breaks (for the second time) when doing an out-of-tree build, which using cmake was **supposed** to give you for free. 😉 In fact, CMake strongly recommends out-of-tree builds.
...

Speaking of which, I am not sure I understand why the Makefile was deleted. It was a perfectly working, tested Makefile, that was removed in favor of using a newly-written formula for a Makefile preprocessor (thereby forcing an additional build dependency)... which you then got wrong.

This seems to be a simple enough project that you shouldn't really need a build system just to generate your Makefile (supported by the fact that you did well without one). I am curious as to the rationale. The commit logs seem to imply that CMake was added "because someone contributed it", and the Makefile was removed afterwards simply because.
Not that I feel strongly about it or anything (I have CMake installed for other things anyway), but I do feel kind of strongly about having a build system that does everything it is supposed to. :smile:

**Comment by eli-schwartz** [comment]
Incidentally, PkgConfig comes with its own pkg_get_variable that would be a lot easier/cleaner than re-implementing as pkg_check_variable...

**Comment by bcopeland** [comment]
Thanks!

**Comment by TheReptile** [comment]
On Linux Mint 18 (Ubuntu derrative) I get the following error with cmake:
`-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!`

**Comment by eli-schwartz** [comment]
@TheReptile, not relevant. ;)

Your problem is that CMake can't find "gcc" and friends in your PATH, which implies you don't have a compiler installed. *Do you*, in fact, have them installed?

**Comment by TheReptile** [comment]
@eli-schwartz Yes I have gcc installed, the previous versions of lpass-cli which used a normal makefile compiled just fine.

**Comment by eli-schwartz** [comment]
Well, it is still not the problem I raised, which relates to the CMakeLists.txt having flaws in its handling of the proper installation steps.

If CMake cannot find the CXX compiler, that implies a problem with CMake itself. Likely in your setup. Do you have "build-essential" installed? If yes, what is the output of `which c++`?

**Comment by TheReptile** [comment]
Thanks, installing "build-essential" solved the problem, maybe useful to add this to the list of dependencies?
