### ISSUE TITLE
Error: HTTP response code said error.

### ISSUE THREAD

**Issue by gmihalache** [lastpass/lastpass-cli#228]
The cli login fails completely and the error message is rather cryptic. I removed the brew installed build and installed it manually from the master branch here but there's no change.

osx ~/.lpass $ lpass login xxx@gmail.com
Error: HTTP response code said error.

osx ~/.lpass $ lpass login xxx@gmail.com
^CError: Unable to fetch iteration count. Check your internet connection and be sure your username is valid.

^ the second time i killed the connection attempt, i am not sure if that output is relevant

**Comment by gmihalache** [comment]
P.S. the ~/.lpass directory is empty, i cleared it's contents. No other files were created upon subsequent login attempts.

**Comment by bcopeland** [comment]
Are you still having this issue?  If so, it could be a problem with libcurl.  In any case the best way to get more information is to do this:
```
export LPASS_LOG_LEVEL=8
lpass login xxx@gmail.com
less ~/.lpass/lpass.log
```
*Note* please don't paste the full contents of the log file here, it could contain your session id etc.

**Comment by gmihalache** [comment]
Hey, it looks like it was a temporary server issue of some kind (i.e. maintenance, loss of connectivity, etc.). It resolved itself the next day and has been working fine ever since.


Thank you,

Gabriel Mihalache

“If everything seems under control, you're not going fast enough” Mario Andretti

**Comment by bcopeland** [comment]
Thanks, closing then.
