### ISSUE TITLE
lpass mv doesn't move?

### ISSUE THREAD

**Issue by zostay** [lastpass/lastpass-cli#233]
Maybe I'm missing something? It appears though that:

    lpass mv foo folder

creates a new account named "foo" in "folder" but the old account remains in place. Intuitively, `mv` means "move" but looking at the source, that does not appear to be the case. Am I missing something?

If not, could `lpass mv` be renamed to `lpass cp` and/or should `lpass mv` be changed to remove the previous account when `lpass mv` is performed.

**Comment by bcopeland** [comment]
On Thu, Dec 22, 2016 at 12:31:18PM -0800, Sterling Hanenkamp wrote:
> Maybe I'm missing something? It appears though that:
> 
>     lpass mv foo folder
> 
> creates a new account named "foo" in "folder" but the old account remains in
> place. Intuitively, `mv` means "move" but looking at the source, that does
> not appear to be the case. Am I missing something?

I'm not sure why the source code leads you to believe the old account
is left in place.

There are two cases:
 - move to/from shared folder, in which case the server is responsible
   for deleting the old record from the blob (involves reencryption with
   a different key, and this is the only case where there are actually
   two accounts)

 - move of an account into a regular folder: in this case the account is
   updated in-place

Which of these are we talking about?

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by zostay** [comment]
Nevermind, I can no longer reproduce my problem.
