### ISSUE TITLE
cannot compile 1.1.0 .  hard-coded paths?

### ISSUE THREAD

**Issue by hymie0** [lastpass/lastpass-cli#236]
I cannot compile the new version 1.1.0 , and I don't know `cmake` well enough to track down the problem.

Problem 1:

[  2%] Building C object CMakeFiles/lpass.dir/xml.c.o
/home/hymie/lastpass-cli.git/trunk/xml.c:40:27: fatal error: libxml/parser.h: No such file or directory

The file is right where it always has been, `/usr/local/include/libxml2/libxml/parser.h` .  But I cannot find any CFLAGS in any Makefile that I can add a `-I` option to.

Problem 2:

make[2]: *** No rule to make target '/usr/lib/libxml2.so', needed by 'lpass'.

That's not where libxml2.so is.  It's in `/usr/local/lib/libxml2.so` .  I don't know why it's looking in `/usr/lib`, but again, I can't find where to fix it.

**Comment by bcopeland** [comment]
On Tue, Jan 03, 2017 at 04:26:37PM -0800, hymie0 wrote:
> Problem 2:
> 
> make[2]: *** No rule to make target '/usr/lib/libxml2.so', needed by 'lpass'.
> 
> That's not where libxml2.so is.  It's in `/usr/local/lib/libxml2.so` .  I don't know why it's looking in `/usr/lib`, but again, I can't find where to fix it.

These paths come from pkg-config.  You can override by passing
the appropriate -D option to cmake or by running ccmake and specifying
it in the gui.  You can find the variable names by grepping CMakeCache.txt.

e.g:
```
cd build
cmake -DLIBXML2_INCLUDE_DIR=/tmp/include \
      -DLIBXML2_LIBRARIES=/tmp/libxml2.so ..
make
```

**Comment by hymie0** [comment]
Weird.  I erased and re-downloaded the source code, and it compiled perfectly.  I guess just doing an update-in-place from 1.0 to 1.1 left ... something behind that ... confused something...

Or user error.
