### ISSUE TITLE
sort is different with/without color

### ISSUE THREAD

**Issue by hymie0** [lastpass/lastpass-cli#240]
`lpass ls` shows my sites in alphabetical order, separated by folders, also in alphabetical order.

`lpass ls --color=never` shows all of my sites, but the folder name is mix-sorted in with the site names.

```
$ lpass ls
(none)
    A Employee Self-Service [id: 3477795049406206269]
    C Credit Card [id: 661873925094035941]
    E FSA 2016 [id: 1143257020019700849]
    M FSA 2016 [id: 3297855566084128639]
    P Bank [id: 4340077385227455955]
    Paypal [id: 1750485928675130706]
    Safe in basement [id: 3668343174742792957]
    T (car loan) [id: 369592957157878689]
    V 401K [id: 6751052423925157652]
KBR
    benefitenroll.com [id: 6424184541482513053]
    iPay (paystubs) [id: 7211524887071226285]

$ lpass ls --color=never
(none)/A Employee Self-Service [id: 3477795049406206269]
(none)/C Credit Card [id: 661873925094035941]
(none)/E FSA 2016 [id: 1143257020019700849]
KBR/benefitenroll.com [id: 6424184541482513053]
KBR/iPay (paystubs) [id: 7211524887071226285]
(none)/M FSA 2016 [id: 3297855566084128639]
(none)/P Bank [id: 4340077385227455955]
(none)/Paypal [id: 1750485928675130706]
(none)/Safe in basement [id: 3668343174742792957]
(none)/T (car loan) [id: 369592957157878689]
(none)/V 401K [id: 6751052423925157652]
```

**Comment by bcopeland** [comment]
This is intentional: --color=never invokes the pipe-output method and is single-line because people might want to script the output.

If you'd like a different output you can use the --format option, although there is no way to get the tree-style output that way.

**Comment by hymie0** [comment]
Single-line isn't the problem.  The concern is that my "KBR" folder is listed in the middle of my "(none)" folder, in the spot where a site that was named "(none)/KBR" would have appeared.

I would have expected to see all of my (none) sites together followed by my "KBR" folder sites, in the same order as the colored tree output.

**Comment by bcopeland** [comment]
Gotcha - care to try out topic-sort branch to see if it fixes for you?

**Comment by hymie0** [comment]
Yes, those changes fixed it.

**Comment by bcopeland** [comment]
Merged.
