### ISSUE TITLE
Enable pinentry-mac use in lastpass-cli

### ISSUE THREAD

**Issue by vinceatbluelabs** [lastpass/lastpass-cli#248]
Hi!

There's a version of pinentry for OS X which pops up a graphical window--it's called 'pinentry-mac'.  

This version is super handy for usage within tools which embed lastpass-cli - for instance, for long Ansible playbook runs where the lastpass credentials time out and require reauthentication halfway through the run to look up a secret.

`pinentry-mac` is available on homebrew, but there's no good way today to use it with lastpass CLI, as lastpass CLI calls `pinentry`, not `pinentry-mac`.

I could see a couple of approaches here--I think the one I'm thinking about right now would enable `brew install lastpass-cli --pinentry-mac` to work and use pinentry-mac, while leaving `brew install lastpass-cli --pinentry` to use the existing terminal-based pinentry.  

To make this happen, the CLI build would need to change to make the pinentry executable name a #define that could be overwritten as a Makefile argument.  

Would you be open to PRs in this direction?

**Comment by bcopeland** [comment]
On Wed, Jan 11, 2017 at 09:21:32AM -0800, vinceatbluelabs wrote:
> Hi!
> 
> There's a version of pinentry for OS X which pops up a graphical window--it's
> called 'pinentry-mac'.  

You can just uninstall pinentry and install pinentry-mac, and
that should do the right thing, right?

At least on my development mac I have brew-installed pinentry-mac and
/usr/local/bin/pinentry is symlinked to /usr/local/bin/pinentry.

**Comment by vinceatbluelabs** [comment]
Unfortunately, doesn't seem to be the case when I try:

```bash
$ brew uninstall pinentry-mac
Error: No such keg: /usr/local/Cellar/pinentry-mac
$ brew uninstall pinentry
Error: No such keg: /usr/local/Cellar/pinentry
$ ls -l /usr/local/bin/pinentry*
ls: /usr/local/bin/pinentry*: No such file or directory
$ brew install pinentry-mac
==> Downloading https://homebrew.bintray.com/bottles/pinentry-mac-0.9.4.el_capitan.b
Already downloaded: /Users/vincebroz/Library/Caches/Homebrew/pinentry-mac-0.9.4.el_c\
apitan.bottle.tar.gz
==> Pouring pinentry-mac-0.9.4.el_capitan.bottle.tar.gz
==> Caveats
You can now set this as your pinentry program like

~/.gnupg/gpg-agent.conf
    pinentry-program /usr/local/bin/pinentry-mac
==> Summary
🍺  /usr/local/Cellar/pinentry-mac/0.9.4: 10 files, 390.4K
$ ls -l /usr/local/bin/pinentry
ls: /usr/local/bin/pinentry: No such file or directory
$ ls -l /usr/local/bin/pinentry-mac
lrwxr-xr-x  1 vincebroz  wheel  45 Jan 11 15:19 /usr/local/bin/pinentry-mac -> ../Ce\
llar/pinentry-mac/0.9.4/bin/pinentry-mac
$
```

**Comment by bcopeland** [comment]
Hmm, I wonder if this is something that changed in brew or if I installed that symlink myself a while ago and forgot.  In any case, this should make it work:
```
ln -s /usr/local/bin/pinentry{-mac,}
```
I'm not sure if I want to make this configurable, build time or otherwise, when a symlink will do.

**Comment by vinceatbluelabs** [comment]
Yeah, that's how I'm doing it personally, was just looking for a cleaner way to roll that out to our other devs.  Thanks.

**Comment by vinceatbluelabs** [comment]
(and if you change your mind, happy to open a PR with my changes!)
