### ISSUE TITLE
The requested URL returned error: 503 Service Unavailable

### ISSUE THREAD

**Issue by pnikolaev31** [lastpass/lastpass-cli#250]
Hello,
I don't expect that this is a issue with the release. But when I try to log in, I see the following error in the lasptass.log:

<7> [1484571399.993503] Making request to https://lastpass.com/iterations.php
* About to connect() to lastpass.com port 443 (#0)
*   Trying 23.77.20.185...
* Connected to lastpass.com (23.77.20.185) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=lastpass.com,O="LogMeIn, Inc",OU=LastPass,STREET=320 Summer St Ste 100,L=Boston,ST=Massachusetts,C=US,incorporationState=Massachusetts,incorporationCountry=US,serialNumber=000873622,businessCategory=Private Organization
*       start date: Jun 13 16:58:09 2016 GMT
*       expire date: Jun 14 16:58:09 2018 GMT
*       common name: lastpass.com
*       issuer: CN=GlobalSign Extended Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE
> POST /iterations.php HTTP/1.1
User-Agent: LastPass-CLI/1.1.1
Host: lastpass.com
Accept: */*
Content-Length: 33
Content-Type: application/x-www-form-urlencoded

* upload completely sent off: 33 out of 33 bytes
* The requested URL returned error: 503 Service Unavailable
* Closing connection 0

Can we somehow understand more about this situation? The lastpass works normally with web browser (plugin) but the cli doesn't want to connect. Tried latest one release: [~]# lpass -v
LastPass CLI v1.1.1 also made sure that no firewall is blocking the connection.

Thank you.

**Comment by bcopeland** [comment]
On Mon, Jan 16, 2017 at 05:07:17AM -0800, pnikolaev31 wrote:
> Hello,
> Can we somehow understand more about this situation? The lastpass works normally with web browser (plugin) but the cli doesn't want to connect. Tried latest one release: [~]# lpass -v
> LastPass CLI v1.1.1 also made sure that no firewall is blocking the connection.

It depends on which datacenter you were hitting -- one of them was having
network issues this morning.  Meanwhile some of the other datacenters may
have been slower than normal due to increased load.

You can check @LastPassStatus on twitter for this kind of thing.

Also, use `lpass [ls/show] --sync=no ...` (if you have logged in before) in
order to use the program without contacting the server.

**Comment by bcopeland** [comment]
Closing as the server status is normal.
