### ISSUE TITLE
lpass config

### ISSUE THREAD

**Issue by hoto** [lastpass/lastpass-cli#255]
Where is lpass storing it's config and auth token?

I noticed that there is a `~/.config/lpass` directory but it's empty.

Is there a `~/.lpassrc` or something? 

I would add this to the documentation or readme.

**Comment by bcopeland** [comment]
On Tue, Jan 17, 2017 at 04:33:48AM -0800, Andrzej Rehmann wrote:
> Where is lpass storing it's config and auth token?
> 
> I noticed that there is a `~/.config/lpass` directory but it's empty.
> 
> Is there a `~/.lpassrc` or something? 
> 
> I would add this to the documentation or readme.

XDG_DATA_HOME defaults to ~/.local/share/ and XDG_CONFIG_HOME
defaults to ~/.config.   I'd take a patch that adds the defaults to
lpass.1.txt.  Here's what it already says:

Configuration
~~~~~~~~~~~~~
'lpass' stores configuration in the following locations, in descending
order of precedence:

* The directory '$LPASS_HOME', if set
* '$XDG_CONFIG_HOME/lpass', '$XDG_DATA_HOME/lpass', and
  '$XDG_RUNTIME_DIR/lpass' (or equivalent defaults), if at least
  '$XDG_RUNTIME_DIR' is set
* '$HOME/.lpass'

All configuration may be specified via environment variables. Alternatively, a
set of environment variable overrides may be specified in '$LPASS_HOME/env' in
the form of:

[verse]
VARIABLE1=VALUE1
VARIABLE2=VALUE2
...

**Comment by hoto** [comment]
got it, thanks @bcopeland
