### ISSUE TITLE
specifying note-type on OSX results in Segmentation fault: 11

### ISSUE THREAD

**Issue by chriso-u3d** [lastpass/lastpass-cli#258]
lpass CLI v1.1.1 installed via MacPorts on OS X 10.11.6

Attempts to add records with --note-type are resulting in segmentation faults.

$ lpass add --note-type=database TESTDB
Segmentation fault: 11

**Comment by bcopeland** [comment]
On Tue, Jan 17, 2017 at 02:53:20PM -0800, chriso-u3d wrote:
> lpass CLI v1.1.1 installed via MacPorts on OS X 10.11.6
> 
> Attempts to add records with --note-type are resulting in segmentation faults.
> 
> $ lpass add --note-type=database TESTDB
> Segmentation fault: 11


Can you try master branch?  I believe I fized this a couple of
days ago. (brew install --HEAD)

**Comment by chriso-u3d** [comment]
Thank you.  That did take care of that particular issue.
