### ISSUE TITLE
Error start lastpass-cli on ArchLinux

### ISSUE THREAD

**Issue by SpyderSC** [lastpass/lastpass-cli#259]
I receive this error when start lastpass-cli on ArchLinux

**cnf-lookup: error while loading shared libraries: libboost_system.so.1.62.0: cannot open shared object file: No such file or directory**

**Comment by bcopeland** [comment]
What's the output of `ldd lpass`?  lpass doesn't, by itself, use boost at all.

**Comment by nicoulaj** [comment]
That's usually because you updated boost and did not recompile `command-not-found`.
And if `command-not-found` kicks in, you're probably not calling the right command (`lpass`).

**Comment by bcopeland** [comment]
@nicoulaj 's answer sounds right, closing this.
