### ISSUE TITLE
offline access

### ISSUE THREAD

**Issue by hymie0** [lastpass/lastpass-cli#260]
This isn't an issue so much as a question; but as far as I know, I have no other way to contact you.
I'm not sure exactly what/how the "local cache" is used.
Is there access to my lpass info when (say) my internet connection is down?
Without internet access, `lpass ls` gives me an error "Error: Couldn't resolve host name."  I don't know what host name it's trying to resolve.
It looks like `lpass show -G -x --all .*` will download all of my info into a file I can encrypt, but that kinda defeats the purpose.

**Comment by bcopeland** [comment]
Use `--sync=no`.  See #31; but one slight addition to what I said there: you need to both login and download the blob once.  Running `lpass ls` once while online is enough to download the blob.
