### ISSUE TITLE
Search function?

### ISSUE THREAD

**Issue by luckman212** [lastpass/lastpass-cli#262]
I have thousands of entries saved between my personal and shared folders in LastPass.  Many share a common base name.  E.g. `"ebay - personal"` and `"ebay - work"`.  In order to find/filter these I have been using `grep` e.g.

    lpass ls | grep ebay

It seems very inefficient to pipe thousands of lines into grep just to retreive 2 records. Not to mention that the color output is lost.

Is there a way to search independently using only lpass? Or is this a planned feature?

**Comment by hymie0** [comment]
Not the "lpass ls" command, but the "lpass show" command has a -F option
that will search for an (exact) substring, and a -G option which will
search for a case-insensitive regex.

lpass show ebay

**Comment by lukehamburg** [comment]
Ah perfect. Thank you!  Not sure how I missed that in the man page.

**Comment by KhaimovMR** [comment]
Hi, guys.
Is there any plans to make `lpass show [-G|-F]` search by urls?
