### ISSUE TITLE
Problem building 1.1.2 with Homebrew

### ISSUE THREAD

**Issue by wesbland** [lastpass/lastpass-cli#264]
I just tried to update to the latest version via Homebrew and ran up against this problem:

> ==> Upgrading lastpass-cli --with-pinentry
==> Downloading https://github.com/lastpass/lastpass-cli/archive/v1.1.2.tar.gz
Already downloaded: /Users/wbland/Library/Caches/Homebrew/lastpass-cli-1.1.2.tar.gz
==> make PREFIX=/usr/local/Cellar/lastpass-cli/1.1.2 install
==> make MANDIR=/usr/local/Cellar/lastpass-cli/1.1.2/share/man install-doc
Last 15 lines from /Users/wbland/Library/Logs/Homebrew/lastpass-cli/02.make:
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/lastpass-cli-20170207-67777-1ra2q06/lastpass-cli-1.1.2/build
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C build install-doc
Scanning dependencies of target doc-man
[100%] Generating lpass.1
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/lastpass-cli-20170207-67777-1ra2q06/lastpass-cli-1.1.2/build/lpass.1.xml" returned non-zero exit status 5
make[4]: *** [lpass.1] Error 1
make[3]: *** [CMakeFiles/doc-man.dir/all] Error 2
make[2]: *** [CMakeFiles/install-doc.dir/rule] Error 2
make[1]: *** [install-doc] Error 2
make: *** [install-doc] Error 2
>
>READ THIS: http://docs.brew.sh/Troubleshooting.html

Here's the log file (with `.txt` extension for upload-ability): [02.make.txt](https://github.com/lastpass/lastpass-cli/files/758192/02.make.txt)

**Comment by bcopeland** [comment]
Hmm.... xsltproc failed with ```5: error in the stylesheet```.  However, I can't seem to reproduce this with my version of asciidoc.

Are  you able to install the bottled version by dropping the `--with-pinentry` part?  The `--with-pinentry` only makes the pinentry package a dependency; it doesn't change how the program is built at all.

**Comment by wesbland** [comment]
Looks like this was reported in homebrew-core: https://github.com/Homebrew/homebrew-core/issues/9740

I can confirm that this fixed the issue for me as well. Seems like the problem is not from this package, but from the homebrew recipe. However, they raise a good point on that issue that people might not want to install a 100MB package in order to build the docs.
