### ISSUE TITLE
lpass not syncing

### ISSUE THREAD

**Issue by Kiemes** [lastpass/lastpass-cli#265]
lpass upload queue is hanging forever. sync=now does not fail.
Trying to edit or add has no effect on the server side.

I am working with LastPass CLI v1.1.2. on OSX 10.12.3

Now sure if this [bug](https://github.com/lastpass/lastpass-cli/issues/101) was fixed too 'optimistically', of if we talk about regression.

**Comment by bcopeland** [comment]
On Fri, Feb 10, 2017 at 05:22:24AM -0800, Tom Kiemes wrote:
> lpass upload queue is hanging forever. sync=now does not fail.
> Trying to edit or add has no effect on the server side.
> 
> I am working with LastPass CLI v1.1.2. on OSX 10.12.3
> 
> Now sure if this [bug](https://github.com/lastpass/lastpass-cli/issues/101) was fixed too 'optimistically', of if we talk about regression.

Best thing to do is kill the agent and uploader processes, then set
LPASS_LOG_LEVEL=8 and try again.  This should give an idea what is going
on in the requests to the server.  The file will end up in ~/.lpass/lpass.log
or ~/.local/share/lpass/lpass.log.

Do NOT post these logs though, it will contain your session ids and other
sensitive info.

**Comment by mpontillo** [comment]
I just hit this and saw a `400 Bad Request` error in the log, with no further detail

Looking at the `.lock` file in the `upload-queue`, I figured out that it was because I was trying to do a scripted sync with a file that was too large. (~64k) If I believe my Google search that found the FAQ, lastpass will only store secure notes up to ~45k in size.

**Comment by Kiemes** [comment]
For us it sometimes worked with the same content. So size was probably not the reason.

We now always delete the upload-queue and try again.

Still I think this is a bug. When using `sync=now`, the command should be synchronously made and it should fail with exit code >0.

**Comment by bcopeland** [comment]
On Tue, Mar 28, 2017 at 04:27:13AM -0700, Tom Kiemes wrote:
> For us it sometimes worked with the same content. So size was probably not the reason.
> 
> We now always delete the upload-queue and try again.
> 
> Still I think this is a bug. When using `sync=now`, the command should be synchronously made and it should fail with exit code >0.

I'll accept a patch for that.

**Comment by Laharah** [comment]
I'm running into this problem as well.

I'm running LastPass CLI v1.3.2 on Linux Debian 3.16.56-1+deb8u1 (2018-05-08)

When I run any edit and sync, either through `lpass rm [ID] --sync=now` or by running `lpass rm [ID]; lpass sync` changes only persist in the cache. The chrome extension shows no changes, and all changes are reverted by a `lpass logout; lpass login` 

I tried changing the log level by running `export LPASS_LOG_LEVEL=8` however the log seems pretty useless, I only see successfully calls to login_check.php and the occasional messages `UQ: starting queue run`. No other upload queue messages are written. I assume this means that the upload queue is hanging, but I can't find a way to check. I can see that the upload-queue folder has several entries.

**Comment by Laharah** [comment]
I can confirm that syncing does work on the same network on an OSX Laptop though.

**Comment by msbit** [comment]
Okay, so I've had the same thing occur on my machine:

```
$ lpass -v
LastPass CLI v1.3.2
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

and I've found the following from strace (specific to the upload-queue):

```
[pid 18725] set_robust_list(0x7fe83287fa20, 24 <unfinished ...>
[pid 18725] <... set_robust_list resumed> ) = 0
[pid 18725] open("/dev/null", O_RDONLY <unfinished ...>
[pid 18725] <... open resumed> )        = 4
[pid 18725] dup2(4, 0 <unfinished ...>
[pid 18725] <... dup2 resumed> )        = 0
[pid 18725] dup2(4, 1 <unfinished ...>
[pid 18725] <... dup2 resumed> )        = 1
[pid 18725] dup2(4, 2 <unfinished ...>
[pid 18725] <... dup2 resumed> )        = 2
[pid 18725] close(4 <unfinished ...>
[pid 18725] <... close resumed> )       = 0
[pid 18725] close(4 <unfinished ...>
[pid 18725] <... close resumed> )       = -1 EBADF (Bad file descriptor)
[pid 18725] setsid( <unfinished ...>
[pid 18725] <... setsid resumed> )      = 18725
[pid 18725] chdir("/")                  = 0
[pid 18725] prctl(PR_SET_NAME, "lpass [upload qu") = 0
[pid 18725] rt_sigaction(SIGHUP, {0x41a5d0, [HUP], SA_RESTORER|SA_RESTART, 0x7fe8316164b0}, {SIG_DFL, [], 0}, 8) = 0
[pid 18725] rt_sigaction(SIGINT, {0x41a5d0, [INT], SA_RESTORER|SA_RESTART, 0x7fe8316164b0}, {SIG_DFL, [], 0}, 8) = 0
[pid 18725] rt_sigaction(SIGQUIT, {0x41a5d0, [QUIT], SA_RESTORER|SA_RESTART, 0x7fe8316164b0}, {SIG_DFL, [], 0}, 8) = 0
[pid 18725] rt_sigaction(SIGTERM, {0x41a5d0, [TERM], SA_RESTORER|SA_RESTART, 0x7fe8316164b0}, {SIG_DFL, [], 0}, 8) = 0
[pid 18725] rt_sigaction(SIGALRM, {0x41a5d0, [ALRM], SA_RESTORER|SA_RESTART, 0x7fe8316164b0}, {SIG_DFL, [], 0}, 8) = 0
[pid 18725] open("/usr/lib/ssl/openssl.cnf", O_RDONLY) = 4
[pid 18725] fstat(4, {st_mode=S_IFREG|0644, st_size=10835, ...}) = 0
[pid 18725] read(4, "#\n# OpenSSL example configuratio"..., 4096) = 4096
[pid 18725] read(4, "Netscape crash on BMPStrings or "..., 4096) = 4096
[pid 18725] read(4, " this to avoid interpreting an e"..., 4096) = 2643
[pid 18725] read(4, "", 4096)           = 0
[pid 18725] close(4)                    = 0
[pid 18725] stat("/home/tom/.local/share/lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
[pid 18725] open("/home/tom/.local/share/lpass/upload-queue", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
[pid 18725] fstat(4, {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
[pid 18725] brk(0xe4b000)               = 0xe4b000
[pid 18725] getdents(4, /* 3 entries */, 32768) = 88
[pid 18725] getdents(4, /* 0 entries */, 32768) = 0
[pid 18725] brk(0xe43000)               = 0xe43000
[pid 18725] close(4)                    = 0
[pid 18725] stat("/run/user/1000/lpass", {st_mode=S_IFDIR|0700, st_size=80, ...}) = 0
[pid 18725] stat("/run/user/1000/lpass/upload-queue/15394801540000.lock", 0x7fffaf3eeec0) = -1 ENOENT (No such file or directory)
[pid 18725] open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 4
[pid 18725] fstat(4, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
[pid 18725] poll([{fd=4, events=POLLIN}], 1, 10) = 1 ([{fd=4, revents=POLLIN}])
[pid 18725] read(4, "]oLw\225)@\231\327\32\n\274Lyh\231\233\347{XO\334\v\177\240\376\365\363K@\211\240", 32) = 32
[pid 18725] close(4)                    = 0
[pid 18725] getuid()                    = 1000
[pid 18725] stat("/run/user/1000/lpass", {st_mode=S_IFDIR|0700, st_size=80, ...}) = 0
[pid 18725] open("/run/user/1000/lpass/upload-queue/15394801540000.lock.FmwoMc", O_RDWR|O_CREAT|O_EXCL, 0600) = -1 ENOENT (No such file or directory)
[pid 18725] ioctl(2, TCGETS, 0x7fffaf3edbd0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 18725] write(2, "Error", 5)        = -1 EBADF (Bad file descriptor)
[pid 18725] write(2, ": ", 2)           = -1 EBADF (Bad file descriptor)
[pid 18725] write(2, "No such file or directory", 25) = -1 EBADF (Bad file descriptor)
[pid 18725] write(2, ": mkstemp(/run/user/1000/lpass/u"..., 72) = -1 EBADF (Bad file descriptor)
[pid 18725] close(3)                    = 0
[pid 18725] exit_group(1)               = ?
[pid 18725] +++ exited with 1 +++
```

Looking through the code, it looks like the upload queue process dies at:

https://github.com/lastpass/lastpass-cli/blob/df182dd7c04715f1b18f5ff3a8074e198fc1d06c/config.c#L255

called from:

https://github.com/lastpass/lastpass-cli/blob/df182dd7c04715f1b18f5ff3a8074e198fc1d06c/upload-queue.c#L224

when attempting to create the lock file.

The issue is that the directory it wants to create the file in doesn't actually exist, as the upload queue files are stored in `~/.local/share/lpass/upload-queue`, but the queue process is looking in `/run/user/1000/lpass/upload-queue` (i.e. under `XDG_RUNTIME_DIR`). On my machine:

```
$ find ~/.local/share/lpass -type d
/home/tom/.local/share/lpass
/home/tom/.local/share/lpass/upload-queue
$ find /run/user/1000/lpass -type d
/run/user/1000/lpass
```

I'd also suggest that https://github.com/lastpass/lastpass-cli/issues/450 and https://github.com/lastpass/lastpass-cli/issues/326 might be duplicates of this issue.

**Comment by msbit** [comment]
As a work-around, I was able to add:

`export LPASS_HOME="${HOME}/.local/share/lpass"`

to my `.profile` file, to force lpass to put lock and pid files under that directory instead of `/run/user/1000/lpass`.

**Comment by gerhard** [comment]
I was having a similar issue with LastPass CLI v1.3.1 running on macOS v10.14.2

There were 2k+ items in the upload queue:
```
ls ~/.lpass/upload-queue | wc -l
2270
```

Killing the agent & upload queue processes (`pkill lastpass`) and running `LPASS_LOG_LEVEL=8 lpass sync` showed a ~14% failure rate for `POST /loglogin.php` requests

```
ag -c "502 Bad Gateway" /Users/gerhard/.lpass/lpass.log
46

ag -c "POST /loglogin.php" /Users/gerhard/.lpass/lpass.log
328

ag -m 1 -B 10 "502 Bad Gateway" /Users/gerhard/.lpass/lpass.log
ERR: Too many matches in /Users/gerhard/.lpass/lpass.log. Skipping the rest of this file.
172-* Server certificate: GlobalSign
173-> POST /loglogin.php HTTP/1.1
174-Host: lastpass.com
175-User-Agent: LastPass-CLI/1.3.1
176-Accept: */*
177-Cookie: PHPSESSID=xxx
178-Content-Length: 58
179-Content-Type: application/x-www-form-urlencoded
180-
181-* upload completely sent off: 58 out of 58 bytes
182:* The requested URL returned error: 502 Bad Gateway
```

I've deleted `~/.lpass`, logged in again and now `lpass sync` works.
