### ISSUE TITLE
CLI does not appear to nicely handle deeply nested folders. 

### ISSUE THREAD

**Issue by nneul** [lastpass/lastpass-cli#266]
It appears to get confused about folder vs. name when the folder structure is more than a single level deep.

**Comment by nneul** [comment]
Example:

`Shared-00. Toplevel /01. Sublevel1/01. Sublevel2/NoteName`

**Comment by bcopeland** [comment]
On Sun, Feb 12, 2017 at 03:07:22PM -0800, Nathan Neulinger wrote:
> Example:
> 
> `Shared-00. Toplevel /01. Sublevel1/01. Sublevel2/NoteName`

You must use backslashes after the first level.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by nneul** [comment]
I tried a few combinations with backslashes, and it didn't seem to help. I'll give it a try again - maybe I didn't have all of them.

**Comment by nneul** [comment]
Ah, I see... It's backslashes on all but the last level. So:

`Share/_path with subdirs as backslashes_/NoteName`

**Comment by Fatal-Halt** [comment]
Apologies, but could you elaborate on your example and how you got it to work?

**Comment by nneul** [comment]
Going from memory here but:

`Shared-00. Toplevel /01. Sublevel1/01. Sublevel2/NoteName`

became:

`Shared-00. Toplevel /01. Sublevel1\01. Sublevel2/NoteName`

**Comment by nneul** [comment]
Basically - first and last slash stay as is - everything in the intermediate path turns into a backslash.

**Comment by Fatal-Halt** [comment]
Cheers - that works - sort of!
