### ISSUE TITLE
FR: A minimalist server to go with this CLI

### ISSUE THREAD

**Issue by nneul** [lastpass/lastpass-cli#267]
I realize that this isn't something you'd want to put much of any resource into, but it would be very useful to have a minimalist server to go along with this CLI for local/internal automation - as an alternative for example to using Hashicorp's vault.

**Comment by bcopeland** [comment]
I don't think we will take this on.  If you would like some inspiration, the tests/ directory has a mock server that cans some of the responses.  Of course, using that as a basis for an actual server is iffy, but it gives an example of how the vault is delivered (basically the same format as ~/.lpass/blob).
