### ISSUE TITLE
Notes aren't saved when using lpass add. 

### ISSUE THREAD

**Issue by terw-dan** [lastpass/lastpass-cli#269]
I'm currently figuring out a way to create an entry from the command line that creates a password entry, with the possibility of adding a note. 
Currently I'm using `(echo "Username:Danny"; echo "URL:http://example.com"; echo "Password:1234") | ./lpass add testentry --non-interactive` to add an entry. This works as it will show up in my vault. 

The problem I run into is that adding a note doesn't work. 
`(echo "Username:Danny"; echo "URL:http://example.com"; echo "Password:1234"; echo "Note:this is a note" ) | ./lpass add testentry --non-interactive`  adds all fields, but leaves the note field empty. 
I've tried adding a notetype but this doesn't add a note. So I have no clue why the note isn't added.

Adding a note after an entry is created would be a possibility as well, but I cannot figure out how to edit a specific entry, or if edit always takes the last entry that was added. 

Any ideas how this can be fixed?

Currently running 1.1.2

**Comment by bcopeland** [comment]
When you do `lpass edit testentry` you will see the format you need to follow, and for notes it says:
```
Notes:     # Add notes below this line
```
So you need another newline before your note, and it is "Notes" (plural) not "Note."

Try this:
```printf "Username:Danny\nURL:http://example.com\nPassword:1234\nNotes:\nthis is a note." | lpass add testentry --non-interactive```

**Comment by terw-dan** [comment]
@bcopeland Thanks a bunch for your quick reply. This does indeed work to add 1 single entry with all data at once.
