### ISSUE TITLE
How to pass the login credentials properly?

### ISSUE THREAD

**Issue by terw-dan** [lastpass/lastpass-cli#270]
I'm trying to login from the command line, by automatically passing the credentials, so I don't have a password prompt, but can parse it right away. 
In the documentation it states:
` The login subcommand will initialize a local cache and configuration folder, then attempt to authenticate itself with the LastPass servers, using the provided command line credentials` 

So my guess is I should be able to pass the password in the command line, but any way I try to, it still prompts for a password, or returns the usage of the ./lpass login command. 

Is there any documentation on how this can be done?

**Comment by ElijahLynn** [comment]
Same here. I would like to the option to basically "remember password" as the Chrome extension and Android app have.

**Comment by RobertKaldenbach** [comment]
Have you looked into using LPASS_ASKPASS variable and then piping in the password like this:
echo 'PASSWORD' | lpass login --trust USERNAME

LPASS_ASKPASS documentation:
https://github.com/lastpass/lastpass-cli/pull/123/commits/fc70080c8a54687d985aa6da2a75966a3f24679e

**Comment by bcopeland** [comment]
There are several options, as the documentation points out, of varying levels of security, both in terms of the MPW prompt (pinentry, LPASS_ASKPASS), and the key itself (agent, `login --plaintext_key`).

Due to the insecurity of the solution I will not be adding a command-line option to supply the password.

If you don't care about security, a rough-and-ready option (again, not recommended) is simply:
```
export LPASS_DISABLE_PINENTRY=1
cat my_password.txt | lpass ls
```

**Comment by ElijahLynn** [comment]
Thanks, the `--trust` option is a good improvement for me. I couldn't read the docs before but finally got the manpage installed.

**Comment by bcopeland** [comment]
Note, lpass.1.txt is markdown text which you should be able to read in any text editor, and there is also http://lastpass.github.io/lastpass-cli/lpass.1.html (the html version of that).

**Comment by bcopeland** [comment]
I think we already have a solution for the various use cases, so I will close this one.

**Comment by terw-dan** [comment]
Thanks for the information, it seems to be working in my case, so thanks a lot.

**Comment by dotandpixel** [comment]
I've just installed lpass, and haven't been able to login. When I enter "lpass login --trust USERNAME"  (replacing USERNAME for my email), and hit return, nothing happens. I just get the Usage: tips.

What am I not doing right? Thanks for any help 

I have LastPass CLI v0.3.0 installed.

**Comment by bcopeland** [comment]
You need to upgrade from v0.3.0 to something more recent.

Current version is v1.2.2.

On Sat, Nov 11, 2017 at 06:38:32AM +0000, Andrew Peel wrote:
> I've just installed lpass, and haven't been able to login. When I enter "lpass login --trust USERNAME"  (replacing USERNAME for my email), and hit return, nothing happens. I just get the Usage: tips.
> 
> What am I not doing right? Thanks for any help 
> 
> I have LastPass CLI v0.3.0 installed.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/lastpass/lastpass-cli/issues/270#issuecomment-343644832

-- 
Bob Copeland %% https://bobcopeland.com/

**Comment by zonender** [comment]
To run from a bash script:

$ sudo bash ./myscript.sh "my-lastpass-master-password"

Please note that on lastpass you must have already created a secret note named: aws-access-key and contains only the aws access key for example.

====== beginning of bash script: myscript.sh==========
#!/bin/bash

yum -y install lastpass-cli

MY_LASTPASS_MASTER_PASSWORD=$1

export LPASS_DISABLE_PINENTRY=1

echo MY_LASTPASS_MASTER_PASSWORD | lpass login user@hotmail.com

############## get secrets from lastpass ##############

AWS_SECRET_KEY_ID=$(echo $1 | lpass show --username user@hotmail.com --notes aws-access-key)

AWS_ACCESS_KEY_ID=$(echo $1 | lpass show --username user@hotmail.com --notes aws-secret-key)
====== end of bash script ==========

Works like a charm!!!

I really don't like passing my master password as a parameter to the script, can anyone please make a better alternative to passing the master password as a parameter, thanks.

**Comment by alexkuc** [comment]
In addition to @zonender , I have also created my own script to deal with entries which require master password re-entry (either too many entries or need to have a fully automated script). Please find those scripts in [my repository](https://github.com/alexkuc/lpass-scripts) which a basic explanation of them and how they work. As mentioned in my README.md, I am not a security expert, though I have tried to take into account as many security considerations as possible. Any feedback/critique/PR is welcome!

**Comment by CodeToOvercome** [comment]
Not sure where  to ask this silly question of mine.

**Problems logging into lastpass using bash script**

As mentioned in the title, i am able to login into lastpass via CLI , however when i try the same in a bash script, it simply fails to recognize my password. I am not sure as to what i could be doing wrong

Here's my simply little code



```
#!/bin/bash

lpass login --trust username@domain.com

keyDetails=`lpass show siteid --password`

echo $keyDetails
```

**Comment by alexkuc** [comment]
@CodeToOvercome Check out my working example [here](https://github.com/alexkuc/lpass-scripts/blob/master/lpass-show.sh). It pretty much accomplishes what you are trying to do. Please note that it is an interactive bash script but with some trivial modifications, you can make it fully autonomous.
