### ISSUE TITLE
SSN template has two Name fields

### ISSUE THREAD

**Issue by LK4D4** [lastpass/lastpass-cli#273]
```
lpass add --note-type=ssn personal/ssn
Name: personal/ssn
NoteType: Social Security
Name:
Number: 666-66-666
Notes:
```
In show it looks like:
```
personal/ssn [id: 2072606659204944245]
Name:
Number: 666-66-666
NoteType: Social Security
```
Name is always empty regardless of value I enter in add or edit.
Thanks!

**Comment by bcopeland** [comment]
I think this was fixed in 8322ffe1b7f5a4517ae268a105ad7e97137d591b.  

If you enter it in the second "Name", it should stick, let me know if it's still broken in the latest release, and how to reproduce.

I just added a test to the repo (test_add_ssn_name) which seems to work OK.

**Comment by LK4D4** [comment]
@bcopeland thanks, will check new version now.

**Comment by LK4D4** [comment]
Yup, works like a charm.
Thanks!
