### ISSUE TITLE
Password Reprompt enabled by default on items when moving

### ISSUE THREAD

**Issue by elmoke** [lastpass/lastpass-cli#274]
I importing a number of items from another system which have been converted into the LastPass CSV format.  The import succeeds and the "Reprompt for Authentication" is disabled.
However when using the lpass mv command to a shared folder that option changes to enabled.
This is not as expected and I would like to know how to prevent this form happening and revert it.

**Comment by bcopeland** [comment]
There are two aspects to this:
 * server was improperly interpreting pwprotect value when updated through api; this has been changed on the server, so this particular issue should not trigger going forward even without recompiling lastpass-cli
 * there's no way to see or edit reprompt from cli, so if you got bit by this, it's not easy to fix

For the latter, I pushed this commit today (read commit log for howto):
https://github.com/lastpass/lastpass-cli/commit/f96885f6ad901844579ff73f9e2d2098a6f88443

**Comment by elmoke** [comment]
@bcopeland thanks for the quick turn around. However I tried the new CLI and piped echo but it does not seem to alter the item. Does it only work for a site or would it also work for (server) notes.
