### ISSUE TITLE
Toggle for "Require Password Reprompt" flag?

### ISSUE THREAD

**Issue by jbirdkerr** [lastpass/lastpass-cli#277]
We currently use the LastPass command line utility, lpass, to automatically add credentials for customer instances into appropriate share folders for various departments around the company.

The site records that are created have the advanced option "Require Password Reprompt" enabled by default. Is there a way to have this option disabled by default when we create the new credential set?

**Comment by bcopeland** [comment]
How are you creating them?  I made a change (on the server side) just yesterday to address this problem, is it still happening?

**Comment by bcopeland** [comment]
I think this is fixed, please reopen if not.
