### ISSUE TITLE
Feedback mechanism for too many chars in 'Notes' field

### ISSUE THREAD

**Issue by deniseyu** [lastpass/lastpass-cli#278]
We are trying to use 'Notes' as a workaround for not being able to add attachments at the moment. The Lastpass web interface displays an error message when you try to save a site or secure note with more than 45000 chars in the 'Notes' section.

Would it be possible to add some feedback mechanism if over 45000 chars are in the 'Notes' field during `lpass add`? The current behaviour is that `lpass sync` will hang indefinitely, but locally, `lpass add` runs and the entry shows up in `lpass list`.

**Comment by bcopeland** [comment]
Thanks for the report!
