### ISSUE TITLE
Creating a new entry results in an entry with id: 0

### ISSUE THREAD

**Issue by terw-dan** [lastpass/lastpass-cli#279]
When using `lpass add` to add an entry, all entries get the id: 0 (I have now multiple entries with that ID). 

This used to work, but somehow creating a new entry doesn't seem to work. The problem is that these entries cannot be moved, that results in an error the shared folder cannot be found. 

I try to create a shell script that can add entries based on a form, this way I managed to add some entries, but now it is no longer working. If I do it manually, it results in the same problem. 

What can be the cause of this? I cannot find anything related to entries created without an ID.

**Comment by RobertKaldenbach** [comment]
Sounds like the cli isn't pushing the site to your vault.  From my experience the id will show 0 via the cli until your site is added to your vault.  If you run lpass sync does it update?  Also if you log into your account via lastpass.com do you see the site you are trying to add there?  You could also check your .lpass/upload-queue folder and see if you have anything waiting to be pushed to the vault.

**Comment by terw-dan** [comment]
The entries where indeed in the upload-queue directory. The thing is I ran `lpass sync` but it didn't change anything. If I run `lpass sync now` it does work. 
I'm still baffled why it worked before without having to sync manually and now it doesn't. But if this works i'll incorporate this in my script to make sure we do it in the proper way. 

Thanks @RobertKaldenbach for the explanation :)

Since this seems to be solved, I'll close this.

**Comment by mbigras** [comment]
This is still an issue for me, I'm not sure how to get `lpass` to sync.
My id's are all 0 and I'm not seeing any of these entries in my LastPass Vault online.
I installed this tool with Homebrew.


```
$ lpass show flapjacks
flapjacks [id: 0]
Notes: hello world

$ lpass show flapjacks2
flapjacks2 [id: 0]
Notes: hello world again?

$ lpass show flapjacks3
flapjacks3 [id: 0]
Password: hello world?
Notes: hello world again?

$ lpass show flapjacks4
flapjacks4 [id: 0]
Username: someone
Password: hello world?
URL: cats.com
Notes: some notes?

$ lpass sync now
$ lpass show flapjacks4
flapjacks4 [id: 0]
Username: someone
Password: hello world?
URL: cats.com
Notes: some notes?

$ lpass --version
LastPass CLI v1.2.2
$ which lpass
/usr/local/bin/lpass
$ brew list --info lastpass-cli
/usr/local/Cellar/lastpass-cli/1.2.2/bin/lpass
/usr/local/Cellar/lastpass-cli/1.2.2/share/man/man1/lpass.1
```

**Comment by perlun** [comment]
I am still seeing this issue (on Debian GNU/Linux). The entries in question are never properly uploaded, regardless of whether I use `lpass sync now` or add `--sync=now` when adding the entries.

@terw-dan or anyone else with access, please reopen this issue so we can continue debugging it.
