### ISSUE TITLE
Unable to log into CLI possible firewall block?

### ISSUE THREAD

**Issue by RobertKaldenbach** [lastpass/lastpass-cli#280]
My script has suddenly stopped being able to log into the cli and I want to eliminate the possibility that it's being blocked by your servers.  I emailed copeland@lastpass.com but I am not sure if you would prefer for me to use a different email.
Thanks!

**Comment by bcopeland** [comment]
On Mon, Mar 06, 2017 at 07:26:53AM -0800, Robert Kaldenbach wrote:
> My script has suddenly stopped being able to log into the cli and I want to eliminate the possibility that it's being blocked by your servers.  I emailed copeland@lastpass.com but I am not sure if you would prefer for me to use a different email.
> Thanks!

I replied there, thanks.

**Comment by RobertKaldenbach** [comment]
Resolved!
