### ISSUE TITLE
Segfault when listing usernames

### ISSUE THREAD

**Issue by Mange** [lastpass/lastpass-cli#286]
Hi,

I get a segfault when I try to list containing usernames and piping it to somewhere. How can I help you debug this?

```bash
# this works
lpass ls --format "%au"

# this segfaults
lpass ls --format "%au" | cat
```

I suspect that this has to do with the implicit indentation that I get when I don't pipe somewhere. How can I tell what it crashes on?

```
14:58:17 ~ › lpass ls --format "%au" | cat
zsh: segmentation fault (core dumped)  lpass ls --format "%au" | 
zsh: done                              cat
```

**Comment by kyleburton** [comment]
@Mange #283 and this may be the same issue.  I have an active PR open to fix #283 - can you test that branch and see if it resolves your issue?

**Comment by bcopeland** [comment]
@Mange I pushed both @kyleburton's change plus another one that was needed here to master; please retest.

**Comment by Mange** [comment]
Yes, that fixed it! Thank you. :+1:
