### ISSUE TITLE
lpass generate looking for unique name?

### ISSUE THREAD

**Issue by Kgirthofer** [lastpass/lastpass-cli#290]
I'm trying to generate passwords for multiple items with the same name but different usernames. It works fine as we already have many like that - but when I try to import them via CLI I get this 
$:> lpass generate --username=kgirthofer-test --url=stg-pie-cmos.us-east-1.rds.amazonaws.com stg-pie-cmos 20
Error: Multiple matches found for 'stg-pie-cmos'. You must specify an ID instead of a name.

Doc lists "{NAME|UNIQUEID} " so a non-unique name should be ok
Thanks

**Comment by Kgirthofer** [comment]
I've been able to drop this error by generating a new item - logging out - logging back in and attempting sync.
If I just try to sync - it'll hang. Don't know what's going on - seems to work find from macos box

**Comment by bcopeland** [comment]
I don't understand the use-case; name in this instance refers to the name of the account, which can be different from username and url and really has no meaning other than a label for you.  IOW, to avoid this, all you have to do is tack some sequence number onto the end of `stg-pie-cmos` (e.g. `stg-pie-cmos-001`, `-002`, etc).  The error you get is because there's no way to refer to an unsynced account other than by the account name -- it will have an id of 0 until saved on the server.

**Comment by Kgirthofer** [comment]
@bcopeland thanks for the comment - after looking into it you're correct it looks like nothing is getting synced to lastpass. even if I use --sync now

I checked into the queue I'm not generating a ton of entries there's around 4 - 6. Not sure what's stopping the queue from syncing. 

lpass sync is also not working unless I logout and back in. Ive tried both in amazon linux and centos 7.

Here's my process in order

lpass login - works
lpass sync - works
lpass generate - adds to upload-queue - doesn't sync.
lpass sync - hangs/eventually fails
lpass logout - works
lpass login - works
lpass sync - works and syncs the previous data.

is there someway I can view logs of what's happening?

**Comment by bcopeland** [comment]
On Thu, Mar 23, 2017 at 07:25:23AM -0700, Karl Girthofer wrote:
> is there someway I can view logs of what's happening? 

Yep, kill the agent (if running), set LPASS_LOG_LEVEL=8 in the environment,
and retry sync.

The logfile will be saved in ~/.lpass/lpass.log or ~/.local/share/lpass/.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by Kgirthofer** [comment]
@bcopeland just set that in a brand new centos 7 environment - installed lastpass cli and then tried again. it failed  and no log files were generated in either location. I also monitored any out going traffic on the box and the process never attempted to reach out externally 
sudo netstat -nputwc
here's the strace on what's being attempted 
amazon linux 
    open("/home/ec2-user/.lpass/uploader.pid", O_RDONLY) = 3
    readlink("/proc/8864/exe", "/usr/bin/lpass", 4096) = 14 
    readlink("/proc/21830/exe", "/usr/bin/lpass", 4096) = 14
    stat("/home/ec2-user/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/ec2-user/.lpass/uploader.pid", O_RDONLY) = 3
    readlink("/proc/8864/exe", "/usr/bin/lpass", 4096) = 14
    readlink("/proc/21830/exe", "/usr/bin/lpass", 4096) = 14
    stat("/home/ec2-user/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/ec2-user/.lpass/uploader.pid", O_RDONLY) = 3
    readlink("/proc/8864/exe", "/usr/bin/lpass", 4096) = 14
    readlink("/proc/21830/exe", "/usr/bin/lpass", 4096) = 14

This happens over and over and over
and in centos 7 it finishes like it completed - but the file stays in the queue
    access("/etc/system-fips", F_OK)        = -1 ENOENT (No such file or directory)
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/env", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/alias.sync", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    stat("/home/centos/.lpass/plaintext_key", 0x7fff8319f370) = -1 ENOENT (No such file or directory)
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/session_uid", O_RDONLY) = 3
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/session_sessionid", O_RDONLY) = 3
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/session_token", O_RDONLY) = 3
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/session_privatekey", O_RDONLY) = 3
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/uploader.pid", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/uploader.pid", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/uploader.pid.tQP9uU", O_RDWR|O_CREAT|O_EXCL, 0600) = 3
    rename("/home/centos/.lpass/uploader.pid.tQP9uU", "/home/centos/.lpass/uploader.pid") = 0
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/uploader.pid", O_RDONLY) = 3
    readlink("/proc/9312/exe", "/usr/bin/lpass", 4096) = 14
    readlink("/proc/9311/exe", "/usr/bin/lpass", 4096) = 14
    --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=9312, si_status=0, si_utime=0, si_stime=0} ---
    stat("/home/centos/.lpass", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    open("/home/centos/.lpass/uploader.pid", O_RDONLY) = -1 ENOENT (No such file or directory)



FWIW this is in a brand new server - in a brand new VPC with all ports open and a direct external IP to the web.

**Comment by Kgirthofer** [comment]
Here's my console output from history of every step I made from creation of the box to failure
[centos@ip-172-31-38-247 .lpass]$ history
    1  netstat -nputw
    2  sudo netstat -nputw
    3  sudo netstat -nputwc
    4  cd .lpass/
    5  ls
    6   sudo yum install –y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    7  sudo yum install lpass
    8  sudo yum install lastpass-cli
    9  ls
   10  lpass login
   11  lpass login email@domain
   12  set LPASS_LOG_LEVEL=8
   13  export LPASS_LOG_LEVEL=8
   14  lpass generate test-test 4
   15  cd .lpass/
   16  ls
   17  cd upload-queue/
   18  ls
   19  cd ..
   20  lpass sync
   21  cd .lpass/
   22  ls
   23  cd upload-queue/
   24  ls
   25  lpass sync
   26  ls -al
   27  cd .lpass/
   28  ls
   29  cd ..
   30  ls
   31  ps aux | grep last
   32  ps aux | grep lpass
   33  strace -e trace=file lpass
   34  sudo yum install strace
   35  strace -e trace=file lpass
   36  strace -e trace=file lpass sync
   37  cd .lpass/
   38  ls
   39  ls upload-queue/
   40  vim 1
   41  vim upload-queue/14903648560000 
   42  history

**Comment by bcopeland** [comment]
Which version of lastpass-cli do you have?  There was an issue fixed in ef497343c082dd2238962c03c87f606a0d255a2f that affected CentOS 7 -- discussion here https://github.com/lastpass/lastpass-cli/issues/101.  It should be fixed in all 1.x versions.

As in the other report, note strace of the lpass sync binary won't work as expected; it's the uploader process that actually does the syncing so you will want to at least use ```strace -f``` to see what it is trying to do.

**Comment by Kgirthofer** [comment]
Oooh that's probably it then - the lastpass-cli in the epel repo is v.8 - I will try installing v1 and see what happens.

**Comment by Kgirthofer** [comment]
@bcopeland that was it - needed to upgrade the version. Thanks for your help!
