### ISSUE TITLE
Question: Switch login prompt from popup to inline

### ISSUE THREAD

**Issue by fearphage** [lastpass/lastpass-cli#298]
On a mac, I've seen coworkers get prompted to login via an inline terminal prompt:

![inline prompt](https://cloud.githubusercontent.com/assets/23887/25432732/3d82e9ac-2a4b-11e7-92ba-ef6a46b85cdb.png)

In Linux (Ubuntu), I get a gui prompt popup (similar to this - not an actual screenshot though):

![*NOT* a screenshot of lastpass-cli](https://cloud.githubusercontent.com/assets/23887/25432686/11bdb48c-2a4b-11e7-9425-096ab7e9986d.png)

Is it possible to switch to the inline prompt from linux?

**Comment by nneul** [comment]
```env -u DISPLAY lpass login email@domain.com```

It uses same behavior as ssh key passphrase prompting - if DISPLAY is set indicating graphical session - will use graphical prompt. There may be a way to disable it globally, but above is simple.

**Comment by fearphage** [comment]
@nneul Thank you for the explanation and the fix!

If anyone else ever ends up here, I added the following alias to my shell (zsh) to always get this behvaior:

```shell
alias lpass='env -u DISPLAY lpass'
```

I assume this would work in bash as well.

**Comment by fearphage** [comment]
Does `lpass` have some config or environment variable that I can override for this? The alias is fine when I run it on the command line, but other subshells don't have that alias and I still get the popup.

**Comment by bcopeland** [comment]
You can set LPASS_DISABLE_PINENTRY.  pinentry is what decides whether to show terminal or popup (based on DISPLAY) but you can forego it entirely if you want.

**Comment by bcopeland** [comment]
Closing this because I think there are plenty of existing options.

**Comment by ezekiel-lemur** [comment]
@bcopeland   I have read the [wiki](https://lastpass.github.io/lastpass-cli/lpass.1.html#_configuration) and I would gladly set `LPASS_DISABLE_PINENTRY` to show terminal but I cannot figure out where this variable is on my linux install. Thank !

**Comment by bcopeland** [comment]
On Wed, Jun 27, 2018 at 03:02:38PM -0700, Ezekiel wrote:
> @bcopeland   I have read the [wiki](https://lastpass.github.io/lastpass-cli/lpass.1.html#_configuration) and I would gladly set `LPASS_DISABLE_PINENTRY` to show terminal but I cannot figure out where this variable is on my linux install. Thank !

You can do this in your shell, e.g. before running lpass:

export LPASS_DISABLE_PINENTRY=1

Add this to your startup scripts (~/.bash_profile, say) in order for it to be
set always.
