### ISSUE TITLE
How to create a group (folder)

### ISSUE THREAD

**Issue by eterry1388** [lastpass/lastpass-cli#300]
I am trying to create a group (folder) using this CLI.

If I run this: `printf '' | lpass add --non-interactive --sync=no 'GroupName/'`, a group appears is created, but with a blank account inside of it.

If I run this: `printf "Username: root\nPassword: pass\nURL: http://example.com" | lpass add --non-interactive --sync=no 'GroupName/AccountName'`, it does create the account properly inside of what appears to be a new group called GroupName.

However, when querying all accounts like this:  `lpass show --basic-regexp '.*'`, it doesn't show a separate entry for the group, with the group ID.  Rather it just shows the account inside of the group.

For example, I'm expecting to see this (which is what happens when creating a group and account in the LastPass UI):

```
GroupName/ [id: 3333]
GroupName/AccountName [id: 4444]
```

But instead, I'm just seeing this:

```
GroupName/AccountName [id: 4444]
```

So, how do I properly create a group using the LastPass CLI?

**Comment by bcopeland** [comment]
On Sat, Apr 29, 2017 at 10:17:42PM -0700, Eric Terry wrote:
> I am trying to create a group (folder) using this CLI.
> So, how do I properly create a group using the LastPass CLI?

Create an account with the special url 'http://group'.

Note, it's completely optional to have a group item representing
the folder unless you want to have empty folders appear.  I prefer
to just create accounts with specific group names and they will
automatically appear as if they belong to that folder.

**Comment by eterry1388** [comment]
@bcopeland Thank you for your quick response.  This did the trick:

```bash
printf 'URL: http://group' | lpass add --non-interactive 'GroupName/'
```
