### ISSUE TITLE
Adding new entry on a shared-folder directly.

### ISSUE THREAD

**Issue by jp-ec** [lastpass/lastpass-cli#305]
Hi,

Is there a way we could add entries directly on a shared folder? With version `1.0.0`, we could do:

`echo -ne "Name: ${entryname}\nHostname: ${hostname}\nUsername: ${username}\nPassword: ${password}\nNoteType: Server\nNotes:\n$notes" | lpass add --sync=now --note-type=server --non-interactive "Shared-$folder/${entryname}"`

We can't do this now and getting `(ver 1.1.2)`:

`Error: Use lpass mv to move items to/from shared folders`

I figured I could do:

```
echo $ARGS | lpass add --sync=now --note-type=server --non-interactive $entryname
lpass mv $entryname Shared-$folder
```

But this doesn't work as expected due to 

1) Entry isn't moved but rather just copied. Leaves us with two copies

2) The entry can't be moved if $entryname isn't unique. We have multiple entries with the same name. I could make a workaround here by checking if the name exists and accept only unique entry names.

Is there an easy way I could accomplish this? I might be overcomplicating the issue. Need your input. 

Thanks!

**Comment by jp-ec** [comment]
Hi,

Can I get an input here? A suggestion would be much appreciated.

We can't move to the latest version due the issues stated above. I hope we could have a fix before 1.0.0 is depreciated.

Thanks.

**Comment by bcopeland** [comment]
Try this:

```echo -ne "Name: Shared-$folder/${entryname}\nHostname: ${hostname}\nUsername: ${username}\nPassword: ${password}\nNoteType: Server\nNotes:\n$notes" | lpass add --sync=now --note-type=server --non-interactive "Shared-$folder/${entryname}"```

I added Shared-folder in front of the entryname -- otherwise lpass thinks you want to move it to the root folder.  Note, if you are editing a secure note which has Name already in the template (SSN, say), you will have to put Name twice, the first time as the account folder/name and the second one for the name of the person.

**Comment by jp-ec** [comment]
Thank you @bcopeland! That trick did it.

Closing this now as resolved.
