### ISSUE TITLE
Edit problem with mac

### ISSUE THREAD

**Issue by bonk** [lastpass/lastpass-cli#309]
Hello,
It seems that the edit command is not running properly.
When it is executed, the editor opens, but opens with no template.
We can not change this because there is no information on this in the help.
Also, I do not understand it in detail, but the attached directory may not exist.
Please confirm it is.

ProductName:	Mac OS X
ProductVersion:	10.12.4

**Comment by bonk** [comment]
Hello,
Although it was, it was solved.
I specified the environment variable as an env file and changed it to vim. I could edit the template.
It looks like a phenomenon that occurred because the bash editor was code.
Please add it to the help if you do not mind.
Thanks.

**Comment by bcopeland** [comment]
I don't quite understand your explanation, do you mean the `$EDITOR` variable was set to something called "code" which is a text editor on mac?  Suggestions for what to add are welcome.

**Comment by bcopeland** [comment]
Closing for now, we already mention editor in the docs.
