### ISSUE TITLE
1.2.0 has regressed on showing custom note types

### ISSUE THREAD

**Issue by speshak** [lastpass/lastpass-cli#311]
With 1.0 I could request fields from my custom template from `show`, with 1.2 that is no longer true:

> ➜  ~ lpass show --field="Vault Password" 256016XXXXX
> Error: Could not find specified field 'Vault Password'.

> ➜  ~ lpass show 256016XXXXX
> Shared-Notes/Vault [id: 256016XXXXX]
> NoteType: Custom_5203145724438773151

Before 1.2 the custom fields would show up in the general form of `show` and could be selected via the `--field` parameter.

**Comment by speshak** [comment]
I did a little recon work on this issue.

First a little script I named test_custom_notes.sh

    #!/bin/sh
    rm -f ./lpass ./build/lpass
    make clean && make

    if [ -e ./lpass ]; then
      LPASS=./lpass
    else
      LPASS=./build/lpass
    fi

    echo "Testing custom type with ${LPASS}"
    ${LPASS} show 2560167592455176475 | grep -q "Vault Password"
    exit $?

I then used this script with `git bisect` to test between current master and `v1.0.0`

That yielded the following bisect log:
    
    git bisect start
    # bad: [2c601472fa3a95381f836d7e450d87cb810ffefd] Merge pull request #310 from bket/test-openbsd
    git bisect bad 2c601472fa3a95381f836d7e450d87cb810ffefd
    # good: [fee47e77d4e622d47c3e33c37094162986c09f1e] changelog: add version 1.0.0 
    changes
    git bisect good fee47e77d4e622d47c3e33c37094162986c09f1e
    # bad: [063c4ce3db470f8ad2202c5478b092afb71a7cc8] version: update to 1.1.0
    git bisect bad 063c4ce3db470f8ad2202c5478b092afb71a7cc8
    # good: [32dc0637785280ac86f8eb641f2860ff975f28e9] Merge remote-tracking branch 'origin/topic-user-format-strings'
    git bisect good 32dc0637785280ac86f8eb641f2860ff975f28e9
    # bad: [d60e7316f95a527c5a0eb69f8871ecdb64a353dd] Merge pull request #230 from eli-schwartz/master
    git bisect bad d60e7316f95a527c5a0eb69f8871ecdb64a353dd
    # bad: [ad86e3b93fb8eea49500b66f3a884db7663bb44c] cmake: force -std=gnu99
    git bisect bad ad86e3b93fb8eea49500b66f3a884db7663bb44c
    # good: [ab6ad6705f0ec3fc5cea8d25ac408b778765065a] cmake: default openssl directory on mac to /usr/local/opt/openssl
    git bisect good ab6ad6705f0ec3fc5cea8d25ac408b778765065a
    # bad: [a971ec2d0c7568d0e33ab72ce9622a58bd858c11] cmake: remove Makefile since cmake generates it now
    git bisect bad a971ec2d0c7568d0e33ab72ce9622a58bd858c11
    # good: [6879b9f4bdf4a953d6ac4ee53395b721d7bb7480] cmake: add install-doc target
    git bisect good 6879b9f4bdf4a953d6ac4ee53395b721d7bb7480
    # first bad commit: [a971ec2d0c7568d0e33ab72ce9622a58bd858c11] cmake: remove Makefile since cmake generates it now

I don't understand why a change to the build system would cause this regression, but at least now I have a decent starting point for deeper investigation.

**Comment by speshak** [comment]
I realize now that the reason my bisect stopped where it did was due to the change to CMake.  I'll update my test script and continue bisecting where it left off.

**Comment by bcopeland** [comment]
On Tue, Jun 13, 2017 at 10:22:44AM -0700, Scott Peshak wrote:
> I realize now that the reason my bisect stopped where it did was due to the change to CMake.  I'll update my test script and continue bisecting where it left off.

Can you try reverting 1ae6957ac2fdf2b7352eed028fd66bcd11d31173?  That would
be my guess.

-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by speshak** [comment]
Reverting 1ae6957 on top of master restores the old functionality.

**Comment by bcopeland** [comment]
Thanks!  I'll get a test case for this into the tree and address.

**Comment by twistedjoe** [comment]
When can we expect a release with this fix?  The new Arch linux package use the releases and it's breaking some of my setup on my end. (Built over lastpass cli)

**Comment by bcopeland** [comment]
On Tue, Jun 27, 2017 at 04:02:02PM -0700, Joé Dupuis wrote:
> When can we expect a release with this fix?  The new Arch linux package use the releases and it's breaking some of my setup on my end. (Built over lastpass cli)

Would today be okay?

**Comment by bcopeland** [comment]
Released now, enjoy :)

**Comment by twistedjoe** [comment]
Awesome! Thanks :-)

**Comment by DebbieGillespie** [comment]
I am still seeing issues with this in version 1.2.1:
```
lpass show --field="Secret Key Base" 128139XXXXXXXXX
Error: Could not find specified field 'Secret Key Base'.
```

**Comment by bcopeland** [comment]
We have a test case in the tree for this now which is passing -- perhaps the test case didn't capture your bug exactly.  Can you verify that reverting 1ae6957 in 1.2.1 restores the functionality for you?  Or if you can tell me how your example differs from test-show-note in the `tests/test` script, I'd appreciate it.

**Comment by DebbieGillespie** [comment]
My bad, evidently we had a corrupt record that was causing the problem. Version 1.2.1 is behaving as expected and I can no longer reproduce the bug.
