### ISSUE TITLE
allow using pinentry-mac

### ISSUE THREAD

**Issue by glyph** [lastpass/lastpass-cli#314]
Right now in order to configure `lastpass` to use `pinentry-mac` rather than `pinentry`, I have to create a symlink somewhere on `$PATH`.  It would be nice to have an env var like `LPASS_ASKPASS` which expects an assuan implementation rather than a straight argv/stdout protocol.

**Comment by waterkip** [comment]
Could this be a solution to your problem? https://bezhermoso.github.io/2017/05/29/get-gpg-pinentry-to-work-with-vim-gnupg-in-neovim/
