### ISSUE TITLE
How is LPASS_AGENT_DISABLE meant to work?

### ISSUE THREAD

**Issue by vivianho** [lastpass/lastpass-cli#320]
I tried testing this out by doing the following:

```
➜ ~ export LPASS_AGENT_DISABLE=1
➜ ~ echo $LPASS_AGENT_DISABLE
1
➜ ~ lpass login --trust vho@lyft.com
Success: Logged in as vho@lyft.com.
➜ ~ ps -ef | grep lpass
502 84090 1 0 2:24PM ?? 0:00.00 lpass [agent]
```

As you can see, the lpass agent is still there, even though I disabled it. I'm just curious about this feature and would like more information.

**Comment by nneul** [comment]
```
        disable_str = getenv("LPASS_AGENT_DISABLE");
        if (!disable_str || strcmp(disable_str, "1")) {
            agent_start(key);
        }
```

**Comment by vivianho** [comment]
Actually I think `LPASS_AGENT_DISABLE=1` works, it only doesn't work on the `lpass login` command. Here is me using it for `lpass ls`
```
➜  ~ LPASS_AGENT_DISABLE=1 lpass ls > lpass.txt
➜  ~ ps -ef | grep lpass
  502 13499 12974   0  1:07PM ttys003    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn lpass
➜  ~ LPASS_AGENT_DISABLE=0 lpass ls > lpass.txt
➜  ~ ps -ef | grep lpass
  502 13506     1   0  1:07PM ??         0:00.00 lpass [a SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.hY08KPOToe/Listeners
  502 13512 12974   0  1:07PM ttys003    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn lpass
```

**Comment by vivianho** [comment]
If I run `lpass login` and then kill the agent, but still have all the session files in the `$HOME/.lpass` folder, does the session stored in this folder have an expiration? Or would I always be able to call `lpass ls` as long as I have this folder set up with session files?

**Comment by bcopeland** [comment]
@nneul you misunderstand strcmp's return value

@vivianho it looks like a bug, one of the paths doesn't check for LPASS_AGENT_DISABLE before starting.  Does the attached patch fix?

[fixme.patch.txt](https://github.com/lastpass/lastpass-cli/files/1179810/fixme.patch.txt)

**Comment by nneul** [comment]
Wow... I was interpreting the strcmp right - just completely blanked on the REST of the logic in that very simple if statement... Not sure how I managed that.

**Comment by nneul** [comment]
Why should the agent run in the other code path? i.e. why shouldn't it be disabled in both paths? (and factored out into separate function if so)

**Comment by bcopeland** [comment]
The patch I posted moves the check into agent_start(), so that now there is only one place to check and it doesn't matter where it gets called from.  The missing check was indeed for cmd-login (agent_save()) which just starts it so that subsequent commands don't have to reprompt for MPW.

**Comment by vivianho** [comment]
Yep I think that works for me.

**Comment by vivianho** [comment]
@bcopeland had an unrelated question while I have your attention here:

If I run `LPASS_AGENT_DISABLE=1 lpass login` which generates all the session files in the `$HOME/.lpass` folder, does the session stored in this folder have an expiration? Or would I always be able to call `lpass ls` as long as I have this folder set up with session files?

**Comment by bcopeland** [comment]
@vivianho There is an expiration, but it is fairly long -- 2 weeks if I recall correctly, and it will be extended another 2 weeks when used, so if you use it frequently enough it won't expire for practical purposes.

**Comment by vivianho** [comment]
Thanks, is there a specific error I can catch if the expiration is hit (so that I know to renew), or a file to check the expiration date?

**Comment by bcopeland** [comment]
@vivianho I don't think so.  There's been a request to make `lpass status` reach out to the server and check whether the session is still live, that should be doable with a minimum of fuss but doesn't exist yet today.
