### ISSUE TITLE
CLI Login Issue

### ISSUE THREAD

**Issue by RobertKaldenbach** [lastpass/lastpass-cli#325]
I have an issue with logging into our lastpass@directive.com account.  I am receiving a lockout email however there has been no change to our password.  Could this be related to a change in IP?  I know in the past we have had to verify an IP.  Any help in this matter would be greatly appreciated.

**Comment by bcopeland** [comment]
I checked the logs for this account which just appears to show incorrect password used several times, which eventually triggered the blacklist for brute force attempts.  The ban expires after a short time so it should be available to try again.

**Comment by bcopeland** [comment]
Still having an issue with this account?

**Comment by rutkai** [comment]
Please post a comment if it occurs again.
