### ISSUE TITLE
Feature request: show multiple fields

### ISSUE THREAD

**Issue by StevenLiekens** [lastpass/lastpass-cli#331]
Would it be possible to make `lpass show` print multiple fields on seperate lines?

> Usage: lpass show [--username] [--password] [--url] [--notes] [--field=FIELD_m [--field=FIELD_n [...]]] [--id] [--name] [--attach=ATTACHID_m [--attach=ATTACHID_n [...]]]

Example:

```sh
$ lpass show --username --password Email # or: lpass show -up Email
steven@example.com
$uper$ecret1
```

I'm asking because I configured LastPass to prompt for my master password every time I try to view something in my vault. So I get the prompt every time I run `lpass show`.

**Comment by bcopeland** [comment]
On Sat, Sep 09, 2017 at 07:30:45AM +0000, Steven Liekens wrote:
> Would it be possible to make `lpass show` print multiple fields on seperate lines?
> 
> > Usage: lpass show [--username] [--password] [--url] [--notes] [--field=FIELD_m [--field=FIELD_n [...]]] [--id] [--name] [--attach=ATTACHID_m [--attach=ATTACHID_n [...]]]
> 
> Example:
> 
> ```sh
> $ lpass show --username --password Email # or: lpass show -up Email
> steven@example.com
> $uper$ecret1

Is this for a script or just for normal usage?  Because without
any args, show does this already pretty much.

You can't do newlines currently, but you could use --format to get
delimited fields, e.g.:

```
$ lpass show acct --format='%au !!! %ap' | tail -1
user !!! password
```
-- 
Bob Copeland %% https://bobcopeland.com/

**Comment by StevenLiekens** [comment]
This is for a script. I'm trying to set two variables (user and password) using a single `show` command.

instead of:
```powershell
$user = $(lpass show -u Email)
$pass = $(lpass show -p Email)
```

I was trying to find a way to make lpass show print both fields at once on separate lines.

It looks like `--format` fits my use case.

```powershell
$credentials = $(lpass show --format='%/au%ap' Email | tail -1)
# $credentials = steven@example.com/$uper$ecret1
```
I can split the output by forward slash to get the username and password. Win!

The tail part confuses me. I'm not sure why the same output is printed multiple times.

**Comment by StevenLiekens** [comment]
What I ended up doing is quite complicated because I'm doing all this in PowerShell on Windows 10.

```powershell
$u,$p = ((ubuntu run lpass show --format='%/au%ap' Email) | select -last 1) -split '/',2,"simplematch"
```
This runs `lpass show` in [Bash on Ubuntu on Windows](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/) from PowerShell. Phew, what a mouthful.

Instead of tail in bash, I use a PowerShell cmdlet: `select -last 1`. Then I convert forward slashes to line breaks by using the `-split` operator in PowerShell: `-split '/',2`. The `,2` part limits the split operation to two substrings to avoid splitting passwords that contain slashes.

Finally I assign the first line of output to `$u` and the second line to `$p`. Perfect. 😄
