### ISSUE TITLE
SSO access to CLI

### ISSUE THREAD

**Issue by Catharz** [lastpass/lastpass-cli#332]
We're about to change our lastpass sign-in throughout our organisation, and we use the lastpass-cli.

Is it possible to sign into the lastpass-cli via OAuth or SAML?

**Comment by bcopeland** [comment]
It is not.

If you want to generate SAML tokens from the command line _from_ LastPass, well, that is a thing you could do: https://github.com/lastpass/lp-aws-saml.

**Comment by dwrusse** [comment]
Wish you would consider adding!

**Comment by chrisjohnson** [comment]
What would it take to get SSO cli support prioritized? We're in the same boat
