### ISSUE TITLE
Please support VISUAL alongside EDITOR

### ISSUE THREAD

**Issue by rjc** [lastpass/lastpass-cli#337]
Hi,

Most people by `EDITOR` actually mean `VISUAL`, as in a *full screen editor*.

For those of us who have **both** set in our environment, i.e.:

```
...
EDITOR=ed
VISUAL=vi
...
```

the current behaviour is to always use `EDITOR`, i.e. `ed`. It would be great if `VISUAL` could be added alongside `EDITOR` with the following order: `VISUAL -> EDITOR -> vi`, i.e.: `${VISUAL:-${EDITOR:-vi}}`.

Regards,

rjc

**Comment by waterkip** [comment]
I cannot close the issue, but this was merged yesterday.

**Comment by rjc** [comment]
Nice one! Thanks for doing that :^)
