### ISSUE TITLE
ssl connect error

### ISSUE THREAD

**Issue by peerster** [lastpass/lastpass-cli#338]
I get the following trying to login:
```
# lpass login myuser@example.com
Error: SSL connect error.
```
```
# lpass --version
LastPass CLI v1.2.1
```

Running on:
```
System Version: macOS 10.13 (17A405)
```

Any tips on how I could debug this? Can't find any arguments for increasing verbosity/debugging

**Comment by rutkai** [comment]
Is this issue still reproducible?

**Comment by peerster** [comment]
@rutkai I couldn't reproduce it. It might have been caused by the companies network that I was using. I I think we can close it

**Comment by rutkai** [comment]
Okay, thank you.
