### ISSUE TITLE
Sync causes result 60 (http_code=0)

### ISSUE THREAD

**Issue by thehpi** [lastpass/lastpass-cli#340]
I'm using lpass client installed via brew on a mac sierra.
I'm doing this to activate logging

export LPASS_LOG_LEVEL=7

Then I look in the $HOME/.lpass/lpass.log and see (after a sync)

<7> [1507892976.259575] Making request to https://lastpass.com/login_check.php
<7> [1507892976.499248] UQ: starting queue run
<7> [1507892976.499814] UQ: processing job upload-queue/15078929760000
<7> [1507892976.499878] UQ: posting to show_website.php
<7> [1507892976.499976] Making request to https://lastpass.com/show_website.php
<7> [1507892976.724668] UQ: result 60 (http_code=0)
<7> [1507892976.724790] UQ: attempt 2, sleeping 1 seconds
<7> [1507892977.726165] UQ: posting to show_website.php
<7> [1507892977.726391] Making request to https://lastpass.com/show_website.php
<7> [1507892977.916945] UQ: result 60 (http_code=0)
<7> [1507892977.917099] UQ: attempt 3, sleeping 8 seconds
<7> [1507892985.918206] UQ: posting to show_website.php
<7> [1507892985.918384] Making request to https://lastpass.com/show_website.php
<7> [1507892986.111406] UQ: result 60 (http_code=0)
<7> [1507892986.111563] UQ: attempt 4, sleeping 64 seconds
<7> [1507893050.111687] UQ: posting to show_website.php
<7> [1507893050.111923] Making request to https://lastpass.com/show_website.php
<7> [1507893050.182886] UQ: result 60 (http_code=0)
<7> [1507893050.183062] UQ: attempt 5, sleeping 512 seconds

Is 60 a curl error?

CURLE_SSL_CACERT (60): Peer certificate cannot be authenticated with known CA certificates.

Do we send a certificate? Is it a generated one? Looks like one of your servers does'n recognise it?

Please explain how to fix this.

**Comment by bcopeland** [comment]
Yes, curl error. Do you have anything unusual in your environment, like an intercepting proxy?  And what version of lpass is this?  In an older version we had a bug initializing the child process in curl which could cause SSL to not work, but only in the uploader process.  That was fixed in b78ae2ef2ed185e32147c3d51db219d8d003594e.

**Comment by thehpi** [comment]
No I'm using a normal wifi connection without special stuff. I installed lpass from brew so latest version.

But now I reinstalled the way it is described in the readme, so using

    brew install lastpass-cli --with-pinentry --with-doc

Now it looks better. I haven't seen the ssl error anymore.

thanks for your quick response

**Comment by bcopeland** [comment]
Closing on basis of most recent comment.
