### ISSUE TITLE
url should be displayed via ls command

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [lastpass/lastpass-cli#344]
Hello,

both chrome extension app and MAC OS application support searching feature by url.

Based on that searching url UX in UI app, I tried to use on cli like following,

```
$ lpass ls -l | grep someurl.com
```

but I failed because `ls` command did not provide url.

**Comment by bcopeland** [comment]
On Sat, Oct 21, 2017 at 10:08:26AM +0000, Alfred UC wrote:
> Hello,
> 
> both chrome extension app and MAC OS application support searching feature by url.
> 
> Based on that searching url UX in UI app, I tried to use on cli like following,
> 
> ```
> $ lpass ls -l | grep someurl.com
> ```
> 
> but I failed because `ls` command did not provide url.

In latest master you can do something like:

```
lpass ls --format=%al
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@bcopeland Thanks! I checked now!

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@bcopeland When do you expect next release version?
