### ISSUE TITLE
Impossible to add an ssh private key using the ssh-key note type

### ISSUE THREAD

**Issue by wknapik** [lastpass/lastpass-cli#353]
No matter what you do, the key will end up truncated.

Even the code in `test_add_ssh_key` saves a truncated private key.

This seems to have been reported and "resolved" multiple times.

LastPass CLI v1.2.1 on Arch Linux.

**Comment by bcopeland** [comment]
On Wed, Nov 08, 2017 at 02:52:50PM +0000, Wojciech Knapik wrote:
> No matter what you do, the key will end up truncated.
> 
> Even the code in `test_add_ssh_key` saves a truncated private key.
> 
> This seems to have been reported and "resolved" multiple times.
> 
> LastPass CLI v1.2.1 on Arch Linux.

The commits that "resolved" it this time are in 1.2.2 not 1.2.1 -- can
you try that?

**Comment by wknapik** [comment]
Yep, 1.2.2 fixed it, thanks.
Marked the Arch package outdated.

**Comment by wknapik** [comment]
For those interested - the [Arch package](https://www.archlinux.org/packages/community/x86_64/lastpass-cli/) was updated to 1.2.2.
