### ISSUE TITLE
Error after first login 

### ISSUE THREAD

**Issue by gsabatie** [lastpass/lastpass-cli#356]
**Step to reproduce** :
`$>  sudo apt-get install openssl libcurl4-openssl-dev libxml2 libssl-dev libxml2-dev pinentry-curses xclip cmake build-essential pkg-config`

`$>  sudo apt-get install lastpass-cli`
`$> lpass login user@me.com`
`Error: Peer certificate cannot be authenticated with given CA certificates.`

**Lastpass-cli** 0.7.0-1
**OS**: ubuntu 16.4

**Comment by bcopeland** [comment]
Please ask ubuntu to upgrade the version to something more recent.

On Tue, Nov 14, 2017 at 10:24:24AM +0000, Guillaume wrote:
> Step to reproduce :
> `$>  sudo apt-get install openssl libcurl4-openssl-dev libxml2 libssl-dev libxml2-dev pinentry-curses xclip cmake build-essential pkg-config`
> 
> `$>  sudo apt-get install lastpass-cli`
> `$> lpass login user@me.com`
> `Error: Peer certificate cannot be authenticated with given CA certificates.`
> 
> Lastpass-cli 0.7.0-1
> OS: ubuntu 16.4
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lastpass/lastpass-cli/issues/356

-- 
Bob Copeland %% https://bobcopeland.com/

**Comment by bcopeland** [comment]
Closing this as it has been reported already (and fixed in 0.7.2 and subsequent versions).

**Comment by masaeedu** [comment]
@bcopeland Seeing this again in v1.3.0 on Windows (built with Cygwin)

**Comment by dogik** [comment]
@bcopeland same here
> @bcopeland Seeing this again in v1.3.0 on Windows (built with Cygwin)

**Comment by karlney** [comment]
I am also affected. lpass worked well yesterday but today it stopped working with the following error

           Error: Peer certificate cannot be authenticated with given CA certificates.

I am running the latest master version - built it today (2018-05-16)

**Comment by AJZ229** [comment]
@bcopeland I started seeing this on Ubuntu 16 again, on v1.3.0

**Comment by AJZ229** [comment]
Tried downgrading to 1.2.2, same issue

**Comment by luckyvalentine** [comment]
same error here.  worked up until today.  
```
$ lpass --version
LastPass CLI v1.3.0
$ lpass ls
Error: Peer certificate cannot be authenticated with given CA certificates.
```
(running on Windows/Cygwin)

**Comment by blackjackshellac** [comment]
I am getting this error on fedora 28 after an upgrade from fedora 27.

```
$ lpass login foo@bar.com
Error: Peer certificate cannot be authenticated with given CA certificates.
```

```
$ rpm -qi lastpass-cli
Name        : lastpass-cli
Version     : 1.1.2
Release     : 4.fc28
Architecture: x86_64
Install Date: Mon 28 May 2018 05:51:34 PM EDT
Group       : Unspecified
Size        : 256769
License     : GPLv2
Signature   : RSA/SHA256, Thu 08 Feb 2018 10:06:31 PM EST, Key ID e08e7e629db62fb1
Source RPM  : lastpass-cli-1.1.2-4.fc28.src.rpm
Build Date  : Thu 08 Feb 2018 12:00:58 AM EST
Build Host  : buildvm-15.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/LastPass/lastpass-cli
Summary     : Command line interface to LastPass.com
Description :
A command line interface to LastPass.com.

```
