### ISSUE TITLE
Fingerprint login

### ISSUE THREAD

**Issue by widewing** [lastpass/lastpass-cli#363]
Is there any chance this cli tool can work with fingerprint devices?

**Comment by bcopeland** [comment]
On Fri, Dec 15, 2017 at 04:12:07AM +0000, Gavin Ni wrote:
> Is there any chance this cli tool can work with fingerprint devices?

Very unlikely.

1) There is (as far as I know) no cross-platform way to interact with
   fingerprint devices.

2) Having log-in-with-fingerprint effectively requires lastpass-cli to
   retain the key, and there is no single cross-platform way to do that
   securely.

**Comment by bcopeland** [comment]
I'm going to close this per the above.  If you or someone else decides to hack on it anyway and add fingerprint support, I'd love to hear about it!
