### ISSUE TITLE
PAM integration

### ISSUE THREAD

**Issue by guedressel** [lastpass/lastpass-cli#371]
Is any integration into Linux PAM planned?

**Comment by bcopeland** [comment]
Nothing planned at this time, and I think it's probably out of scope.  But what would you like out of such a module -- login to systems using LastPass password?  or something else?  At least the former could be achieved using code from kdf.c and login endpoint handling.

**Comment by guedressel** [comment]
Yes -- logging in to a PAM based (most (all?) Linux distributions) system with only the last pass master password, that's what I would like to have.
Once PAM is connected with last pass a whole lot other applications may become able to use the "login via last pass' master pass" feature - since they incorporate with PAM in some way (DB-Systems, SASL based services, ...)

**Comment by bcopeland** [comment]
OK - this is out of scope for this project, but if it's something you really need you can reach out to lastpass support with the request.
