### ISSUE TITLE
Notes entered in lpass to not appear in web ui

### ISSUE THREAD

**Issue by bseb** [lastpass/lastpass-cli#374]
If I create a new password entry using the lpass utility that has something in the "Notes" field that note does not appear in the web ui, it can only be viewed again using lpass show.  Notes entered in the web ui will appear both in the cli and webui. For example

```
Name: something
URL: foo.bar
Username: foo
Password: bar
Notes:    # Add notes below this line.
**This wont be visible in the web ui**
```
MacOS version 10.12.6
LastPass CLI v1.2.2
LastPass Enterprise account.

**Comment by carsonreinke** [comment]
@bseb Seeing this too, but noticed it appears under `Form Fields` instead of the Notes section.

**Comment by carsonreinke** [comment]
I got it to work with modifying the (test)[https://github.com/lastpass/lastpass-cli/blob/master/test/tests#L52] from this package:

```bash
cat<<__EOM__ | lpass add --sync=no --note-type=ssn --non-interactive "my-test-8"
> Name: my-test-8
> Number: 000-00-0000
> NoteType: Social Security
> Notes: 
> This is my SSN
> __EOM__
```

![screen shot 2018-03-14 at 1 52 54 pm](https://user-images.githubusercontent.com/378481/37421185-0aae8da0-278f-11e8-9bb8-4544088b3585.png)

I had to rename to `Notes` and move `NoteType` above.  I have not gotten this to work properly for a Site, not a Secure Note.

**Comment by carsonreinke** [comment]
@bseb The only way I could it to work is by doing the following `lpass edit --note` after adding it.  The parsing of this data is pretty badly broken.

**Comment by bcopeland** [comment]
@carsonreinke thanks for the hint that these were ending up in fields, committed a fix for that.

**Comment by carsonreinke** [comment]
@bcopeland You should change the "tests" too: https://github.com/lastpass/lastpass-cli/blob/76d4fbc5df1bfcd6617c255b5bbd08fbdf5ad3e5/test/tests#L81

**Comment by bcopeland** [comment]
@carsonreinke fair enough, though if you didn't notice, I added a test specifically for this case already as well.
