### ISSUE TITLE
Segmentation fault on lpass login when building under debian

### ISSUE THREAD

**Issue by seanfdnn** [lastpass/lastpass-cli#375]
Running lpass login after builting from source on debian produces a segfault:

lpass login <email address> 
gives "Segmentation Fault"

lpass login (without email) give the correct usage info
Usage: lpass login [--trust] [--plaintext-key [--force, -f]] [--color=auto|never|always] USERNAME

Built under debian using the instructions in the README
4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

(note the warnings at the end of make -- this may be related?)

mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_MANDIR:PATH=/usr/share/man ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.4") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.0f") 
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.52.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sean/lastpass-cli/build
make -C build all
make[1]: Entering directory '/home/sean/lastpass-cli/build'
make[2]: Entering directory '/home/sean/lastpass-cli/build'
make[3]: Entering directory '/home/sean/lastpass-cli/build'
Scanning dependencies of target lpass
make[3]: Leaving directory '/home/sean/lastpass-cli/build'
make[3]: Entering directory '/home/sean/lastpass-cli/build'
[  2%] Building C object CMakeFiles/lpass.dir/agent.c.o
[  4%] Building C object CMakeFiles/lpass.dir/blob.c.o
[  7%] Building C object CMakeFiles/lpass.dir/cipher.c.o
[  9%] Building C object CMakeFiles/lpass.dir/clipboard.c.o
[ 12%] Building C object CMakeFiles/lpass.dir/cmd-add.c.o
[ 14%] Building C object CMakeFiles/lpass.dir/cmd-duplicate.c.o
[ 17%] Building C object CMakeFiles/lpass.dir/cmd-edit.c.o
[ 19%] Building C object CMakeFiles/lpass.dir/cmd-export.c.o
[ 21%] Building C object CMakeFiles/lpass.dir/cmd-generate.c.o
[ 24%] Building C object CMakeFiles/lpass.dir/cmd-import.c.o
[ 26%] Building C object CMakeFiles/lpass.dir/cmd-login.c.o
[ 29%] Building C object CMakeFiles/lpass.dir/cmd-logout.c.o
[ 31%] Building C object CMakeFiles/lpass.dir/cmd-ls.c.o
[ 34%] Building C object CMakeFiles/lpass.dir/cmd-mv.c.o
[ 36%] Building C object CMakeFiles/lpass.dir/cmd-passwd.c.o
[ 39%] Building C object CMakeFiles/lpass.dir/cmd-rm.c.o
[ 41%] Building C object CMakeFiles/lpass.dir/cmd-share.c.o
[ 43%] Building C object CMakeFiles/lpass.dir/cmd-show.c.o
[ 46%] Building C object CMakeFiles/lpass.dir/cmd-status.c.o
[ 48%] Building C object CMakeFiles/lpass.dir/cmd-sync.c.o
[ 51%] Building C object CMakeFiles/lpass.dir/cmd.c.o
[ 53%] Building C object CMakeFiles/lpass.dir/config.c.o
[ 56%] Building C object CMakeFiles/lpass.dir/edit.c.o
[ 58%] Building C object CMakeFiles/lpass.dir/endpoints-login.c.o
[ 60%] Building C object CMakeFiles/lpass.dir/endpoints-share.c.o
[ 63%] Building C object CMakeFiles/lpass.dir/endpoints.c.o
[ 65%] Building C object CMakeFiles/lpass.dir/format.c.o
[ 68%] Building C object CMakeFiles/lpass.dir/http.c.o
[ 70%] Building C object CMakeFiles/lpass.dir/kdf.c.o
[ 73%] Building C object CMakeFiles/lpass.dir/log.c.o
[ 75%] Building C object CMakeFiles/lpass.dir/lpass.c.o
[ 78%] Building C object CMakeFiles/lpass.dir/notes.c.o
[ 80%] Building C object CMakeFiles/lpass.dir/password.c.o
[ 82%] Building C object CMakeFiles/lpass.dir/pbkdf2.c.o
[ 85%] Building C object CMakeFiles/lpass.dir/process.c.o
[ 87%] Building C object CMakeFiles/lpass.dir/session.c.o
[ 90%] Building C object CMakeFiles/lpass.dir/terminal.c.o
[ 92%] Building C object CMakeFiles/lpass.dir/upload-queue.c.o
[ 95%] Building C object CMakeFiles/lpass.dir/util.c.o
[ 97%] Building C object CMakeFiles/lpass.dir/xml.c.o
[100%] Linking C executable lpass
make[3]: Leaving directory '/home/sean/lastpass-cli/build'
[100%] Built target lpass
make[2]: Leaving directory '/home/sean/lastpass-cli/build'
make[1]: Leaving directory '/home/sean/lastpass-cli/build'

/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1

**Comment by ashemedai** [comment]
To add, this is part of the backtrace:

```
(gdb) bt
#0  0x0000000000000001 in ?? ()
#1  0x00007ffff31c465d in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
#2  0x00007ffff70f8140 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#3  0x00007ffff70fa150 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#4  0x00007ffff70fb00a in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#5  0x00007ffff70a9682 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#6  0x00007ffff70b5e86 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#7  0x00007ffff70cb9b6 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#8  0x00007ffff70cc954 in curl_multi_perform () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#9  0x00007ffff70c2884 in curl_easy_perform () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#10 0x00005555555729ae in http_post_lastpass_v_noexit (server=0x0, page=0x55555557d757 "login_check.php", session=0x5555557d54d0, final_len=0x0, argv=0x5555559912b0, curl_ret=0x7fffffffdb24, 
    http_code=0x7fffffffdb18) at /home/jeroenr/projects/thirdparty/lastpass-cli/http.c:310
#11 0x0000555555572aeb in http_post_lastpass_v (server=0x0, page=0x55555557d757 "login_check.php", session=0x5555557d54d0, final_len=0x0, argv=0x5555559912a0)
    at /home/jeroenr/projects/thirdparty/lastpass-cli/http.c:336
#12 0x0000555555572b61 in http_post_lastpass_param_set (page=0x55555557d757 "login_check.php", session=0x5555557d54d0, final_len=0x0, param_set=0x7fffffffdb90)
    at /home/jeroenr/projects/thirdparty/lastpass-cli/http.c:347

```

**Comment by Ozzyboshi** [comment]
I remember I had the same issue when installing on my debian 9, I solved installing openssl but not sure...

**Comment by bcopeland** [comment]
Yes, it's exactly because of this:
```
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
```
The reason is that libcurl4-openssl-dev is linked against openssl 1.0, while the binary is linked against openssl 1.1 and they are not compatible.  You will need to install libssl1.0-dev to fix.

**Comment by seanfdnn** [comment]
Installing libssl1.0-dev and re-compiling worked perfectly. Thank you for the help!
