### ISSUE TITLE
unable to access passwords from cli

### ISSUE THREAD

**Issue by efx** [lastpass/lastpass-cli#380]
I have been using this cli for the past year successfully on mac OS. Thank you for building it; it is quite helpful.
Recently, it has stopped working. I am using version 1.2.2. I am an enterprise user.
I first saw issue https://github.com/lastpass/lastpass-cli/issues/140. I executed `rm -rf ~/.lpass`. Now I see:
```
$ lpass ls  
Error: HTTP response code said error.
```
Any specific debugging steps I should take?

**Comment by efx** [comment]
Upped the log level per https://github.com/lastpass/lastpass-cli/issues/304#issuecomment-301823148, and see the following:
```
<7> [1519229290.177355] Making request to https://lastpass.com/getaccts.php
*   Trying 23.14.146.170...
* TCP_NODELAY set
* Connected to lastpass.com (23.14.146.170) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: businessCategory=Private Organization; serialNumber=000873622; jurisdictionC=US; jurisdictionST=Massachusetts; C=US; ST=Massachusetts; L=Boston; street=320 Summer St Ste 100; OU=LastPass; O=LogMeIn, Inc; CN=lastpass.com
*  start date: Jun 13 16:58:09 2016 GMT
*  expire date: Jun 14 16:58:09 2018 GMT
*  subjectAltName: host "lastpass.com" matched cert's "lastpass.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Extended Validation CA - SHA256 - G2
*  SSL certificate verify ok.
> POST /getaccts.php HTTP/1.1
Host: lastpass.com
User-Agent: LastPass-CLI/1.2.2
Accept: */*
Cookie: PHPSESSID=tpc9y-biXaDh6rq7ezzkVzjYvc2
Content-Length: 39
Content-Type: application/x-www-form-urlencoded

* upload completely sent off: 39 out of 39 bytes
* The requested URL returned error: 403 Forbidden
* stopped the pause stream!
* Closing connection 0
```
Still not sure what this means or why it just started happening...

**Comment by bcopeland** [comment]
On Wed, Feb 21, 2018 at 08:10:22AM -0800, Eli Flanagan wrote:
> Upped the log level per https://github.com/lastpass/lastpass-cli/issues/304#issuecomment-301823148, and see the following:
> ```
> <7> [1519229290.177355] Making request to https://lastpass.com/getaccts.php
> *   Trying 23.14.146.170...

Are you still having issues with this today?  According to
https://status.lastpass.com/ there was a service interruption yesterday.

-- 
Bob Copeland %% https://bobcopeland.com/

**Comment by efx** [comment]
@bcopeland thanks, I no longer am seeing this issue. It would be nice to have clearer error messages as I was confused for a bit. I'll just close this issue though.
