### ISSUE TITLE
Can't use spaces

### ISSUE THREAD

**Issue by tjarvstrand** [lastpass/lastpass-cli#382]
Hi!

I just installed the lastpass cli and it seems it's impossible for me to use anything (folder, entry or field) that contains spaces.

```
$ lpass ls 'My Folder'
Usage: /usr/bin/lpass ls [--sync=auto|now|no] [--long, -l] [-m] [-u] [--color=auto|never|always] [GROUP]

$ lpass ls 'Sites\\Personal/Docker Hub'
Usage: /usr/bin/lpass ls [--sync=auto|now|no] [--long, -l] [-m] [-u] [--color=auto|never|always] [GROUP]

$ lpass show --field='Private Key' ssh/my_key                                     
Error: Could not find specified field 'Private'.
```

Any clue what could be wrong?

**Comment by bcopeland** [comment]
On Mon, Mar 05, 2018 at 12:39:42PM +0000, Thomas Järvstrand wrote:
> Hi!
> 
> I just installed the lastpass cli and it seems it's impossible for me to use anything (folder, entry or field) that contains spaces.
> 
> ```
> $ lpass ls 'My Folder'
> Usage: /usr/bin/lpass ls [--sync=auto|now|no] [--long, -l] [-m] [-u] [--color=auto|never|always] [GROUP]
> 
> $ lpass ls 'Sites\\Personal/Docker Hub'
> Usage: /usr/bin/lpass ls [--sync=auto|now|no] [--long, -l] [-m] [-u] [--color=auto|never|always] [GROUP]
> 
> $ lpass show --field='Private Key' ssh/my_key
> Error: Could not find specified field 'Private'.
> ```

Very strange.  What shell is this?  Are you sure those single-quotes are
the kind your shell expects (and not, say, smart quotes or the like)?

I would try either double quotes or escaping the space with backslash; it
seems like the shell is discarding the argument before lpass sees it.

-- 
Bob Copeland %% https://bobcopeland.com/

**Comment by tjarvstrand** [comment]
Yeah, those are the same single quotes I use for everything else :)

I'm in bash 4.4.12 on Ubuntu 17.10

```
lpass show --field="Private Key" ssh/tjarvstrand                                          
Error: Could not find specified field 'Private'.
```

**Comment by tjarvstrand** [comment]
Forget about it. I found the problem and it's nothing that I will entertain other people with :D

Sorry for the noise!
