### ISSUE TITLE
lpass.exe is considered a trojan in Kapersky Endpoint Security 10 for Windows

### ISSUE THREAD

**Issue by ilima-nvps** [lastpass/lastpass-cli#384]
Just received a warning from my endpoint security solution that your executable is exhibiting behavior that is a "sure sign of malware". See screenshots attached including log entries that the software has deemed malicious. Is this behavior expected?

![image](https://user-images.githubusercontent.com/14248975/37345884-46762a8c-26a4-11e8-9b42-ed6dd9664612.png)
![image](https://user-images.githubusercontent.com/14248975/37346116-e72674f0-26a4-11e8-89c9-23ee461cfd6f.png)

**Comment by bcopeland** [comment]
I'm not sure what all of the "Create" with keys beside them are, due to details being chopped off.  But everything else is perfectly normal.

**Comment by bcopeland** [comment]
Looks like a false positive to me, closing on that basis.
