### ISSUE TITLE
how to show form fills?

### ISSUE THREAD

**Issue by btmurrell** [lastpass/lastpass-cli#388]
it seems to me that lastpass form fills are just a more sophisticated note of sorts.  i cannot find a way in lpass cli to show any of my form-fill objects.  am i missing something?  or is this an enhancement request?

btw, props -- thanks for the lpass cli.  love having this!

**Comment by waterkip** [comment]
You can view them with lpass show $site:

```
lpass show foo         
foo [id: XXXX]
Username: bar
Password: foo
URL: https://foo.bar
foo: barzz
fooooo: barrxx
nnnaa: bbaa
```

foo, fooooo and nnnaaa

if you run `lpass edit foo` you will  see

```
Name: foo 
URL: https://foo.bar
Username: bar 
Password: foo 
foo: barzz
fooooo: barrxx
nnnaa: bbaa
Notes:    # Add notes below this line.
```

And now you can add form fields and change the values.

Hope this helps!

**Comment by btmurrell** [comment]
Thanks @waterkip, but that's not it.  The distinction here is *form fills*, not sites or notes.

**Comment by rutkai** [comment]
Lastpass cli doesn't support formfills and currently there are no plans to provide support for them. You can use secure notes instead of them.

**Comment by btmurrell** [comment]
@rutkai  -- with all due respect, to say i can use notes instead is to disregard the distinctive features of lastpass.  form fills and secure notes serve two different purposes.

**Comment by quantuminformation** [comment]
You can't even add a form fill any more using the lastpass chrome mention it only has the existing ones there. Infuriating when you want to add a default from fill for the key bindings
