### ISSUE TITLE
Password changes are recorded, but do not update Chrome plugins

### ISSUE THREAD

**Issue by waterkip** [lastpass/lastpass-cli#391]
Hi,

We have changed passwords via the CLI client of LP like so:

    echo "$password" | \
        lpass edit --sync=yes --non-interactive \
        --password $site

What we now see/experience is that users of the Chrome plugin can:
1) Not login directly, the prefill enters an old password
2) When they c/p the password, they are able to login

What I see/suspect is that once I enter an "adminstrative" area (I click on the wrench in the plugin once I open the site information) is that it is filled with: username/password fields. If I remove these, the password is picked up correctly. This is clearly visible via the cli: `lpass show $site`:

 ```bash
show $site
The sitename
Username: <username>
Password: <password>
URL: <url>
username:<username>
password: <some other password>
```

Related side note:
I also have a huge issue with updating the passwords from the CLI client, `lpass edit --sync=now $site` doesn't seem to do much, similarly, calling `lpass sync` doesn't seem to do its magic. At least, I don't see my changes in the Chrome plugin, or via the website (and the website is even trickier, because reloading LP makes me login again).

I hope you can help,
Wesley

**Comment by waterkip** [comment]
I'm also talking to LP support via the normal way. The issue is two fold:

1) The Chrome plugin uses the form field data to populate the username/password fields. This is wrong from my point of view. We cannot fix this from this side

2) The lastpass cli client does not delete form fields. I'm able to reproduce that on both my private and corporate account: I'm going to close this issue and open a new one.

**Comment by acjay** [comment]
@waterkip  Did you figure this out? I'm having issues with changes in the Chrome plugin not being reflected on the command line, regardless of syncing either.

**Comment by waterkip** [comment]
Nope: https://github.com/lastpass/lastpass-cli/issues/392
