### ISSUE TITLE
No way to retrieve attachments to secure notes

### ISSUE THREAD

**Issue by mexon** [lastpass/lastpass-cli#393]
I just installed version 0.7.2.  I am pretty sure that in earlier versions there was a way to export an attachment.  The attachments showed up when you did lpass show.  They don't any more, and there doesn't seem to be any command to do that.  This is on an Ubuntu machine.

This is pretty important for me, since the browser plugins are broken and have been for a long time.  If I don't install the extension and click an attachment, it tells me to install the extension.  When I install the extension, and then click an attachment, it simply doesn't react.  Chrome and Firefox, Macintosh.  There is now literally no way for me to get access to my files.

**Comment by rutkai** [comment]
There was no feature removal, so this feature is not yet supported. The version 0.7.2 you installed is pretty old though, I can recommend downloading the latest tag.

Speaking of the browser extensions, if you have any problems with them, please contact our support at
https://lastpass.com/supportticket.php?lpnorefresh=1
