### ISSUE TITLE
Can't log in: Error in pinentry

### ISSUE THREAD

**Issue by cledoux** [lastpass/lastpass-cli#40]
A simple login attempt fails after inputting the 2FA code.

After inputting password and 2FA code, I am brought back to the password prompt with a red error message.

    Aborted multifactor authentication.

Cancelling the login shows the following error message on the console.

    *** Error in `pinentry': free(): invalid next size (normal): 0x00000000024db930 ***

Repeated attempts always result in this message with varying hex values on the end.

I am using Linux Mint 17 with the cinnamon desktop. Pinentry is pinentry-curses version 0.8.3. Everything is fully updated to the versions in the repos.

Using `export LPASS_DISABLE_PINENTRY=1` is a viable work around.  Additionally, after logging in with the --trust option once, subsequent logins work just fine using pinentry.

**Comment by bcopeland** [comment]
I still don't know root cause of this one - I'm unable to reproduce here (and am using multifactor with pinentry).

**Comment by cledoux** [comment]
Attempting to reproduce on my machine with lastest source checkout and now everything works perfectly.  Don't know what changed, though.

Using commit b5bccb699183925752028be394f265b3ca440cc2 for reference.

Thanks for looking into this and glad it's working now, whatever the fix might have been.
