### ISSUE TITLE
Error: Peer certificate cannot be authenticated with given CA certificates.

### ISSUE THREAD

**Issue by RevHokan** [lastpass/lastpass-cli#409]
I'm using CLI 1.2.1 and, starting late this morning, am receiving this message, "Error: Peer certificate cannot be authenticated with given CA certificates."

This happens on two different FreeBSD systems.

I downloaded and compiled 1.3.0 but it produced the same message.

**Comment by briantist** [comment]
Same, was working earlier, stopped suddenly today. Recompiling, updating system packages, etc. have not fixed.

I'm on Ubuntu 16.04 (WLS).

**Comment by dogik** [comment]
I am facing this as well. Had older version and started getting this error today. Thought that because I was out to date. Upgraded to 1.3.0 - the same. I tried on ubuntu for windows and on my EC2 ubuntu 16 instance.

**Comment by dead10ck** [comment]
Confirming this started happening to me on Arch Linux.

**Comment by paulo-Faitarone** [comment]
My application running at 2 hours ago, and now, when i try connect lpass login ... return "Peer certificate cannot be authenticated with given CA certificates."

We use version 1.3.0

**Comment by dogik** [comment]
@bcopeland Can we please get any advice on this one? Any quick fix? It seems like it is affecting a lot of people. It was a massive blocker for me this morning. You seems answered to similar issues before. Thanks in advance.

**Comment by DelusionalLogic** [comment]
So it seems like a simple case of miscommunication.

2 years ago, [this](https://github.com/lastpass/lastpass-cli/commit/46e2a0fb488f4ed7fd8cc3f1c5b64ca009abc5ba) commit removed GlobalSign R3 from the pin list, supposedly because they were going to be using R2 from now on. Unfortunately for them, the new cert they were issued May 2nd is actually from R3, meaning that the pin list is not broken.

Adding the old R3 pin back into the list fixes the issue.

**Comment by bcopeland** [comment]
@dogik unfortunately I no longer work at LastPass so I can't do anything about it... 

@rutkai can you find out why the *intermediate* certs changed and undo that pretty please?  It should work even if the root cert is not pinned.

**Comment by DelusionalLogic** [comment]
It seems like GlobalSign got a new intermediate cert Sep 21st 2016, half a year after last update to the pin list.

**Comment by karlney** [comment]
I am also affected. lpass worked well yesterday but today it stopped working with the following error

           Error: Peer certificate cannot be authenticated with given CA certificates.

I am running the latest master version - built it today (2018-05-16)

I am using Linx Mint v 18.2

**Comment by bcopeland** [comment]
Ok, well I guess we pinned the primary and the leaf, not the intermediate... I don't know if it is possible for LP to get a new cert with the old key (assuming GlobalSign won't issue another R2 cert), but obviously I have no say in cert procurement anymore so I guess reverting that commit is the best we can do for now

**Comment by RevHokan** [comment]
Based on comments by @karlney and @bcopeland I added these lines to pins.h and now things seem to work:
        /* future lastpass root CA (GlobalSign R1) */
        "K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q=",
        /* future lastpass root CA (GlobalSign R3) */
        "cGuxAXyFXFkWm61cF4HPWX8S0srS9j0aSqN0k4AP+4A=",

I'm guessing I really only need the last one.

**Comment by bcopeland** [comment]
I went ahead and sent a PR for reverting that commit (adding back the other 2 roots), but I can't merge it, @rutkai will have to do that.

**Comment by efx** [comment]
As I'm an enterprise user, I've submitted a support ticket linking to this issue.

**Comment by karlney** [comment]
The fix @RevHokan suggested works for me as well, changing the pins.h file and re-building

**Comment by supernomad** [comment]
can confirm the fix @RevHokan posted indeed works

**Comment by paulgear** [comment]
Merging the change from @bcopeland's PR and recompiling did not work for me.  Still gives the same error on attempting `./lpass show NNNN`

**Comment by hirenshah005** [comment]
Can anyone please tell how can I fix this issue with my LP?

**Comment by jballment** [comment]
I pulled this patch as well and lpass is now working for me as well.

**Comment by Ozzyboshi** [comment]
recompiling with the pins.h as suggested by @bcopeland  fixes the issue
Thanks a lot for your help

**Comment by cytopyge** [comment]
Same issue with LastPass CLI v1.2.2 under Linux 4.16.8-1-ARCH x86_64 GNU/Linux

**Comment by wknapik** [comment]
Arch users will be happy to hear that the distro package, updated 100min ago, already contains the patch (kudos to @mtorromeo for the quick reaction!). Everyone else has to patch manually and recompile.

**Comment by rutkai** [comment]
Fix is in the master branch and is included in the latest version `1.3.1`. Thank you for the contribution!

**Comment by userdash** [comment]
Dear @RevHokan , 
may i ask where can we find (_path_) this **pins.h** file in ubuntu os?
thanks in advance

**Comment by Xtigyro** [comment]
It appears it still not fixed in SLES - reported it today: https://bugzilla.suse.com/show_bug.cgi?id=1139563
