### ISSUE TITLE
Subfolders/Groups show up as empty id entries

### ISSUE THREAD

**Issue by azmodude** [lastpass/lastpass-cli#41]
I am using several subfolders in my vault. It seems like those subfolders show up ungrouped in `lpass ls` with just their id shown. Is this intended behaviour?

```
$ lpass ls
Development\Sites
    Testentry [id: 3886944626]
 [id: 3886932556]
[...]

$ lpass show 3886932556
Development\Sites/ [id: 3886932556]
URL: http://group
```

**Comment by bcopeland** [comment]
Fixed in f58eb0e74fd26a1103dc3d9b2019a467dfaf6180.
