### ISSUE TITLE
Error: Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by NikoGrano** [lastpass/lastpass-cli#414]
Duplicates: #88 #242  #356 #409 

Having error: Peer certificate cannot be authenticated with given CA certificates

Reinstalling helps usually, but not this time. I have run this script:
```
sudo rm -f /usr/bin/lpass \
&& wget https://github.com/lastpass/lastpass-cli/releases/download/v1.3.1/lastpass-cli-1.3.1.zip \
&& unzip lastpass-cli-1.3.1.zip \
&& rm lastpass-cli-1.3.1.zip \
&& cd lastpass-cli-1.3.1 \
&& make \
&& sudo make install \
&& cd .. \
&& rm -rf lastpass-cli-1.3.1
```

![image](https://user-images.githubusercontent.com/4658966/40473622-65ef88de-5f45-11e8-8b6b-ad6ffb3780b1.png)

**Comment by lpagie** [comment]
I had the same problem, tried to install after fetching git repos. I could re-make, but re-make install installed in a different directory ( #413 ).
Directly calling the newly made bin successfully allowed me to login:
```
~/src/lastpass/lastpass-cli/lpass login my-user-name 
Success: Logged in as my-user-name.
XYZ@ZYX:~/src/lastpass/lastpass-cli$ 
```
Just some sanity checks (which could have helped me, perhaps you checked all this already):
* make sure you call the newly compiled binary (`lastpass --version`)
* make sure the binary you use is what you think is used (`which lpass`)
* perhaps you need to logout first from lastpass (`lpass logout`)

Hope any of this helps, Ludo

**Comment by AJZ229** [comment]
Using current from master solved my problem as well.

**Comment by blackjackshellac** [comment]
I am getting this error on fedora 28 after an upgrade from fedora 27.

```
$ lpass login foo@bar.com
Error: Peer certificate cannot be authenticated with given CA certificates.
$ lpass --version
LastPass CLI v1.1.2
```
```
$ rpm -qi lastpass-cli
Name        : lastpass-cli
Version     : 1.1.2
Release     : 4.fc28
Architecture: x86_64
Install Date: Mon 28 May 2018 05:51:34 PM EDT
Group       : Unspecified
Size        : 256769
License     : GPLv2
Signature   : RSA/SHA256, Thu 08 Feb 2018 10:06:31 PM EST, Key ID e08e7e629db62fb1
Source RPM  : lastpass-cli-1.1.2-4.fc28.src.rpm
Build Date  : Thu 08 Feb 2018 12:00:58 AM EST
Build Host  : buildvm-15.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/LastPass/lastpass-cli
Summary     : Command line interface to LastPass.com
Description :
A command line interface to LastPass.com.

```

**Comment by Niko9911** [comment]
This issue doesn't have any references to OS upgrade. This issue is caused by using wrong certs, but how I can get the latest certs for lpass is different thing. Like, do I just need to copy them from their website, or do those certs belong into the repo?

**Comment by blackjackshellac** [comment]
Well, it is related to an old version in the redhat repos :)

cross referencing fedora issue https://bugzilla.redhat.com/show_bug.cgi?id=1583717

**Comment by craigm-splunk** [comment]
I am also getting this error, but with a couple of caveats depending on the user.  For example, on 1.3.0, it doesn't work regardless of user or platform.  However, I don't receive the error on 1.3.1 when using root privs.  I would like to get around this issue without using a privileged account.  Open to any idea.  =)

**Comment by falconian** [comment]
I am experiencing this same issue with an AWS Linux AMI on 1.3.0.  However, on 1.3.1, it works if I use root privs.  Is there any way to use 1.3.1 with a non-privileged user?

**Comment by ben-rabid** [comment]
I've installed 1.3.1 on my Debian machine and I'm able to use the CLI again - thanks @falconian for the tip

**Comment by blackjackshellac** [comment]
FWIW, cloning the repo followed by `make && sudo make install` was sufficient to get it running on fedora 28.  No root privs needed to use here.

**Comment by Niko9911** [comment]
@blackjackshellac 

Yes, you don't need root privileges, if you're installing for current user. But if're installing to all users, story is different.

**Comment by blackjackshellac** [comment]
@Niko9911 I was responding to @falconian's comment aobut 1.3.1 requiring root privs.  

Obviously root privs are required to install with `sudo make install`, but the app works fine as a regular user.

**Comment by blackjackshellac** [comment]
FWIW, this is fixed on the latest fedora 28 version, currently in updates-testing but should be making itself available in the updates repository in the coming days.

**Comment by NikoGrano** [comment]
Repository maintainer seems to be dead and no productive work have been done for fixing this, so closing. This issue still persist. 

Somebody else; feel free to open new issue.
