### ISSUE TITLE
intermittent errors and segmentation faults when logging-in on macOS

### ISSUE THREAD

**Issue by robjtede** [lastpass/lastpass-cli#421]
intermittent segmentation faults and other errors when logging-in on macOS After a few attempts at logging in, it allows it. I've also witnessed this happening with other operations such as `show`.

<img width="870" alt="2018-06-25_13 02 12-2937c671" src="https://user-images.githubusercontent.com/3316789/41849319-6a580814-7878-11e8-8d00-73a059430d0c.png">

**Comment by wkoszek** [comment]
@robjtede Are you on macOS Mojave by any chance? Did you have these problems on High Sierra?

**Comment by robjtede** [comment]
Looking at the issue date, I would have been on Mojave by then, yes.
I have no experience of the tool before then.

**Comment by andilesteve** [comment]
having the same issue >

**Comment by micdah** [comment]
See #427, there is a workaround as well
