### ISSUE TITLE
Option to use curses interface in Linux

### ISSUE THREAD

**Issue by kbenzie** [lastpass/lastpass-cli#434]
When I invoke an `lpass` command on macOS (installed with Homebrew) that requires my password I'm presented with a curses interface but when on Linux Mint 18 (built from source) I'm presented with a GUI dialog box which can appear in random places I'm not focused on.

Is there a way to use the curses interface instead of the GUI dialog box when building from source in Linux?

**Comment by ymatsiuk** [comment]
@kbenzie I think the answer is in https://github.com/lastpass/lastpass-cli/issues/456

**Comment by kbenzie** [comment]
@ymatsiuk thanks for the pointer and indeed this has solved my issue. For others finding this, I installed the `pinentry-curses` package on a Debian distro then added the following to my shell config.

```bash
which pinentry-curses &> /dev/null && \
  export LPASS_PINENTRY=pinentry-curses
```
