### ISSUE TITLE
force ipv4 function

### ISSUE THREAD

**Issue by umop3plsdn** [lastpass/lastpass-cli#440]
For some reason in my Arch Install anything that uses curl or wget automatically tries to use ipv6 and creates a pause for 15+ seconds until it can timeout and rollback to ipv4. This is fixed by putting curl -4 or whatever. I'm just wondering if you know where the references to this would be in this application? Where I could at least manually hardcode the -4. It is painful to use this and almost every command I have to wait 15+ seconds at least to get a result. From login to ls.

**Comment by umop3plsdn** [comment]
i'm sure i'm not the only one that suffers form this. Even an argument --force-ipv4 or something would be amazing!

**Comment by waterkip** [comment]
What happens when you do this? `CURLOPT_IPRESOLVE=CURL_IPRESOLVE_V4` ?
