### ISSUE TITLE
Cannot login with microsoft authenticator 2fa

### ISSUE THREAD

**Issue by sumitsahrawat** [lastpass/lastpass-cli#442]
Using `lpass login <email>`, I'm asked to fill in the master password. Once I fill it in, the same window opens up again but this time it has a message in red saying 'Microsoft authenticator authentication required`. Filling in the code from the authenticator gives an invalid password message.

**Comment by sumitsahrawat** [comment]
```
~
λ lpass -v
LastPass CLI v1.3.1
```

**Comment by TimKillingsworth** [comment]
@sumitsahrawat ,

You may try clearing your cached blob under your profile using this command and then attempt it again. 

rm -rf ~/.lpass

Once you do this then it will take a new token and should resolve your issue. Note you may have to sudo or switch to the root account then go to your profile. 

TK

CC: @bcopeland

**Comment by sumitsahrawat** [comment]
Hello @TimKillingsworth,

The file/dir `~/.lpass` didn't exist for me. So I found out all files related to `lpass` and deleted them:

```
find . | grep lpass | xargs sudo rm -rf
```

- Sumit

**Comment by sumitsahrawat** [comment]
I also tried building from git, nothing works.

**Comment by rkirkpat** [comment]
On a fresh install of MacOS Mojave, brew installed lastpass-cli, it is version 1.3.1, and I too am unable to login with Microsoft Authenticator as second factor. I enter my master password with the prompt (with or without pinentry enabled), and then get a message that Microsoft Authenticator code is required but no way to enter it, the prompt is simply for the master password again. Is there a second factor app that does work with lpass CLI?

**Comment by sumitsahrawat** [comment]
Apparently there is some issue with last pass' interaction with Microsoft authenticator. I disabled it but it did not even disable properly, so I had to get it disabled through customer support.

Google authenticator should work.

**Comment by tmrtkn** [comment]
I also have this problem.

I built the lpass from git: LastPass CLI v1.3.2.9.gb838abc

**Comment by jmvalente** [comment]
I'm also having the issue, installed got Homebrew

LastPass CLI v1.3.3.GIT

Correctly entering the password returns the Master Password Prompt a red line stating that Microsoft Authenticator is required. Entering the code from the Authenticator app also doesn't work as it (correctly) returns that my password is invalid.

My account history doesn't record any failed logins except for the cases where I try to enter the code in the password field.

**Comment by cerebrate** [comment]
Exact same issue here; LastPass CLU v1.3.1, installed from the Debian buster package.

**Comment by marshel12** [comment]
Actually i also have an issue with LastPass , where yesterday i had to reset my mobile , and i reinstalled all the apps. Now the problem is that i lost the Microsoft Authenticator configurations , and i had to start again from scratch because it doesnt have any login in such apps , you just have to scan the QR. And now i am stuck , i know my master password , but cant go through because of the authenticator , and whenever i request to rest the password i can recieve the code by sms , but also cant get through. Also if i request to disable the authenticator , to access my vault then a message will appear , (lastpass microsoft authenticator authentication is currently not enabled for your account).
I sent an email for support@lastpass.com and still no one replied back.

Anyone have any idea what to do with this issue guys??

**Comment by bcopeland** [comment]
On Sat, Jul 27, 2019 at 11:12:43PM -0700, marshel12 wrote:
> Actually i also have an issue with LastPass , where yesterday i had to reset
> my mobile , and i reinstalled all the apps. Now the problem is that i lost
> the Microsoft Authenticator configurations , and i had to start again from
> scratch because it doesnt have any login in such apps , you just have to scan
> the QR. And now i am stuck , i know my master password , but cant go through
> because of the authenticator , and whenever i request to rest the password i
> can recieve the code by sms , but also cant get through. Also if i request to
> disable the authenticator , to access my vault then a message will appear ,
> (lastpass microsoft authenticator authentication is currently not enabled for
> your account).

I can't speak to the authenticator issues, but if you have the blob
already cached with lastpass-cli, you can still use lastpass-cli in
offline mode.  Just don't do `lpass login` -- instead pass `--sync=no`
to `lpass ls` or `lpass show`.  As long as you have a copy of the blob,
you can do this without ever hitting lastpass' servers.

-- 
Bob Copeland %% https://bobcopeland.com/

**Comment by ede-n** [comment]
Even though the fix was merged, a new version of cli hasn't been released, so one would have to install from `master`. Until then, one may use this command to install, for Mac based installation.

```
brew install lastpass-cli --HEAD
```

**Comment by olive007** [comment]
Anyone know when this fix will be release on the Linux packages ?
