### ISSUE TITLE
Request: login to multiple accounts e.g. work account and personal account

### ISSUE THREAD

**Issue by nitrocode** [lastpass/lastpass-cli#445]
Hi. It would be nice if there was a way to switch between lastpass accounts.

For now, I do this using browser profiles and the lastpass plugin. It would be nice if there was a way to set profiles on my commandline without having to run a docker container to login and access different accounts.

**Comment by CyberLeo** [comment]
It's possible to do so, but you must reauthenticate after every switch.

Log into each account one at a time, and save the contents of `~/.local/share/lpass` someplace descriptive. After you have directories for each account, use a symlink to point `~/.local/share/lpass` to your desired account, and then `pkill lpass` or otherwise terminate the lpass agent to switch to the new account.

**Comment by nitrocode** [comment]
Yes, I know I could do something like this manually but why not have something similar to aws-vault and awscli built in using

```bash
$ lpass add profile personal myname@gmail.com
Password: 
2fa: 039430
Authentication of myname@gmail.com successful and lpass profile "personal" added.
$ lpass add profile company myname@company.com
Password: 
2fa: 993382
Authentication of myname@company.com successful and lpass profile "company" added.
$ lpass --profile personal ...
$ lpass --profile company ...
```

Or lpass could have some kind of env token like `LPASS_TOKEN` that could then be saved into profiles and used on-the-fly like the vault cli project.

```
$ lpass login to personal
$ export LPASS_PERSONAL_TOKEN=LPASS_LOGIN
$ lpass login to company
$ export LPASS_COMPANY_TOKEN=LPASS_LOGIN
$ LPASS_LOGIN=LPASS_PERSONAL_TOKEN lpass ...
$ LPASS_LOGIN=LPASS_COMPANY_TOKEN lpass ...
```

**Comment by martini97** [comment]
@nitrocode I think I got it working by using aliases overriding `$LPASS_HOME`, it's not a clean fix but is a good workaround

**Comment by nitrocode** [comment]
That's a great workround @martini97 .

Another way around it is to add your other LastPass accounts to a parent account and then you can access all the credentials through the parent account which is what I do now.
