### ISSUE TITLE
Struggling with lpass share create SHARE and lpass add command 

### ISSUE THREAD

**Issue by gedion** [lastpass/lastpass-cli#446]
Can someone please help me create a set of lpass commands to be able to create shared folders and notes with below structure. I'm not able to get any consistent behavior whatsoever with v1.3.1

* Shared-Food Secrets
  * Fruits
    * dev
  	  * fruit_dev.secrets
	* test
	  * fruit_test.secrets
  * Veggies
	* dev
	  * veggies_dev.secrets
  	* test
	  * veggies_test.secrets      
  * Dairy
	* dev
	  * dairy_dev.secrets
	* test
	  * dairy_test.secrets

**Comment by Kelmey** [comment]
I am having the same issue. I can't figure out how to do anything inside a shared folder.

The LPASS manual is dreadfully vague in several areas, mainly around shared folders.

**Comment by MeOnGitHub123** [comment]
not sure if this really help or if you already have seen #305
