### ISSUE TITLE
macOS Mojave segmentation faults and malloc errors

### ISSUE THREAD

**Issue by schultz-texas** [lastpass/lastpass-cli#447]
I've been seeing a couple intermittent errors when using `lastpass-cli` on macOS Mojave.

One issue is a segfault:
```
% lpass show -c --password <ACCOUNT>
zsh: segmentation fault  lpass show -c --password <ACCOUNT>
```

The other appears to be a malloc issue:
```
% lpass show -c --password <ACCOUNT>
lpass(27361,0x11655b5c0) malloc: *** error for object 0xec83485354415541: pointer being freed was not allocated
lpass(27361,0x11655b5c0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      lpass show -c --password <ACCOUNT>
```

This seems to occur both with the prepackaged Homebrew binary and with a locally compiled binary. Happy to provide more context or dig in further if needed.

**Comment by cmcfadden** [comment]
More discussion in #427

**Comment by schultz-texas** [comment]
Whoops. Good catch. Not sure how I missed that in search. Going to close this one in favor of that one.
