### ISSUE TITLE
v1.3.2 tag

### ISSUE THREAD

**Issue by msbit** [lastpass/lastpass-cli#453]
Looks like https://github.com/lastpass/lastpass-cli/commit/df182dd7c04715f1b18f5ff3a8074e198fc1d06c is a good candidate for a v1.3.2 tag.

**Comment by waterkip** [comment]
I support e new version as well. Many things have changed and a newer version would be welcome I think :)

**Comment by msbit** [comment]
Closing as we now have the tag.
