### ISSUE TITLE
Terminal option for typing account password

### ISSUE THREAD

**Issue by fredaas** [lastpass/lastpass-cli#456]
When logging in with `lpass login <email>`, a GUI-box pops up for the user to insert the account password.

This seems a little unnecessary since the entire application in CLI-based with the exception of the field where you insert the account password.

I propose two solutions:

1. Remove the GUI element for inserting the account password and replace it with a CLI-based alternative.
2. Add an CLI-based option which makes it possible to choose between the two.

If this sound like a good idea, please let me know and I'll help contribute to add the functionality.

**Comment by apiology** [comment]
@fredaas - This info should resolve your issue: https://github.com/lastpass/lastpass-cli/blob/master/lpass.1.txt#L78

**Comment by fredaas** [comment]
@apiology Thanks! Somehow my brain managed to overlook that section in the man page. Closing issue.
