### ISSUE TITLE
`lpass logout` prompts for password when session is stale

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [lastpass/lastpass-cli#477]
Repro steps:
1) authenticate with lpass cli
2) wait for session to expire (i.e. the next `lpass show` should reprompt for password, `lpass status` returns "Not logged in.")
3) `lpass logout -f`

Expected Behaviour:
lpass should clear any session information from memory, or if no session information is present should no-op

Actual Behaviour:
lpass prompts to reauthenticate

Additional observation:
`lpass logout` can distinguish between 'logged out' and 'expired session' (it either prompts for confirmation or displays "Error: Not currently logged in.") but `lpass status` does not distinguish between these two scenarios (returns "Not logged in." with exit code 1 in both cases).

My use case is a script to log me out of assorted CLIs at the end of the day. I don't want the script to require interaction, but I currently have to sign in to lastpass so that I can sign out of lastpass. In addition, the current behaviour of `lpass status` means I can't query if I'm truly logged out before 
calling `lpass logout`.

```
$ lpass --version
LastPass CLI v1.3.1
$ lpass login user@email
# wait for expiry
$ lpass status
Not logged in.
$ echo $?
1
$ lpass logout -f
# password prompt displayed, select 'cancel'
Error: Could not find decryption key. Perhaps you need to login with `lpass login`.
$ lpass logout -f
# password prompt displayed, enter password
Log out: complete.
$ lpass status
Not logged in.
$ echo $?
1
$ lpass logout
Error: Not currently logged in.
```

**Comment by waterkip** [comment]
Could you test my branch: gh-477-logout_should_not_require_a_login
