### ISSUE TITLE
Fail to copy bash_completion when `PREFIX=/usr/local`

### ISSUE THREAD

**Issue by darcyparker** [lastpass/lastpass-cli#478]
I need to install to `/usr/local/` and do not want to install `bash-completion` to `/usr/share/bash-completion/completions` as `sudo` or `root`.  So I am setting the `PREFIX` and other environment variables like this:

```bash
  export PREFIX=/usr/local
  export BINDIR=/usr/local/bin
  export LIBDIR=/usr/local/lib
  make
  make install
```

But I get this error:
```
-- Install configuration: ""
-- Installing: /usr/local/bin/lpass
-- Installing: /usr/share/bash-completion/completions/lpass
CMake Error at cmake_install.cmake:60 (file):
  file INSTALL cannot copy file
  "/home/darcy/src/lastpass-cli/contrib/lpass_bash_completion" to
  "/usr/share/bash-completion/completions/lpass".
```

It appears the `cmake` configuration is not using `PREFIX` env like other parts of the build.

**Comment by waterkip** [comment]
Hi, see https://github.com/lastpass/lastpass-cli/issues/413

**Comment by darcyparker** [comment]
@waterkip - thanks for the suggestion of looking at #413. I commented there... I don't think `sudo make install` is a suitable solution. Giving `sudo` let's `make install` copy the one file to `/usr`.  But if `$PREFIX` is set to `/usr/local`, then `lastpass-cli/contrib/lpass_bash_completion" should be copying to 
`/usr/local/share/bash-completion/completions/lpass` and not `/usr/share/bash-completion/completions/lpass`.  All of the other files being installed are using $PREFIX.  I think there is an oversight in not using `$PREFIX` for this one file.

**Comment by waterkip** [comment]
Aha, I see what you mean. I see in the CMakeLists.txt file that they query pkg-config like so:

```
root@2118ec79749c:/tmp/build# pkg-config --variable=completionsdir bash-completion
/usr/share/bash-completion/completions
```

This is done on line 39 `pkg_check_variable(bash-completion completionsdir)`
And later on line 72-75: 
```
if(BASH_COMPLETION_COMPLETIONSDIR)                                                  
install(FILES contrib/lpass_bash_completion DESTINATION ${BASH_COMPLETION_COMPLETIONSDIR} RENAME lpass)    
endif
```

**Comment by waterkip** [comment]
I have a fix, the commit is rather large because I was learning a bit of Cmake, but if you can test/check my branch `gh-478-bash-completions` and test it. I'll make a PR and see if the maintainer wants this or want me to tone it down a bit.

**Comment by darcyparker** [comment]
@waterkip - Looks great. I added your fork as a remote, and tried branch `gh-478-bash-completions`. It installs nicely now.  Thanks for this fix. Look forward to seeing your pull request and hope it gets merged.

**Comment by waterkip** [comment]
Thanks! Now we wait :)
