### ISSUE TITLE
`lpass show <entry>` displays duplicate entries

### ISSUE THREAD

**Issue by fredaas** [lastpass/lastpass-cli#495]
Normally when doing `lpass show <entry>`, username, password, and url is shown. However, some entries show duplicate password fields and an email field which, as far as I know, is not possible to set neither in the CLI nor the standard web interface. See image below for an example.

Why this behavior? And where does the email field come from?

![amazon_hidden](https://user-images.githubusercontent.com/10281443/54865552-3e145180-4d67-11e9-99e9-54c4f5eb6381.png)

**Comment by waterkip** [comment]
This is due to the UI on the web and/or the lastpass browser extension which add these fields over and over again.

Related #392

**Comment by fredaas** [comment]
This is still an issue.

**Comment by fredaas** [comment]
This is still an issue.

**Comment by fredaas** [comment]
The project is discontinued. (See #600.) Closing.
