### ISSUE TITLE
Update homebrew version to 1.3.2

### ISSUE THREAD

**Issue by kossmoboleat** [lastpass/lastpass-cli#497]
Homebrew still has version 1.3.1 as the latest one and the new curl segfault fix would be nice to get to everybody.

https://formulae.brew.sh/formula/lastpass-cli

**Comment by waterkip** [comment]
I think you should file this against homebrew and not this repo: https://github.com/Homebrew/homebrew-core/blob/master/Formula/lastpass-cli.rb

**Comment by kossmoboleat** [comment]
I've tried opening the PR myself, which seems quite easy, but I noticed that for the 1.3.2 release there was only only a source code attachment and no .tar.gz/.zip of the binaries?

If that download existed I assume the whole update would be a single command:
`brew bump-formula-pr --url https://github.com/lastpass/lastpass-cli/archive/v1.3.2.tar.gz lastpass-cli`

**Comment by waterkip** [comment]
I think that should do the trick. The formula depends on cmake, so I guess that is builds it from source. Previous releases didn't ship the binary afaik. https://github.com/lastpass/lastpass-cli/releases just shows that they may or may not include a pristine tarball/zip of the repo at that release. Which should be non-blocking for your PR.

**Comment by GPaulovics** [comment]
Hey I'll upload the tarball/zip right away. Sorry for missing that.

**Comment by GPaulovics** [comment]
I've uploaded the tarball/zip. Thank you for reminding me.
