### ISSUE TITLE
segmentation fault attempting to login on OSX (10.8.5)

### ISSUE THREAD

**Issue by acyuta108** [lastpass/lastpass-cli#50]
[1]    16677 segmentation fault  lpass login MY_USERNAME

I attempted with all the flags as well.

OSX 10.8.5
Installed with homebrew (0.9.5)
Tested in iTerm, Terminal.
Tested in zsh/sh/bash

**Comment by bcopeland** [comment]
Did you get a chance to test 10.9 or better?

**Comment by nickjwebb** [comment]
@bcopeland yes, I'm on mavericks now and it is not an issue. This seems specific to 10.8.x, or maybe even just 10.8.5.

**Comment by bcopeland** [comment]
Ok - I think I'm going to consider this a third-party library issue, and close it as such, unless someone can point to a bug in how we're using `SSL_CTX_set_cert_store()`.

**Comment by nickjwebb** [comment]
Thanks @bcopeland for looking at this! Most folks aren't on 10.8 anymore, should be fairly safe to close.
