### ISSUE TITLE
change users email addr

### ISSUE THREAD

**Issue by MeOnGitHub123** [lastpass/lastpass-cli#508]
hey, is there a way to change the email of users ? 

running lastpass in enterprise but as we changing our domain it will be very helpful to update users email in commandline instead GUI

checked e.g. #445 however lpass --profile seems not existing

**Comment by LuL1ll0** [comment]
Users can only change their email address themselves. They always must be a part of that process, as their email address is used as salt for vault encryption, [see here](https://lastpass.com/support.php?cmd=showfaq&id=1116), meaning their vault must first be in a decrypted state before the email address can be changed. 

The only way I know to automate this is by using the LastPass AD Connector-- that tool caches the mail attribute of the user-object, and when this attribute is changed in AD, LastPass will send that user an email, notifying them that they need to login into their vault and change their email address.
