### ISSUE TITLE
Error: Unable to fetch blob. Either your session is invalid and you need to login with `lpass login`, you need to synchronize, your blob is empty, or there is something wrong with your internet connection.

### ISSUE THREAD

**Issue by eikeschott** [lastpass/lastpass-cli#510]
OS: Linux Mint 19.1 Tessa x86_64
LastPass CLI v1.3.2.GIT

I'm getting this error message lately and I don't know how to resolve it. Some hints would be appreciated.

```
ls ~/.lastpass
drwxr-xr-x  user  user       -   Mon Apr  1 16:42:11 2019  🗁  pipes/
drwxrwxr-x  user  user       -   Mon Apr  1 11:28:49 2019  🗁  tmp/
.rw-rw-r--  user  user  2.1 KB  Sat Jun  1 19:34:20 2019  🗋  a75847593c14d759bcfabad5fe5fe56729e44461ce6497fc4f420e6393c4a3d8.sch
.rw-rw-r--  user  user   133 B   Sun May 26 10:04:33 2019  🗋  a75847593c14d759bcfabad5fe5fe56729e44461ce6497fc4f420e6393c4a3d8_lpall.slps
.rw-rw-r--  user  user    63 B   Sat Apr 20 17:42:23 2019  🗋  lp.suid
.rw-rw-r--  user  user  134 B   Sat Apr 20 17:42:23 2019  🗋  lp.suids
.rw-rw-r--  user  user  62.5 KB  Mon Apr  1 16:42:24 2019  🗋  words.dic
```

`lpass status` says that I'm logged in with the correct e-mail address and `lpass sync` gives no output but seems to do something.
Please let me know which information I can provide to narrow down the problem.

**Comment by waterkip** [comment]
Do you still have this issue?

I encountered this issue today as well. I think the call to lastpass servers is timing out. Subsequent requests work well.

**Comment by eikeschott** [comment]
Thanks for your reply.

This issue still persists. Typing `lpass ls` for example will give me the error message while `lpass status` says that I'm logged in.

A workaround I found is to logout with `lpass logout` and log back in with `lpass login USERNAME`.
After confirming the two factor authentication on my phone my passwords and entries are shown as expected.
So I assume it has something to do with an expired 2FA confirmation.

**Comment by waterkip** [comment]
For the purpose of testing, could you confirm this behavior is present with the `--trust` option when you login? `lastpass login --trust $USERNAME`

**Comment by eikeschott** [comment]
Logging in with the `--trust` option seems to have solved the issue. I haven't got the Error message since logging in any more.
I'll report back when it happens again.

**Comment by eikeschott** [comment]
I think this issue can be closed. The `--trust` option fixed it for me.

**Comment by travispaul** [comment]
Even if `--trust` works it still seems like reporting that the user is logged in when they can't make requests would be a bug.
