### ISSUE TITLE
Support for WSL with clip.exe

### ISSUE THREAD

**Issue by AndrewKassab** [lastpass/lastpass-cli#524]
I want to use lastpass-cli with my WSL terminal but unfortunately since WSL can't open graphical programs, xclip does not work. I copy things to my clipboard on WSL using clip.exe which functions just the same as using xclip so I assume it wouldn't be out of the realm to implement.

**Comment by AndrewKassab** [comment]
Also, even when setting LPASS_CLIPBOARD_COMMAND in my enviornment as clip.exe, I still don't hit the if(clipboard_command) block.

**Comment by zpeschke** [comment]
I'm a bit late to the party, but setting the clipboard to clip.exe works for me on WSL 2.

`export LPASS_CLIPBOARD_COMMAND="clip.exe"`
