### ISSUE TITLE
edit doesn't accept multiple fields or key values

### ISSUE THREAD

**Issue by rothgar** [lastpass/lastpass-cli#55]
When trying to edit an entry I cannot edit multiple fields in one command.

```
lpass edit --url --username example.com
```

The above example just returns to the command prompt. I also tried specifying values

```
lpass edit --url=example.com --username=rothgar example.com
```

But I'm returned an error that the `edit: option '--url' doesn't allow an argument`. I think there needs to be an easier way to edit multiple values for an entry.

I also tried --non-interactive but I still had the same result.

**Comment by bcopeland** [comment]
This is now supported in the latest head, although not by specifying values or multiple options; you can do it via just:
```
lpass edit example.com
```
Which will then bring up a buffer with labels for you to edit.
