### ISSUE TITLE
edit doesn't edit existing entry. Adds new entry instead

### ISSUE THREAD

**Issue by rothgar** [lastpass/lastpass-cli#56]
When creating a new entry I used the follow commands.

```
lpass edit --url example
lpass edit --password example
lpass edit --username example
```
Please see issue #55 opened to help with the redundant commands

After the three commands and running `lpss sync` the following entries show up in my vault

![](http://imgur.com/N9yP1QL.png)

Each entry has all the content from the previous entry plus the new field. The old entries are not removed.

**Comment by bcopeland** [comment]
This no longer seems to be the case; at least I could not reproduce as written, but there have been a number of changes over the last year.  If this is still an issue, please reopen.
