### ISSUE TITLE
Is this project still being actively maintained?

### ISSUE THREAD

**Issue by gktrk** [lastpass/lastpass-cli#595]
Hi,

The latest release (v1.3.3) was back in 2019. There are 160 open issues and 24 pending pull requests. The latest commit to the master branch is more than a year old.

Is this project still being actively maintained?

Thanks,

**Comment by tamsky** [comment]
Would this be a good time to mention there appears to be an active fork at:
- https://github.com/lastpass-cli-fork/lastpass-cli
?

**Comment by gktrk** [comment]
> Would this be a good time to mention there appears to be an active fork at:
> 
> * https://github.com/lastpass-cli-fork/lastpass-cli
>   ?

I'd be reluctant to go with a fork primarily because there's no guarantee that the server API will remain stable or compatible without official support. I would hate to find myself unable to access my password all of a sudden because the parameter to a POST needs to be a little different now. It's better to either use the officially supported platforms for lastpass or migrate to a different password manager.

**Comment by fredaas** [comment]
Any news on this? Just opened #600 before noticing that there are several similar issues like this pending without any response. I've been unable to find any official statement from LastPass about the current state of the project.

**Comment by fredaas** [comment]
See #600 for a reply from a LastPass representative about the matter.

**Comment by rsyring** [comment]
New reply from Lastpass staff: https://github.com/lastpass/lastpass-cli/issues/602#issuecomment-832609246

@balintsera or @gktrk can you close this issue as it's a dupe of #602 which has the most recent response?

**Comment by gktrk** [comment]
Dupe of #602
