### ISSUE TITLE
Is this repo being updated?

### ISSUE THREAD

**Issue by mick-t** [lastpass/lastpass-cli#598]
Hi Lastpass authors,

Thank you for your great tool. The last commit was in 2019, is this repo still maintained and is it safe to provide to end-users?

Thanks
--Mick

**Comment by fredaas** [comment]
See #600 for a reply from a LastPass representative about the matter.

**Comment by rsyring** [comment]
New reply from Lastpass staff: https://github.com/lastpass/lastpass-cli/issues/602#issuecomment-832609246

@balintsera or @mick-t can you close this issue as it's a dupe of #602 which has the most recent response?

**Comment by mick-t** [comment]
See #602
