### ISSUE TITLE
Cannot compile on cygwin

### ISSUE THREAD

**Issue by chrissten** [lastpass/lastpass-cli#599]
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/cmd-login.c.o:cmd-login.c:(.bss+0x0): multiple definition of `ARGC'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/cmd-login.c.o:cmd-login.c:(.bss+0x8): multiple definition of `ARGV'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x8): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/cmd-share.c.o:cmd-share.c:(.bss+0x0): multiple definition of `ARGC'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/cmd-share.c.o:cmd-share.c:(.bss+0x8): multiple definition of `ARGV'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x8): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/cmd.c.o:cmd.c:(.bss+0x0): multiple definition of `ARGC'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/cmd.c.o:cmd.c:(.bss+0x8): multiple definition of `ARGV'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x8): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/lpass.c.o:lpass.c:(.bss+0x0): multiple definition of `ARGC'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/lpass.c.o:lpass.c:(.bss+0x8): multiple definition of `ARGV'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x8): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/process.c.o:process.c:(.bss+0x0): multiple definition of `ARGC'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/process.c.o:process.c:(.bss+0x8): multiple definition of `ARGV'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x8): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/upload-queue.c.o:upload-queue.c:(.bss+0x0): multiple definition of `ARGC'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/upload-queue.c.o:upload-queue.c:(.bss+0x8): multiple definition of `ARGV'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x8): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/util.c.o:util.c:(.bss+0x0): multiple definition of `ARGC'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/lpass.dir/util.c.o:util.c:(.bss+0x8): multiple definition of `ARGV'; CMakeFiles/lpass.dir/agent.c.o:agent.c:(.bss+0x8): first defined here

**Comment by arpan3t** [comment]
#532 

Edit lines 7 & 8 in process.h to make variables static -> save -> make install

**Comment by sverhagen** [comment]
I needed to do this on Linux too.

**Comment by MrPeteH** [comment]
Currently still an issue. Same errors. Same workaround. (Messy -- "defined but not used" warning)

**Comment by arpan3t** [comment]
I personally wouldn't waste your time putting effort into LastPass. I think everyone has jumped ship, and don't see this project getting any updates.

**Comment by TiborKLP** [comment]
Change applied in d23846481066ea0a617a7338a3529e78b2eb517a

**Comment by MrPeteH** [comment]
> I personally wouldn't waste your time putting effort into LastPass. I think everyone has jumped ship, and don't see this project getting any updates.

Obviously not "everyone" ;) ... I find significant value here. Yes, there be bugs. ALL software has bugs. LP has the significant advantage of having been seriously banged on....

**Comment by arpan3t** [comment]
> > I personally wouldn't waste your time putting effort into LastPass. I think everyone has jumped ship, and don't see this project getting any updates.
> 
> 
> 
> Obviously not "everyone" ;) ... I find significant value here. Yes, there be bugs. ALL software has bugs. LP has the significant advantage of having been seriously banged on....

I'm glad you find significant value in LastPass! Use the tools you like.  For me, and a lot of other people, the way LastPass handled their breach and prior to that, the lack of activity in this repo (i.e., this issue took 3 years to close) is why we moved on to other password managers.
