### ISSUE TITLE
Project discontinued?

### ISSUE THREAD

**Issue by fredaas** [lastpass/lastpass-cli#600]
Just noticed that the last release was tagged on April 15, 2019 (v1.3.3). As there is currently a non-negligible amount of pending issues it seems fair to ask, is the project still under active development and safe to use?

**Comment by fredaas** [comment]
There are currently several open issues asking the same question with no response (#598, #595). Please provide a statement on the current status of the project. @bcopeland

**Comment by bcopeland** [comment]
I am not personally working on this at this time, nor do I actually have any commit access to this repo.  As for the project itself: I have no idea, as I haven't worked at LastPass for 3 years.  Feel free to fork if the current maintainers are being unresponsive.

**Comment by fredaas** [comment]
@bcopeland Perhaps I'll send a mail to LastPass support to figure out what's going on. I just assumed there would be more activity here since this is the official LastPass GitHub. Thanks for clarifying.

**Comment by bcopeland** [comment]
Thanks!  That would probably be the best approach to take at the moment - please update us all what you find.

**Comment by fredaas** [comment]
So, I got this reply from one of LastPass' representatives. The reply doesn't really address the questions I had, but either way it seems like the project is abandoned. So I guess it's time to look for alternative solutions :man_shrugging:

![image](https://user-images.githubusercontent.com/10281443/114533540-455c6f80-9c4e-11eb-93c7-d63c62e78ea6.png)
