### ISSUE TITLE
Unable to login with master password

### ISSUE THREAD

**Issue by sshahar1** [lastpass/lastpass-cli#606]
I am using the lastpass-cli on my mac:
brew info lastpass-cli
lastpass-cli: stable 1.3.3 (bottled), HEAD
MacOs Big Sur 11.3.1 (20E241)

This week for no apparent reason, when I try to login with the master password, after entering the password and clicking okay, I am thrown back to the login screen.

The master password has not changed, and I am able to use it in the browser's extension.

Scenario:

1. lpass login <my email>
2. Enter master password
3. Click OK

Expected behavior:
Login success

Actual behavious:
Error in login screen:  Review your login info and try again. If you think you entered valid info, check your email to verify login.

**Comment by mjbroekman** [comment]
Check #604 to make sure it's not a case of the 'iterations' on your account being set to something other than `100100` 

This is in Account Settings => Advanced Settings => Password Iterations

It was discovered that, among other things, the communication back from iterations.php changed and resulted in the initial login part failing. There are a number of workarounds, but the most reliable one is to set your "Password Iterations" to 100100.

**Comment by sshahar1** [comment]
@mjbroekman Thank you, it works :-)
