### ISSUE TITLE
How Can I share a folder with another user?

### ISSUE THREAD

**Issue by bidresam** [lastpass/lastpass-cli#610]
I tried using the below lpass CLI commands but it doesn't work. Any help is appreciated 

lpass share create test --> created shared folder 
lpass mv "Secure Notes/Super Secret Note" test --> moved the secure note to the folder
lpass share useradd test <useremailaddress> --> Tried adding user to the folder
 
I'm getting error as Error: Share test not found

I got the above commands from https://github.com/lastpass/lastpass-cli/issues/155

Is there a change in the command usage or am I doing something wrong to share a folder with another user? I looked thru the documentation but couldn't find anything.

**Comment by RevHokan** [comment]
I just tested a bit and this worked:

lpass share create XXXX
lpass share useradd Shared-XXXX  user@domain.tld

Note the folder name difference.

This sent an email to user@domain.tld asking for confirmation that they accept the share.

**Comment by bidresam** [comment]
Thanks for taking a look at this and for the response @RevHokan .I realised that I was on a trial user account of lastpass which is the reason for my issue.
