### ISSUE TITLE
CLI not showing credentials in specific Shared-Folder

### ISSUE THREAD

**Issue by AdamPZsolace** [lastpass/lastpass-cli#615]
Hi world,

I couldn't get a company shared folder to show me any of the credentials through the CLI that i could see in the web browser.

Saw some other people post about this online and want to share my solution. Seems the folder was automatically set to "hidden" in the CLI for some reason but fixed it with

lpass share usermod --hidden=false folderName userName

Cheers !

**Comment by mo5h** [comment]
Hmm, didn't work for me, when I attempted it I got an error:

Error: Unable to find user *redacted account email* in the user list
