### ISSUE TITLE
Lastpass CLI actively being denied by Logmein?

### ISSUE THREAD

**Issue by larrypl** [lastpass/lastpass-cli#616]
I'm now getting
``` 
$ LPASS_DISABLE_PINENTRY=1 lpass login <obscured>
Please enter the LastPass master password for <obscured>.

unknown
Master Password:
```
and with the fork, same thing
```
$ LPASS_DISABLE_PINENTRY=1 ./build/lpass login <obscured>
Please enter the LastPass master password for <obscured>.

unknown
Master Password:
```
This happens regardless of whether the correct email address/password is entered.
Using brew lastpass package on MacOS Big Sur 11.6. May be a kext problem?

**Comment by Chreo** [comment]
I'm getting the same error on fresh install of Ubuntu 21.04 (hirsute) today

**Comment by kellya** [comment]
Getting the same on Fedora from the git version that was compiled when it was last updated 2 years ago.

**Comment by kellya** [comment]
This looks like it is the same as issue #604 That issue has a work-around in place which worked for me.

**Comment by larrypl** [comment]
That's exactly what the problem was. Thanks!
