### ISSUE TITLE
Failed to enter correct password

### ISSUE THREAD

**Issue by mhk-ableton** [lastpass/lastpass-cli#622]
I've been trying to login using lpass and for some reason it says my Master Password is incorrect with the following message: `Failed to enter correct password.`.  I've verified I'm using the correct master password.

I've tried to call `login` multiple ways:
```
lpass login <email>
LPASS_DISABLE_PINENTRY=1 lpass login <email>
LPASS_DISABLE_PINENTRY=1 lpass login --force --trust <email>
```

None of these seem to work. It says my Master Password is the reason but I know this not to be the case.

**Comment by cys2best** [comment]
same to me, i can't use this anymore

**Comment by Leikor** [comment]
Same here, though it's been several month now. The login screen just prompt for more "unknown" passwords.

**Comment by dyerseve** [comment]
Possible Duplicate of #[605 Fix iterations.php requests for login](https://github.com/lastpass/lastpass-cli/issues/604)

**Comment by mhk-ableton** [comment]
The workaround described in #605 fixed the issue on my machine.
