### ISSUE TITLE
Question: what is the "id" for the `-i` flag in the lpass-att-export.sh script?

### ISSUE THREAD

**Issue by sethgoldin** [lastpass/lastpass-cli#645]
Hey there, trying to understand how to properly execute the [lpass-att-export.sh](https://github.com/lastpass/lastpass-cli/blob/master/contrib/lpass-att-export.sh) script, but I'm not understand what the "id" is referring to for the `-i` flag. Is that the numerical account ID of the LastPass account, or a particular entry? Is it something else? How do I locate the "id?"

**Comment by 0xdevalias** [comment]
You can see the code here:

https://github.com/lastpass/lastpass-cli/blob/a5b93b9015e1524f557e3eb4fdf688a407d41c73/contrib/lpass-att-export.sh#L49-L56

It's the `id` of a lastpass entry, it's used as: `lpass show ${id}`

**Comment by sethgoldin** [comment]
Perfect, thank you!
