### ISSUE TITLE
Lastpass 0.3.0 not allowing me Export option

### ISSUE THREAD

**Issue by thomascoreapps** [lastpass/lastpass-cli#65]
I am on the latest and greatest OSX.  I have installed from this repository.

I do not get the lpass export option required to make something I want to work.  What have I done wrong, or what should I do to troubleshoot further?

Arbiter:.ssh thomasdenton$ lpass --version
LastPass CLI v0.3.0
Arbiter:.ssh thomasdenton$ lpass
Usage:
  lpass {--help|--version}
  lpass login [--trust] [--plaintext-key [--force, -f]] USERNAME
  lpass logout [--force, -f]
  lpass show [--sync=auto|now|no] [--clip, -c] [--all|--username|--password|--url|--notes|--field=FIELD|--id|--name] {UNIQUENAME|UNIQUEID}
  lpass ls [--sync=auto|now|no] [GROUP]
  lpass edit [--sync=auto|now|no] [--non-interactive] {--name|--username|--password|--url|--notes|--field=FIELD} {NAME|UNIQUEID}
  lpass generate [--sync=auto|now|no] [--clip, -c] [--username=USERNAME] [--url=URL] [--no-symbols] {NAME|UNIQUEID} LENGTH
  lpass duplicate [--sync=auto|now|no] {UNIQUENAME|UNIQUEID}
  lpass rm [--sync=auto|now|no] {UNIQUENAME|UNIQUEID}
  lpass sync [--background, -b]
Arbiter:.ssh thomasdenton$

**Comment by steakejjs** [comment]
This is totally a stupid question but have you done a pull in a while? LastPass with export is v0.3.0 and LastPass before export was also v0.3.0.

**Comment by thomascoreapps** [comment]
Well that is a neat trick there.  I just nuked my install, re-cloned, re-installed for like the 8th time and I have export! It was not a stupid question after all.

**Comment by steakejjs** [comment]
That's good. You shouldn't need to reclone though, in the future. Just need to do a git pull to pull in the newer code
