### ISSUE TITLE
LC_CTYPE problems when running with $LANG set

### ISSUE THREAD

**Issue by athompso** [lastpass/lastpass-cli#67]
When running with LANG=en_CA.UTF-8, I see an unusual problem (possibly from pinentry?) when I run "lpass login".  See attached screenshot.
![screenshot from 2015-01-11 11 08 37](https://cloud.githubusercontent.com/assets/887417/5696056/1a292a70-9984-11e4-92fb-8a41caa1d13d.png)

I am utterly unable to reproduce this with pinentry *other* than by running "lpass login", so I can't tell you why this occurs, sorry.

**Comment by bcopeland** [comment]
Hi, please see if 1930bb6b1181ace5cc047f474ea53922ff03446e fixed that for you.

**Comment by davbritt** [comment]
I got the same error, it would give me the following output after the login failed : 
ry-curses: no LC_CTYPE known - assuming UTF-8
pinentry-curses: no LC_CTYPE known - assuming UTF-8
Segmentation fault: 11

I cloned the latest version of this repo and it works just as expected.
But the version on brew is still reproducing this error.

**Comment by bcopeland** [comment]
Closing this as the latest version in repo is said to fix.
