### ISSUE TITLE
Master password required when exporting

### ISSUE THREAD

**Issue by giulios123** [lastpass/lastpass-cli#70]
As title explain, every time I try to do *lpass export* it ask me again for master password.(even if I'm already logged in)

Is it normal or not?

**Comment by bcopeland** [comment]
Yes, this is normal, if any one of your accounts has master password reprompt set (see cmd-export.c:83).

**Comment by giulios123** [comment]
Thanks for the very fast answer; how can I disable the master password reprompt?

**Comment by giulios123** [comment]
Ok found and corrected the problem :+1: 
Thanks, this can be closed

**Comment by bcopeland** [comment]
On Wed, Jan 28, 2015 at 12:52:32PM -0800, Giulio wrote:
> Thanks for the very fast answer; how can I disable the master password reprompt?

In the lastpass vault (website or plugin) you can edit the site and
uncheck 'Require Password Reprompt'.  Unfortunately I don't know an
existing way to list all the sites that have this checked.  An easy
way that involves writing some code would be to add a printf to
cmd-export.c like so:
{{{
    if (account->pwprotect) {
        printf("This account is protected: %s\n", account->name); // <- add
        // and comment out the rest of the block to disable the
        // prompt temporarily...
        // unsigned char pwprotect_key[KDF_HASH_LEN];
        // [...]
        // break;
    }
}}}

**Comment by bcopeland** [comment]
ok closing per above, thanks!
