### ISSUE TITLE
Different version number in brew

### ISSUE THREAD

**Issue by giulios123** [lastpass/lastpass-cli#71]
Hi, I just want to report that the version installed via brew on mac is 0.3.0, while for brew is already at 0.4.0

*Mercurio:~ giulios123$  lpass --version
LastPass CLI v0.3.0*

*Mercurio:~ giulios123$ brew info lastpass-cli
lastpass-cli: stable 0.4.0 (bottled), HEAD*

**Comment by bcopeland** [comment]
Ok, thanks.  Unfortunately 0.4.0 was tagged with the old version string, so this should be fixed in the next release.
