### ISSUE TITLE
Using Shared Folders from cli 

### ISSUE THREAD

**Issue by wrighrc** [lastpass/lastpass-cli#76]
I have a shared folder named Shared-HPC and a subfolder named Omega inside that folder
I created an entry via the gui or web interface named guitest in the shared folder Shared-HPC/Omega
The entry works as expected.

I can not figure out how to create an entry in the shared folder via the cli.

I can get the export entries to match...   
charles@x5:/apps/lastpass-cli$ lpass export | grep testcw
http://test/,,,Omega/testcw,testcw,Omega

charles@x5:/apps/lastpass-cli$ lpass export | grep guitest
chrome://lastpass/content/home2.xul,,,Omega/guitest,guitest,Omega

but export and show have different output and the gui shows testcw was created in a non-shared folder Omega rather than in Shared-HPC/Omega

Apparently export doesn't export everything.

charles@x5:/apps/lastpass-cli$ lpass show --all 4510360566
Omega/testcw [id: 4510360566]  
URL: http://test/

charles@x5:/apps/lastpass-cli$ lpass show --all 4510166626
Shared-HPC/Omega/guitest [id: 4510166626]
URL: chrome://lastpass/content/home2.xul

Any help on how to use the cli to create an entry in a shared folder would be appreciated.
Thanks.

**Comment by steakejjs** [comment]
Hey. 

The GUI name versus the Shared-HPC name not matching is somewhat expected. The "Shared-HPC" is prepended in the GUI to help users understand the consequences of the operations they are making on them. Seeing Shared- helps prevent them people from copying things like personal banking information to a Shared Folder.  This is definitely something that will get added.

For now, Shared Folder support in the CLI is really lacking but I guess the first I will begin working on is creating and adding shared folders.

**Comment by bcopeland** [comment]
As far as export vs show differences -- I think all we need to do is add account->shared, into the account->fullname -- currently it is only 'group' + 'name'

**Comment by bcopeland** [comment]
Please try the latest version - I believe both the export and shared folder creation issues are solved now.

**Comment by bcopeland** [comment]
I'm going to close this as I believe 0.6.0 fixed; please reopen if not.
