### ISSUE TITLE
Show command should have better searching and matching support

### ISSUE THREAD

**Issue by vendion** [lastpass/lastpass-cli#78]
When running ```lpass show``` it should do a fuzzy search or some other kind other searching/pattern matching.  My use case I have a entry in Lastpass with the name "dropbox.com" but running ```lpass show dropbox``` results with the following error:

```
Error: Could not find specified account 'dropbox'.
```

Expected results would have been to match "dropbox.com".  In case of the search returns multiple entries maybe return just the account name and the ID for each account allowing the user to be more explicit about which account they want.  Right now the best the user can do if they don't know the exact name is do a ```lpass ls``` and pipe the output to ```grep``` or some similar tool.

**Comment by bcopeland** [comment]
Try out ```lpass show -F dropbox``` -- that should do what you want.

**Comment by vendion** [comment]
Finally got a chance to test this, running ```lpass show -F dropbox```  does infact find the correct account, although I would say that would have been expected default behaviour.  Is there a way to setup an alias for lastpass commands, I have several accounts like this and having to do ```lpass ls | grep <name>``` or doing the ```-F``` argument all the time would get old fast.

**Comment by bcopeland** [comment]
There is no built in way -- but you can usually do this with a shell alias, e.g. in bash:
```
alias lpshow="lpass show -F"
$ lpshow dropbox
```

**Comment by vendion** [comment]
Yeah I know I can setup an alias at the shell level, just if I could do it
at the application level that would be preferable IMO.

**Comment by bcopeland** [comment]
Ok, I personally don't have plans to work on that in the near term, but I wouldn't object if someone wanted to add support for that along the lines of git aliases.

**Comment by HeathNaylor** [comment]
Is `-F` no longer supported, doesn't seem to be working for me on v1.3.1
