### ISSUE TITLE
Applications missing from `lpass ls`

### ISSUE THREAD

**Issue by Sudrien** [lastpass/lastpass-cli#85]
I've been experimenting with trying to get LastPass for Applications -like functionality in Cinnamon.

Not very far yet.
> http://cinnamon-spices.linuxmint.com/applets/view/60
> sudo apt-get install pinentry-gtk2
> make sure to -f logout

However when I *lpass ls* in console there doesn't seem to be any entries for Applications, much less ids that I can use to get usernames and passwords.

From what I can make of the code, this seems to be more an omission than filtering.

**Comment by Sudrien** [comment]
Think I found the omission.

It's stated UNIQUEIDs are all integers - looking through the vault on firefox, applications have an ID of the format app\d{6,7} - unfortunately I'm dense enough on the code that I'm still am not finding where account->id is actually assigned

**Comment by bcopeland** [comment]
It's hidden behind a macro in blob.c -- see account_parse()

**Comment by jameswhite** [comment]
So is `lpass ls` not returning the entire list the desired behavior here? When I run `lpass ls` (version LastPass CLI v0.8.0, built from a code checkout this morning) I get about 13 of the 29 shared folders I can see in the web interface listed.

**Comment by bcopeland** [comment]
@jameswhite that's probably something different; likely related to #130.  Accounts have to be unhidden to show in cli. 

Not showing applications (what this ticket is about) is just because no one has implemented that yet.

**Comment by jameswhite** [comment]
Ah, thank you @bcopeland.

**Comment by bcopeland** [comment]
So on the topic-app-support branch -- commit ff1d4b4b666182ed34cc8e82aae814e37da72397, there's a start on applications.  You can at least list them and show their contents, but cannot edit them.

**Comment by bcopeland** [comment]
I went ahead and merged this code, which has some basic editing capability.  Please open a new issue if there are missing features you need.
