### ISSUE TITLE
Feature Request - Disable Login Prompt Flag

### ISSUE THREAD

**Issue by stuartcryan** [lastpass/lastpass-cli#86]
I have created an integration with Alfred on OSX which works really well.

However, as we are essentially interacting with the Lastpass CLI programmatically there is a new feature I need.

Take for example the following command:
/usr/local/bin/lpass ls | grep -i crash

If you are not logged in, the CLI puts up a prompt requesting you log in, however with Alfred I am doing this all in the background and force a user to log in with "lplogin" separately which brings up the prompt.

Therefore when running this in the background, the perl script just hangs... therefore I would like to request the following:

New flag created for lpass which is --disable-login-prompt

Desired behaviour of this would be if running:
/usr/local/bin/lpass ls --disable-login-prompt | grep -i crash

If logged in, the application would run, if not logged in it exits with a code other than zero and outputs a message to STDERR stating that the user needs to be logged in.

That would be utterly amazing and would enable better interaction with the lpass agent with a different front end than just an ssh prompt.
Cheers,
Stuart

**Comment by bcopeland** [comment]
I'm not really opposed to this, though it seems pretty specific to this implementation.

One thing to consider is that if user has enabled master password reprompt, the command needs to prompt before showing the details for a given account (e.g. cmd-show.c calls agent_load_key() to accomplish this).  Not sure what to do here for your case.

Also I could envision people wanting to use something besides pinentry to ask for the password (cf. ssh-askpass) -- if we allowed that, and treated error exit as "abort" -- you could perhaps set LP_ASKPASS=/bin/false or something to accomplish this in a different way.

**Comment by stuartcryan** [comment]
Hmm that could possibly work.

I had a bit of a closer look at pinentry and found that there is a flag on it that would be perfect... would there be any way of enabling this in lpass:
 -o, --timeout SECS

that way at least the session would die after x seconds and allow related scripts to error out gracefully, rather than sitting alive indefinitely.

**Comment by stuartcryan** [comment]
Hi Bob,
Have been pondering this a bit more, if there was an option to set LP_ASKPASS to something else, that would actually suit the use case perfectly. I could write a separate script/binary/etc that would work around the specific use case issues.

Would definitely be keen to see that.
Cheers,
Stuart

**Comment by bcopeland** [comment]
Ok I'll put this higher on the TODO.

**Comment by stuartcryan** [comment]
Awesome thank you so much. Really appreciate it.
Cheers,
Stuart

___________________________________________________________________

I live my life by three mottos:
1. It doesn't matter if you are laughing at me or with me... as long as you're laughing. | 2. I might have to grow old, but I will be damned if I ever have to grow up. | 3. If I can end each and every day having put at least one smile on another person's face, it has been a smashing day!

Stuart Ryan
Geek, Blogger and Senior Analyst Programmer | Connect with me on LinkedIn <http://stu.link/LINKEdin> | @StuartCRyan - Twitter <http://stu.link/FOLLOWMETWITTER> | Web: http://stuartryan.com <http://stu.link/STUARTRYAN> | Technical Blog: http://technicalnotebook.com <http://stu.link/TECHNOTEBOOK>
> On 11 Aug 2015, at 4:37 am, Bob Copeland <notifications@github.com> wrote:
> 
> Ok I'll put this higher on the TODO.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lastpass/lastpass-cli/issues/86#issuecomment-129559736>.
> 


 
--------------------------------------------------------------------------
This email has been scanned for spam and viruses by a SpamTitan anti-spam appliance. For more information please visit http://stu.link/SPAMTitan

We use Turnkey Internet for all our hosting needs. http://stu.link/TurnkeyInternet 
--------------------------------------------------------------------------
This email has been scanned for spam and viruses by a SpamTitan anti-spam appliance. For more information please visit http://stu.link/SPAMTitan

We use Turnkey Internet for all our hosting needs. http://stu.link/TurnkeyInternet

**Comment by bcopeland** [comment]
Please try out this branch (& read the commit log for usage).   I'm not going to merge it right away as I want to think about the approach and implementation a bit.

https://github.com/lastpass/lastpass-cli/tree/topic-askpass

**Comment by stuartcryan** [comment]
Awesome will have a play with it this weekend :) thanks so much.
Cheers,
Stuart

___________________________________________________________________

I live my life by three mottos:
1. It doesn't matter if you are laughing at me or with me... as long as you're laughing. | 2. I might have to grow old, but I will be damned if I ever have to grow up. | 3. If I can end each and every day having put at least one smile on another person's face, it has been a smashing day!

Stuart Ryan
Geek, Blogger and Senior Analyst Programmer | @StuartCRyan - Twitter <http://stu.link/FOLLOWMETWITTER> | Web: http://stuartryan.com <http://stu.link/STUARTRYAN> | Technical Blog: http://technicalnotebook.com <http://stu.link/TECHNOTEBOOK>
> On 12 Aug 2015, at 2:18 am, Bob Copeland <notifications@github.com> wrote:
> 
> Please try out this branch (& read the commit log for usage). I'm not going to merge it right away as I want to think about the approach and implementation a bit.
> 
> https://github.com/lastpass/lastpass-cli/tree/topic-askpass <https://github.com/lastpass/lastpass-cli/tree/topic-askpass>
> —
> Reply to this email directly or view it on GitHub <https://github.com/lastpass/lastpass-cli/issues/86#issuecomment-129952834>.
> 


 
--------------------------------------------------------------------------
This email has been scanned for spam and viruses by a SpamTitan anti-spam appliance. For more information please visit http://stu.link/SPAMTitan

We use Turnkey Internet for all our hosting needs. http://stu.link/TurnkeyInternet 
--------------------------------------------------------------------------
This email has been scanned for spam and viruses by a SpamTitan anti-spam appliance. For more information please visit http://stu.link/SPAMTitan

We use Turnkey Internet for all our hosting needs. http://stu.link/TurnkeyInternet

**Comment by stuartcryan** [comment]
Hi Bob,
Slight change of plans :D I got bored and tested it out tonight.

Works an absolute CHARM, I would be very happy with that (or similar) implementation.
Cheers,
Stuart

___________________________________________________________________

I live my life by three mottos:
1. It doesn't matter if you are laughing at me or with me... as long as you're laughing. | 2. I might have to grow old, but I will be damned if I ever have to grow up. | 3. If I can end each and every day having put at least one smile on another person's face, it has been a smashing day!

Stuart Ryan
Geek, Blogger and Senior Analyst Programmer | @StuartCRyan - Twitter <http://stu.link/FOLLOWMETWITTER> | Web: http://stuartryan.com <http://stu.link/STUARTRYAN> | Technical Blog: http://technicalnotebook.com <http://stu.link/TECHNOTEBOOK>
> On 12 Aug 2015, at 2:18 am, Bob Copeland <notifications@github.com> wrote:
> 
> Please try out this branch (& read the commit log for usage). I'm not going to merge it right away as I want to think about the approach and implementation a bit.
> 
> https://github.com/lastpass/lastpass-cli/tree/topic-askpass <https://github.com/lastpass/lastpass-cli/tree/topic-askpass>
> —
> Reply to this email directly or view it on GitHub <https://github.com/lastpass/lastpass-cli/issues/86#issuecomment-129952834>.
> 


 
--------------------------------------------------------------------------
This email has been scanned for spam and viruses by a SpamTitan anti-spam appliance. For more information please visit http://stu.link/SPAMTitan

We use Turnkey Internet for all our hosting needs. http://stu.link/TurnkeyInternet 
--------------------------------------------------------------------------
This email has been scanned for spam and viruses by a SpamTitan anti-spam appliance. For more information please visit http://stu.link/SPAMTitan

We use Turnkey Internet for all our hosting needs. http://stu.link/TurnkeyInternet

**Comment by stuartcryan** [comment]
Hi Bob,
Just thought I would check in, is there any movement on this, would be very keen to start using it in my workflow for the benefit of other lastpass users?
Cheers,
Stuart

**Comment by bcopeland** [comment]
Well, I haven't had any bright ideas since, so I guess I'll merge it :)

**Comment by 5haffl** [comment]
What about adding a new (optional) parameter to the 'login' option, that allows logging in by passing the password as argument? I mean something like:

lpass login USERNAME [ --password="PASSWORD" ]

**Comment by bcopeland** [comment]
I really don't want to add "yet-another-way".  First of all, there might be multiple passwords required if 2fa is enabled, so just one ```--password``` option is not enough.  Second, putting passwords on the command line is a security risk -- other users on the machine can see it in things like ps.

LPASS_ASKPASS should be able to do what you want.  The only problem is it can't communicate errors currently (unlike pinentry) so if you put the wrong password you could get stuck in an auth loop and not know it.  I think that is fixable though.

Or you can use the plaintext-key config option if you really wish to throw caution to the wind.
