### ISSUE TITLE
Bug - Backspace interpreted as character

### ISSUE THREAD

**Issue by stuartcryan** [lastpass/lastpass-cli#87]
Hi Team,
I am not sure if anyone else is suffering this but on OSX using iTerm (or Terminal), when I use:
/usr/local/bin/lpass login --trust "<loginEmail>"

If I accidentally type a character wrong while putting in my password and try to use backspace, it interprets it as a character, therefore I have to cancel and start again.

Is there any possibility of fixing to interpret backspace as an actual backspace?
Cheers,
Stuart

**Comment by stuartcryan** [comment]
I have found if I run export TERM=linux before the command, the backspace then works correctly but the login box looks kinda funky.
i.e. with the term set to linux:
![lplogin_bad](https://cloud.githubusercontent.com/assets/9924832/7105486/15ae4038-e160-11e4-8f59-bd0bb6c02579.jpg)

and normally:
![lplogin_good](https://cloud.githubusercontent.com/assets/9924832/7105489/2641049e-e160-11e4-81b5-ec6b71de8101.jpg)

**Comment by bcopeland** [comment]
Sounds like an issue with the terminal or with pinentry, really, not lastpass-cli.  Can you reproduce if you just run pinentry by itself?  (Run pinentry, and after it displays "OK Your orders please", type GETPIN followed by a newline.  It will display the pin after you submit the dialog.)

**Comment by stuartcryan** [comment]
Ahh you are correct it is with pinentry. Sorry for the hassle guess this can be closed (and learning new lessons every day) :)
Cheers,
Stuart

**Comment by bcopeland** [comment]
Ok - feel free to reopen if you find out there's something (portable) lpass should be doing with regards to setting terminal options when starting pinentry.

**Comment by sethdmoore** [comment]
I also had this problem. OSX 10.10, tmux 2.0 on Terminal.App 2.5.3

```
$ echo $TERM
screen
```

The "solution" was to use ctrl-h as backspace. Terminal.App has "Delete sends Control-H" under Profiles -> Advanced. I've never had to do this before, so it seems kind of silly to turn it on for this one app.

**Comment by bcopeland** [comment]
So maybe we need stty erase setting or something for mac...

**Comment by sethdmoore** [comment]
I have password reprompt enabled for a bunch of passcodes, so I'm not sure this is an option for me(?) - or perhaps I'm misunderstanding the functionality of askpass.

Is there a way to read obfuscated master password from STDIN a la ssh / login / read -s prompts?

I had to turn "delete sends control-h" back off as it was messing with the functionality of nc.

**Comment by bcopeland** [comment]
It will still prompt, it will just prompt with a built-in prompt instead of using an external program to do the prompting.  (I mistyped, I meant "pinentry" not "askpass", corrected above.).  I'm not sure what you mean regarding the obfuscated master password, can you describe what you need to accomplish?  I guess 'expect' could do that.  We've thought about adding an askpass type feature so you can have an external program supply the password, but it doesn't exist yet.
