### ISSUE TITLE
Error: Peer certificate cannot be authenticated with given CA certificates.

### ISSUE THREAD

**Issue by markfaine** [lastpass/lastpass-cli#88]
Lastspass CLI has been working fine then suddenly today I get the following message when attempting login:

Error: Peer certificate cannot be authenticated with given CA certificates.

**Comment by alzeih** [comment]
I believe it's due to https://blog.lastpass.com/2015/04/update-to-ssl-certificate-migrating-from-sha-1-to-sha-256.html/

I fixed it for me by extracting the new root CA from https://lastpass.com/ to replace https://github.com/lastpass/lastpass-cli/blob/master/thawte.pem.

**Comment by markfaine** [comment]
Strange, that didn't work for me.  It doesn't build with the new CA.

certificate.h:1:28: warning: missing terminating " character
\n"----END CERTIFICATE-----7z9M/P2C2F+fpErgUfCJzDupxBdN49cOSvkBPB7
                            ^
certificate.h:2:1: error: stray ‘\’ in program
"
"

**Comment by alzeih** [comment]
Convert from dos line endings to unix

**Comment by markfaine** [comment]
Doh, should have figured that out on my own.  Thanks, that did it.

**Comment by Thermionix** [comment]
curl https://www.thawte.com/roots/thawte_Primary_Root_CA.pem | openssl x509 -outform PEM > thawte.pem

**Comment by olantwin** [comment]
Could this please be fixed by replacing the old cert with the new valid cert? (or maybe there is another possible solution).

I think having to do this workaround to get basic functionality as either a packager or user is not good, especially since a lot of users will not understand what @Thermionix scary looking OpenSSL line does, etc..

**Comment by bcopeland** [comment]
Latest master now has the upgraded cert, sorry about the trouble!

**Comment by olantwin** [comment]
Thank you for the quick fix. Would this issue be worth a small bug-fix release? The current stable release is affected by this bug and thus unusable without the workaround.

For now I'll keep @Thermionix's fix in the Arch User Repository PKGBUILD until the next release.

@bcopeland: This is nice piece of software, keep up the great work ;).

**Comment by cheecheeo** [comment]
I second @olantwin's question. A bug-fix release is in order.

**Comment by bcopeland** [comment]
Okay -- I released 0.5.1 which includes the new cert on top of 0.5.0.  If anyone needs a backport to 0.3.0 or 0.4.0 let me know.

**Comment by olantwin** [comment]
Thank you for the release.

**Comment by cheecheeo** [comment]
@bcopeland thanks! :+1:

**Comment by drzraf** [comment]
Is there strong technical reason to no account on user certs (custom or standard paths, ~/.certs, /etc/ssl/certs, ...)?
A "simple" cert change implicate that all previous versions are unusable, especially considering all the installation from distributions. Hardcoding the certificate makes virtually makes all lpass installed on Debian, Ubuntu, ... useless when it changes.

See issue #31 about offline mode too.

**Comment by bcopeland** [comment]
Unless Thawte transitions to a new root (or LastPass changes providers), the baked in-cert should be good for a good long while even as LP continues to update its server certs.  The transition to sha-256 unfortunately moved LP from the older Thawte Premium Server CA to the newer Thawte Primary Root CA but that is hopefully a one-off kind of situation.

There is a certain degree of extra security by only including that root cert (e.g. if some gov't controlled CA is in local cert store.)

Mainly, though, I'd rather not have to maintain a bunch of different setups for all the different platforms' local cert stores.  That said, I'm not really morally opposed.  If we did so, we'd want to at least the baked-in cert first just in case local cert store is out of date.  Distributions, of course, are welcome to patch how this is done today.

**Comment by bcopeland** [comment]
Hi all,

It appears this issue will once again rear its head in the not too distant future, so I'm reopening this to get visibility and hopefully avoid the surprise factor.  In short LastPass will be getting new certs soon.

I talked out of band with whichever distro maintainers I could dig up, and consensus was that pinning is still desirable despite the occasional hiccup.  To make it somewhat easier, I reworked the way we are doing pinning in the latest HEAD commits: now we pin the keys and let the platform handle validating the chain.
 
On top of that I also added (what I believe to be) the public keys that will be in use in the near future.  I plan to backport these patches to the last few releases.

So, if you upgrade to latest master, you should be all set for the cert update.  Once I do the backport releases, grabbing those versions should also work.  Then once everything is working on the new certs I'll do another patch to reduce the set of pins to the minimum.

Comments welcome.

**Comment by drzraf** [comment]
please stop bundling certificates inside the binary.
The logic behind "new cert" implies "new release" is not future-proof.

Imagine you'd need to change the binary when a new TLS version popup or
when you change your registrar?
Would you imagine to have to update Thunderbird when gmail changes its certificate?

Please provide it as an environment variable, a command line option.
Bundle the cert as a *default* value but please, do not make it mandatory.

I started using a source-compiled version the last time certificate
changed what made the Debian package unusable.
And this will happen again.
IMHO the source code should be able to work consistently at least 1
year.

thx

**Comment by bcopeland** [comment]
This is exactly what we did.  Please see 375b77fc58bcc45c7b9770b04017a4466750ccca.

**Comment by drzraf** [comment]
great!
thank you

**Comment by bcopeland** [comment]
Just to be clear, though: we are now pinning keys, so a key change (but not a certificate change) still implies a new release.  There's a tradeoff here: if we only rely on the platform cert store, then there's a chance that a bad actor or compromised CA (e.g. DigiNotar) could impersonate lastpass.com.  Considering the security focus of the application, I'd rather not allow this by default.  (If you or debian  want it though, you can comment out the line that adds the pin_keys callback).

Pinning keys is a bit of a middle ground: you can renew a cert without regenerating the key.  Or you can pin an intermediate (or root) so you could get a new key and new cert, as long as the intermediate or root pubkey is the same.  And you can specify a backup key in case you need it, so there are more options for maintaining continuity.

So at present we're pinning the root CAs (both old and new) and the leaf keys (production and backup) which should provide several outs for the time being.  Once HPKP is widely deployed we may remove the static pins in favor of that.

Incidentally in the example you give: I believe Chrome and Firefox (not sure about Thunderbird) do statically pin Google keys.  So if Gmail for some reason had to regenerate their key and their backups (however unlikely) -- there is actually a scenario where you could need to update Thunderbird for that.

**Comment by bcopeland** [comment]
The certs are now live, so if you are encountering this today, please update your version of lpass.

**Comment by oblitum** [comment]
I started to get this for the first time today on ArchLinux, I'm on LastPass CLI v1.3.0 from [Community](https://www.archlinux.org/packages/community/x86_64/lastpass-cli/).

**Comment by paulgear** [comment]
I got this for the first time today on Ubuntu Linux 17.10; affects both 1.0.0-1.2 from universe repository, and locally-built version from git head: https://pastebin.ubuntu.com/p/p9MwxG9k3R/

**Comment by jballment** [comment]
This was working perfectly yesterday and today it's stopped working.  I'm getting the following error on Ubuntu 16.04 LTS:

lpass login johnxxxx@xxxxxx
Error: Peer certificate cannot be authenticated with given CA certificates.

**Comment by jballment** [comment]
I've logged a ticket with Lastpass support regarding this issue, the ticket number is 0L887H7N4E8Z.

Regards

John.

**Comment by oblitum** [comment]
I've opened an issue on Arch package but I guess this should be ipstream: https://bugs.archlinux.org/task/58625.

**Comment by brendanlong** [comment]
Looks like lastpass.com has a new certificate, issued on May 2nd:

![screenshot from 2018-05-16 20-33-45](https://user-images.githubusercontent.com/1447206/40150595-83fc0b5c-5948-11e8-9d27-3294ff74b9cd.png)

I'm trying to figure out how to update the pinned certificate.

**Comment by alzeih** [comment]
There's an open issue for this at https://github.com/lastpass/lastpass-cli/issues/409 and a pull request that fixes it at https://github.com/lastpass/lastpass-cli/pull/410

**Comment by userdash** [comment]
Hi,
I have lpass on my ubuntu.. where can i find **pins.h** file to modify for this issue??

Error: Peer certificate cannot be authenticated with given CA certificates.

**Comment by oblitum** [comment]
Just sharing that this has been already fixed on ArchLinux repositories just a day after I [reported](https://github.com/lastpass/lastpass-cli/issues/88#issuecomment-389706788).
