### ISSUE TITLE
"Peer certificate cannot be authenticated with given CA certificates."

### ISSUE THREAD

**Issue by somada141** [lastpass/lastpass-cli#89]
I've installed LastPass CLI v0.5.0 through HomeBrew on my MacBook and when I try to login through the CLI with the following command:

```
lpass login my.email@gmail.com
```

I keep getting the following error:

```
Error: Peer certificate cannot be authenticated with given CA certificates.
```

I should mention that the above works fine on my work iMac so I have no idea what the issue or solution is

**Comment by bcopeland** [comment]
Please upgrade to v0.5.1 -- see https://github.com/lastpass/lastpass-cli/issues/88

**Comment by blunttester** [comment]
LastPass CLI v0.7.0 getting teh same error on Ubuntu 16.04

**Comment by rehmanzile** [comment]
I am experiencing the same error on Ubuntu 16.04 LastPass CLI v0.7.0. When is this bug going to be resolved? It has been more than two months!

**Comment by bcopeland** [comment]
On Thu, Jan 05, 2017 at 09:32:00AM -0800, Zile Rehman wrote:
> I am experiencing the same error on Ubuntu 16.04 LastPass CLI v0.7.0. When is this bug going to be resolved? It has been more than two months! 

You have to ask Ubuntu to make a newer package -- this has been fixed
for almost one whole year!  With backported fixes even.

In the meantime, I guess I'll see what it takes to become empowered enough
to upload packages to the distros...

**Comment by rehmanzile** [comment]
In my opinion, LastPass should have it’s own private repository server that I can point to and grab the debs. Do have a link to a tar ball with the fix?

 

Making a fix readily available to customers is just as important as fixing the issue. My two cents. Thanks.

**Comment by bcopeland** [comment]
The updated tarball is here: https://github.com/lastpass/lastpass-cli/releases/tag/v0.7.2

**Comment by rehmanzile** [comment]
@bcopeland I was able to install it successfully. Thanks for your help!

**Comment by bcopeland** [comment]
Great, thanks for the update.  Still, making packages or contributing more to the packaging process is on the TODO here, lots of people want that.
