### ISSUE TITLE
login prompt forced to stay in foreground

### ISSUE THREAD

**Issue by k0377** [lastpass/lastpass-cli#90]
When I use a dropdown terminal and write the command to login, a lastpass prompt will open and remains in focus, doesnt matter which key I press then. This makes it impossible to use from a dropdown terminal like im using on gnome 3, as I would have to hide it first.

**Comment by bcopeland** [comment]
If I understand correctly: perhaps you could switch to using pinentry-curses?

**Comment by k0377** [comment]
Maybe, it is not that big an issue, still usable but annoying.

![bildschirmfoto vom 2015-05-31 11-40-13](https://cloud.githubusercontent.com/assets/1057526/7901477/decde7ee-0789-11e5-9757-a582acdc7090.png)

**Comment by bcopeland** [comment]
I guess my point is, we're not involved in how pinentry presents itself.  You can "export LPASS_DISABLE_PINENTRY=1" or use pinentry-curses if you want to see it as a text prompt.

**Comment by bcopeland** [comment]
I'm going to close this one as there are workarounds, and we don't actually do this prompt, it's pinentry.
