### ISSUE TITLE
Don't prompt for password if stdin isn't a tty.

### ISSUE THREAD

**Issue by tomprince** [lastpass/lastpass-cli#94]
When using `LPASS_DISABLE_PINENTRY`, if stdin isn't a tty, `lpass` shouldn't prompt for the password. For example, if I'm piping in the output of a different password manager.

**Comment by bcopeland** [comment]
in other words you want it to just read stdin, but not output anything? Sounds reasonable.

**Comment by tomprince** [comment]
Yes.

**Comment by tomprince** [comment]
I'd even be happy if I had to ask for that behaviour explicitly.

**Comment by bcopeland** [comment]
This is not hard to do but, what about just redirecting stderr to /dev/null (the prompt is actually on stderr):
{{{
$ ./something | ./lpass login foo@example.com 2>/dev/null
}}}

**Comment by bcopeland** [comment]
I think the new ```LPASS_ASKPASS``` feature can be used to do whatever you want here.
