### ISSUE TITLE
Login fails after first keystroke

### ISSUE THREAD

**Issue by curtisolson** [lastpass/lastpass-cli#95]
After attempting to login, I get an error after the first keystroke. 

``` 
lpass login user@abc.com
```
``` 
                              ┌───────────────────────────────────────────────────────────────────────┐
                              │ Please enter the LastPass master password for <user@abc.com>.         │
                              │                                                                       │
                              │ Master Password: ____________________________________________________ │
                              │                                                                       │
                              │          <OK>                                         <Cancel>        │
                              └───────────────────────────────────────────────────────────────────────┘
```

After I type in the first letter of my master password I get this. 

```
Error: Failed to enter correct password.
```

AFAIK, I've got all the prerequisites installed. I'm not seeing a lot of options to debug. Any ideas?

**Comment by bcopeland** [comment]
try "export LPASS_DISABLE_PINENTRY=1" ... sounds like an issue with pinentry although exactly what, I am not sure.

**Comment by curtisolson** [comment]
Catch 22. Trying "lpass export LPASS_DISABLE_PINENTRY=1" I get

Error: Could not find decryption key. Perhaps you need to login with `lpass login`.

Is there a config file I can edit to adjust the settings?

**Comment by curtisolson** [comment]
I misunderstood your comment. I saw an "lpass export" command and thought I needed that. Just changing the environment variation with the command you gave me work.

THANKS!
