### ISSUE TITLE
Cert Issue even with v0.50.1

### ISSUE THREAD

**Issue by aziz42424** [lastpass/lastpass-cli#96]
Hi BCopeland,

It is my pleasure to be in communicate with you. It is my first experience to test LastPass in Command-line version and face the following error: (Error: Peer certificate cannot be authenticated with given CA certificates). Even I double click the file and import it without any success.

Any Suggestion how to overcome it?

Regards
Abdulla

**Comment by bcopeland** [comment]
Hmm, I'm unaware of anyone else having issues with 0.5.1 -- can you try with a clean build and make sure the version shows up as 0.5.1?  I just pushed a change so version 0.5.1 shows in master branch as well, you may want to repull.

**Comment by aziz42424** [comment]
Thanks a lot. It works now. I just pull it again, clean build and make again. Just one more inquiry, I'm running LastPass command line in Netbean to easily debugging the code. My question is: is this version using the same files created with lastpass plugins or .exe? mainly talking about (C:\Users\xxxx\AppData\LocalLow\LastPass).

Thanks
Abdulla

**Comment by bcopeland** [comment]
No, lastpass-cli will use a separate data store compared to the plugins.

**Comment by aziz42424** [comment]
Thanks. Any help on which tools is useful to debug command line version in order to understand it's functionality? Is there any full documentation about the source code, commands ..etc

**Comment by bcopeland** [comment]
There is a man page for the commands but no source documentation.  If you want to see its interaction with the LastPass server you can enable the proxy code (grep for '8080') and then run mitmproxy to see requests.  Other than that, just gdb.

**Comment by aziz42424** [comment]
Is gdb will answer my questions on how to generate decryption key, login key, storing local files ... Etc? I know which methods generate each one, but still looking for how it works, method bu method and step by step?

**Comment by bcopeland** [comment]
Unfortunately, no, we don't have that level of documentation.  kdf.c contains all the details regarding generating the key (pbkdf2) and the login hash (basically one more round of pbkdf2).  Please feel free to write some documentation as you go through the source, and send a PR!

I'm going to close this issue as the original problem seems to be fixed.
