### ISSUE TITLE
doesn't support masterpassword reprompt settings

### ISSUE THREAD

**Issue by tsujamin** [lastpass/lastpass-cli#97]
lpass seems to ignore the master-password reprompt settings that can be set in the browser extension/web application versions of lastpass.

I'm not sure of the security implications of this, ie whether passwords could still be dumped by an attacker logged in as the user without being reprompted, but it seems like a reasonable feature to respect these settings.

**Comment by bcopeland** [comment]
So we do actually have code to do reprompt checking when you do show or export - which part is not working?

**Comment by tsujamin** [comment]
In the firefox addon/web based interfaces I've set it to reprompt when logging in/editing a site, however I get no such reprompt when logging in via the commandline
```
benjamin ⤃ lpass login Benjamin@*****
Success: Logged in as Benjamin@**********
benjamin ⤃ lpass show "Development\Servers/cloud.digitalocean.com"
Development\Servers/cloud.digitalocean.com [id: **************]
Username: benjamin.roberts@***************
Password: ********************
URL: *************************
user[email]: benjamin.roberts@**************
user[password]: *******************************
```

just tested against HEAD: `brew reinstall --force lastpass-cli --with-pinentry --HEAD`

**Comment by bcopeland** [comment]
Editing any site, or a particular site?  If you want the former, just disable the agent (export LPASS_DISABLE_AGENT=1 -- and be sure to kill any instance that's currently running.)

If you want the latter, mark the site as "Require Password Reprompt" when editing it in the website/plugin.

I just tested it -- it works for me.  The relevant code from cmd-show is here:
https://github.com/lastpass/lastpass-cli/blob/master/cmd-show.c#L157-L163

**Comment by tsujamin** [comment]
sweet, I'll try disabling the agent
