### ISSUE TITLE
login fails

### ISSUE THREAD

**Issue by binaryorganic** [lastpass/lastpass-cli#99]
New install of lpass and I can't login. 

I get a message that says I'm either connecting from a new location or am using the wrong password. 

I *am* connecting from a new location. I'm getting an email to verify my approval of said location. I'm clicking the verify link. And then when I try to login again I get the same prompt/error (with a new email each time).

**Comment by bcopeland** [comment]
Are you clicking the validation link from that new location?  If not, it will not record the new IP, just the one you click the link from.

You can go into lastpass settings -> advanced settings on the website and select "Skip email verification of unknown devices and locations" to bypass this check.

**Comment by binaryorganic** [comment]
Nope! That must be my problem. This is just a remote headless server, which isn't really setup for checking said email account. Thanks so much!

Sidenote: It might make a lot of sense if, when clicking that link, instead of LastPass telling me I'd successfully verified the new location, it let me know I hadn't ;)

**Comment by bcopeland** [comment]
Yeah I agree -- I think it's quite confusing and raised the issue internally.  At any rate you could also 'wget' the validation URL from there and it should work.

**Comment by binaryorganic** [comment]
Of course! That's definitely what I'll do. Thanks again for your help!

On Mon, Jul 20, 2015 at 10:43 AM, Bob Copeland <notifications@github.com>
wrote:

> Yeah I agree -- I think it's quite confusing and raised the issue
> internally. At any rate you could also 'wget' the validation URL from there
> and it should work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lastpass/lastpass-cli/issues/99#issuecomment-122906724>
> .
>



-- 
Daniel Horton
binaryorganic.com
(440) 316-9866
